### ISSUE TITLE
AppVeyor CI job sometimes failed with nonexistent test file

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1015]
https://ci.appveyor.com/project/groonga/groonga/builds/26144163/job/ahorsc81b5d7398v#L6661

```text
C:/projects/groonga/test/command/grntest/lib/grntest/executors/base-executor.rb:50:in `execute': <test/command/suite/suggest/complete/prefix-rk-search-thrshold-found.test> doesn't exist. (Grntest::NotExist)
```

Why? Test files are just cloned by `git`. Who delete it?

**Comment by kenhys** [comment]
Just running RDP enabled jobs to debug this issue.

**Comment by kenhys** [comment]
As RDP enabled jobs are all passed, I'll retry to reproduce it. 
https://ci.appveyor.com/project/kenhys/groonga/builds/26522606
