### ISSUE TITLE
Build packages for Ubuntu Focal

### ISSUE THREAD

**Issue by timabbott** [groonga/groonga#1084]
We're working on adding support for Ubuntu Focal in Zulip, and noticed you don't have Groonga packages in the PPA for Ubuntu 20.04 Focal.  While I know Focal isn't released yet, would it be possible to add Focal packages to the PPA?

**Comment by kou** [comment]
We'll support Ubuntu Focal in a week!

**Comment by timabbott** [comment]
Awesome!

**Comment by kou** [comment]
Done!
PGroonga for PostgreSQL 12 is also available.
