### ISSUE TITLE
Groonga Windows版に含まれているmecab関連のexeが、複数のセキュリティソフトにウイルスやマルウェアとして誤検知される

### ISSUE THREAD

**Issue by tetradice** [groonga/groonga#1119]
GroongaのWindows版バイナリに含まれている mecab.exe が、いくつかのセキュリティソフトによって
ウイルスもしくはマルウェアと検知されることがあるようです。

VirusTotal（Web上で複数のエンジンによりスキャンをかけてくれるサイト）でmecab.exeをスキャンしたところ、
1/3ほどのエンジンがmecab.exeをウイルスとして検知するという結果となりました。
たとえば、Groonga 10.0.4のWindowsバイナリ（x86版）のzipに含まれるmecab.exeをスキャンすると
下記のような結果となります。（72エンジン中27種類が脅威と判断）
https://www.virustotal.com/gui/file/eb43569bb26ca975a41a64723937adede6afdd9af1faeccc2de052731b133c96/detection

また、私の手元の環境では、Groonga 10.0.4のWindowsバイナリ（x64版）のzipを展開すると
その中に含まれている下記exeファイルが、それぞれAvira AntiVirusによりマルウェアと判断され、隔離対象となります。

* mecab-system-eval.exe
* mecab-dict-index.exe
* mecab.exe
* mecab-dict-gen.exe
* mecab-cost-train.exe
* mecab-test-gen.exe

判断されるのがmecab関連のexeに限られることから、mecabのバイナリにのみ共通する何かのパターンに引っかかっているようです。

**Comment by komainu8** [comment]
手元の環境ではGroonga 10.0.4のWindowsバイナリ（x86版）に同梱の`mecab.exe`はWindows Defenderに検知されたので、それについては、Microsoftへ連絡して誤検知かどうか確認してもらいました。

結果、誤検知とのことでしたので、Windows Defender の定義を更新してもらいました。

以下の手順で Windows Defender を更新いただければ検知されなくなると思います。

```
  1.管理者としてコマンドプロンプトを開き、c:\Program Files\Windows Defenderに移動します。
  2.「MpCmdRun.exe -removedefinitions -dynamicsignatures」を実行します
  3.「MpCmdRun.exe -SignatureUpdate」を実行します
```

Avira AntiVirus で検知される件については、以下のところに誤検知報告用の窓口があるので、そちらに検知された実行ファイルをおくることで、誤検知であれば、以後検知されなくなると思います。

https://www.avira.com/en/analysis/submit?utm_source=CS&utm_medium=KB

また、可能であれば、 以下の4つのzipファイルを展開した際に同じように検知されるかを確認していただくことはできますでしょうか？

* https://github.com/groonga/groonga/releases/download/v10.0.4/groonga-10.0.4-x64.zip
* https://github.com/groonga/groonga/releases/download/v10.0.4/groonga-10.0.4-x86.zip

**Comment by tetradice** [comment]
@komainu8 丁寧なコメントありがとうございます。
Avira AntiVirusの誤検知については、先ほど教えていただいた窓口より、誤検知の報告を行いました。

> https://www.avira.com/en/analysis/submit?utm_source=CS&utm_medium=KB
> 
> また、可能であれば、 以下の4つのzipファイルを展開した際に同じように検知されるかを確認していただくことはできますでしょうか？
> 
> * https://github.com/groonga/groonga/releases/download/v10.0.4/groonga-10.0.4-x64.zip
> * https://github.com/groonga/groonga/releases/download/v10.0.4/groonga-10.0.4-x86.zip

これらの中に含まれるファイルをそれぞれ展開したところ、x64版のexeについて、同様にAviraで誤検知されました。
また、x86版のexeについても、mecab関連のexeをVirusTotalにかけてみたところ
同様にいくつかのエンジンによって誤検知されることを確認しました。

例：groonga-10.0.4-x86.zip のインストーラexe内に含まれるmecab.exeのスキャン結果（72種類中32種類が誤検知）
https://www.virustotal.com/gui/file/0c5e5af0ddef394f4992947a7f869fcf7e8268232214dc2ba9a3a34a1f1d5cdb/detection

**Comment by komainu8** [comment]
誤検知の報告の対応ありがとうございました。

また、検知されるかどうかもご確認いただき、ありがとうございます。ビルド方法に依らず検知されることがわかりました。

アンチウィルスソフトのどのような挙動に引っかかっているのかは、こちらではわからないため、検知されてしまったら、誤検知用の窓口に都度報告していただく形が現実的です。
(アンチウィルスソフトの開発元へ報告することで、お使いのアンチウィルスソフトの品質も向上し、より良いものになると思います。)
