### ISSUE TITLE
groonga-httpdの管理ツールでロゴ画像が表示されていません

### ISSUE THREAD

**Issue by sutamin** [groonga/groonga#1139]
対象バージョン: 10.0.7
00df1ee2cc40dbea8ac029baed07c57e6ead8ddf　の変更による忘れかと思います。

- アイコン画像類が表示されていない
- advance search、editが効かない
- 日本語画面でグラフが表示されていない

**Comment by komainu8** [comment]
@sutamin ご報告ありがとうございます！
以下のコミットで修正しました。次のリリースで修正されます。

cc581c58712c9e928fd26c02770bce410a16a6bd
a895aecced879d3975b13d01bd5224714117529a
3fbc0c91ecdf097a26f8b711572c0f5e7dcc6175
d6008879ca7a41c332ba82bca1443fb288aa7ad0
