### ISSUE TITLE
About error when table does not exist in grn_table_cursor_open 

### ISSUE THREAD

**Issue by naoa** [groonga/groonga#1169]
The following case that did not previously result in an error are now strictly errored by this commit. 

https://github.com/groonga/groonga/commit/ce03c7a85aa6206f4696cdacd0478cf37439a251

Is the behavior that makes an error when the table does not exist at the time of ``grn_table_cursor_open`` mandatory required for the next version or later? If this will be formal specification, I need to modify some applications that call ``grn_table_cursor_open``. 

```
table_create Tags TABLE_PAT_KEY ShortText

table_create Memos TABLE_HASH_KEY ShortText
column_create Memos tag COLUMN_SCALAR Tags

load --table Memos
[
{"_key": "Groonga is fast!", "tag": "Groonga"},
{"_key": "Mroonga is fast!", "tag": "Mroonga"},
{"_key": "Groonga sticker!", "tag": "Groonga"},
{"_key": "Rroonga is fast!", "tag": "Rroonga"}
]

select Memos --limit 0 \
  --drilldown[tags].keys tag_ \\
  --drilldown[tags_all].table tags
```

**Comment by kou** [comment]
`tag_` is not a typo of `tag`, right?

Could you show use case of the previous behavior?

Do you want to ignore invalid key from drilldown keys list?

**Comment by naoa** [comment]
> tag_ is not a typo of tag, right?
> Do you want to ignore invalid key from drilldown keys list?

Yes. I want to ignore invalid key and table in drilldown params.

I am using drilldown against a dynamic column, but that dynamic column may not be generated, depending on user specified settings. Currently our application, drilldown remains specified even in cases where such dynamic columns are not generated. It's a loose implementation because not getting an error without the drilldown keys.  However, due to the above commit, drilldown specify a non-existant table has become a strict error. 

It is desirable for us to specify a non-existent table in the drilldown table without causing an error same as setting a non-existent column in the drilldown keys does not cause an error.

However, since this is caused by loose implementation, it can be avoided by modifying the application side, so it is not a mandatory requirement.

**Comment by kou** [comment]
OK. We ignore `drilldown[].table` with nonexistent table for consistency.

Response doesn't have `{"tags_all": [...]"}` at all. Because we did so for `output_columns`.
Note that this behavior is different with before https://github.com/groonga/groonga/commit/ce03c7a85aa6206f4696cdacd0478cf37439a251 (`{"tags_all"]: [[0], ...]}` exists). Is it OK?

**Comment by naoa** [comment]
> Note that this behavior is different with before ce03c7a ({"tags_all"]: [[0], ...]} exists). Is it OK?

It is OK. Thanks!
