### ISSUE TITLE
sort_keys: expression support may break reference count mode

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1178]
This is a blocker of 11.0.2.

Some `sort_keys` with expression tests are sometimes failed with MSVC and reference count mode:

https://github.com/groonga/groonga/runs/2407120343?check_suite_focus=true#step:25:157

```text
F--- (expected)
+++ (actual)
@@ -10,42 +10,4 @@
 ]
 [[0,0.0,0.0],3]
 select Values --sort_keys 'numbers[1]' --output_columns numbers
-[
-  [
-    0,
-    0.0,
-    0.0
-  ],
-  [
-    [
-      [
-        3
-      ],
-      [
-        [
-          "numbers",
-          "Int32"
-        ]
-      ],
-      [
-        [
-          128,
-          -254
-        ]
-      ],
-      [
-        [
-          127,
-          128,
-          129
-        ]
-      ],
-      [
-        [
-          126,
-          255
-        ]
-      ]
-    ]
-  ]
-]
+[[0,0.0,0.0],[[[3],[["numbers","Int32"]]]]]

===============================================================================
[1] select/sort_keys/expression
  vector                                                       0.6329s [failed]
===============================================================================
```

https://github.com/groonga/groonga/runs/2418462830?check_suite_focus=true#step:25:54

```text
F--- (expected)
+++ (actual)
@@ -10,4 +10,4 @@
 ]
 [[0,0.0,0.0],3]
 select Values --sort_keys '1 + 1, -number' --output_columns number
-[[0,0.0,0.0],[[[3],[["number","Int32"]],[[255]],[[128]],[[-254]]]]]
+[[0,0.0,0.0],[[[3],[["number","Int32"]]]]]

===============================================================================
[0] select/sort_keys/expression/column
  descending                                                   0.6386s [failed]
===============================================================================
```

https://github.com/groonga/groonga/runs/2418462766?check_suite_focus=true#step:25:54

```text
F--- (expected)
+++ (actual)
@@ -10,42 +10,4 @@
 ]
 [[0,0.0,0.0],3]
 select Values --sort_keys 'numbers[1]' --output_columns numbers
-[
-  [
-    0,
-    0.0,
-    0.0
-  ],
-  [
-    [
-      [
-        3
-      ],
-      [
-        [
-          "numbers",
-          "Int32"
-        ]
-      ],
-      [
-        [
-          128,
-          -254
-        ]
-      ],
-      [
-        [
-          127,
-          128,
-          129
-        ]
-      ],
-      [
-        [
-          126,
-          255
-        ]
-      ]
-    ]
-  ]
-]
+[[0,0.0,0.0],[[[3],[["numbers","Int32"]]]]]

===============================================================================
[1] select/sort_keys/expression
  vector                                                       0.7067s [failed]
===============================================================================
```

**Comment by komainu8** [comment]
`proc_select.c`の`grn_select_sort`の`grn_table_sort`で値をソートしている。
ソート結果は、`grn_table_sort data->tables.sorted`に入っていて、この段階で結果が入ってなければ、検索結果を格納するところか、検索結果をソートするところに問題がある。

この段階で結果が入っていれば、結果を表示するところに問題があることがわかる。

**Comment by komainu8** [comment]
ソート結果は入っているように見える。

```
.#<table:no_key (anonymous:2147483649) value:Values size:3 columns:[] ids&values:[
  1:#<record:no_key:Values id:3 number:[-254]>, 
  2:#<record:no_key:Values id:1 number:[128]>, 
  3:#<record:no_key:Values id:2 number:[255]>
] subrec:none>

F--- (expected)
+++ (actual)
@@ -10,4 +10,4 @@
 ]
 [[0,0.0,0.0],3]
 select Values --sort_keys '1 + 1, -number' --output_columns number
-[[0,0.0,0.0],[[[3],[["number","Int32"]],[[255]],[[128]],[[-254]]]]]
+[[0,0.0,0.0],[[[3],[["number","Int32"]]]]]
```

**Comment by komainu8** [comment]
ソート結果が入っているように見えたが、HTTPのレスポンスを返す直前で値を出力したところ入っていなかった。
ソート結果を格納する箇所に問題がありそう。

```
output_table:
#<table:no_key (anonymous:2147483649) value:Values size:0 columns:[] ids&values:[
] subrec:none>
http_responce_body:
"[[[3],[[\"number\",\"Int32\"]]]]"
http_output_send1:
"[[[3],[[\"number\",\"Int32\"]]]]"
```

**Comment by komainu8** [comment]
結果のソートは `sort_value_execute_expr` で実行している。
この段階でソート対象の値が取得出来ているのか確認する。

取得できていないなら、検索結果を取得するところに問題があるか、検索結果がそもそも入ってないか。
取得できてきるなら、値をソートするところか、ソート結果を格納するところに問題があると判断できる。

**Comment by komainu8** [comment]
ソートした値が出力されないときは `sort_value_execute_expr`が呼ばれてないので、値をソートする処理が実行されない。
`grn_table_sort`は呼ばれているのでそこから、コールツリーをたどってどこまで、呼び出されているのか確認する。

**Comment by komainu8** [comment]
`grn_table_sort`の次は、`grn_table_sort_value`が呼ばれるはずだが、現象が起こるときは、`grn_table_sort_value`が呼ばれてないので、この関数が呼ばれない原因を特定する。

**Comment by komainu8** [comment]
なぜか、 https://github.com/groonga/groonga/blob/master/lib/sort.c#L1056 の `keys->flags & GRN_TABLE_SORT_GEO`の条件が`true`になり、 https://github.com/groonga/groonga/blob/master/lib/sort.c#L1066 に飛んで、`goto exit` するのでソート結果がセットされない。

`GRN_TABLE_SORT_GEO`をセットする処理は実行されていないので、 `keys->flags` の値がどこかで意図しない値に設定されている。

**Comment by komainu8** [comment]
`keys`は、`grn_select_sort`で設定されるので、 `grn_select_sort`から`grn_table_sort`の間で`keys->flags`を設定している箇所を探す。

**Comment by komainu8** [comment]
`keys->flags`の値は`0x0f`だったり`0x62`だったり一定しない。

**Comment by kou** [comment]
だったら未初期化かすでに解放されてしまっているかも。

**Comment by komainu8** [comment]
`keys->flags`にソートフラグを設定しているのが https://github.com/groonga/groonga/blame/master/lib/sort.c#L1253 しかなく、それ以外のパスでは、 ローカル変数の`flag`にしかソートフラグが設定されないため、 https://github.com/groonga/groonga/blame/master/lib/sort.c#L1253 以外のパスでは、未初期化の値が`keys->flags`に設定されている、そのため、意図しない処理が実行されていたと思われる。

`keys->flags`の値が一定しないのもそのせいと思われる。

**Comment by komainu8** [comment]
> だったら未初期化かすでに解放されてしまっているかも。

未初期化っぽいです。

**Comment by komainu8** [comment]
https://github.com/komainu8/groonga/runs/2453776812?check_suite_focus=true にて修正したものを確認中。

**Comment by komainu8** [comment]
修正してテストを流した結果、現象が収まったので、 https://github.com/groonga/groonga/issues/1178#issuecomment-828100701 が原因と特定。修正内容をPRにする。
