### ISSUE TITLE
Introduce EditorConfig

### ISSUE THREAD

**Issue by HashidaTKS** [groonga/groonga#1185]
It seems that our style and your editor configuration use difference style. How about introducing `.editorconfig` as a separated pull request?

_Originally posted by @kou in https://github.com/groonga/groonga/pull/1177#discussion_r624757918_

**Comment by HashidaTKS** [comment]
#1191

**Comment by komainu8** [comment]
We close this issue.
Because this issue has alredy fixed at #1191.
