### ISSUE TITLE
adminサイトの管理モードが機能していません

### ISSUE THREAD

**Issue by poti-top** [groonga/groonga#1186]
レコード一覧の管理モードチェックボックスにチェックを入れていても、非管理モードに入力されている検索クエリが送信されてしまいます。
チェックボックスの状態を取得するのに.attr()が使われている箇所が原因かと思われます。
https://github.com/groonga/groonga/blob/e297e079af21c34e1fb5a0300d55db6242419a6c/data/html/admin/assets/groonga-admin.js#L177

**Comment by kou** [comment]
なるほど！
それを修正するpull requestを作ることはできますか！？

**Comment by HashidaTKS** [comment]
以下のコミットで修正しました。
次回のリリースから修正されます。

https://github.com/groonga/groonga/commit/f57c8763a263c4f41b76d9c96dfdafa152d7e17b
