### ISSUE TITLE
grn_snip_add_cond(): accept 32 or more keywords

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1309]
The current implementation has fixed size (32) `snip_cond` buffer as `grn_snip::cond`. See `lib/grn_snip.h` for details.

We can accept 32 or more keywords by allocating the buffer dynamically with `GRN_REALLOC()` like `ctx->impl->stack` in `expr.c`.

**Comment by kou** [comment]
@HashidaTKS You may want to work on this.

**Comment by HashidaTKS** [comment]
Sure. I will work on this.

**Comment by kou** [comment]
Done by #1313.
