### ISSUE TITLE
Summarize changes from Groonga 11.0.0 to Groonga 11.1.3.

### ISSUE THREAD

**Issue by komainu8** [groonga/groonga#1315]
We want to summarize changes from Groonga 11.0.0 to Groonga 11.1.2. (However, Groonga 11.1.2 doesn't release yet. Groonga 11.1.2 will release on 2021/1/29.)
Because Groonga will update the major version on 2021/2/9, we will announce to users the changes for one year.

Therefore, we will add the changes for one year in Groonga's news.

**Comment by komainu8** [comment]
@HashidaTKS 
Could you work on this issue?
The due date of this work is 2021/2/2.

**Comment by komainu8** [comment]
In my mind, the tasks of this issue are in the following.

1. we add summarize of changes from Groonga 11.0.0 to Groonga 11.1.2 to `doc/news.rst` as below.

```
.. -*- rst -*-

:orphan:

News
====

.. _release-12-0-0:

Release 12.0.0 - 2022-02-09
---------------------------

Summarize of changes from Groonga 11.0.0 to 11.1.2
--------------------------------------------------

* ...
* ...
* ...
```

2. we translate to Japanese `doc/news.rst` by the following command.

```
$ make -C doc html
```

3. we add Japanese translation to `doc/locale/ja/LC_MESSAGES/news.edit`.

4. we translate to Japanese `doc/news.rst` by the following command.

```
$ make -C doc html
```

5. we confirm deliverable by the following commands.

```
$ (your web browser) doc/locale/ja/html/news.html
$ (your web browser) doc/locale/en/html/news.html
```

**Comment by komainu8** [comment]
@HashidaTKS 
Would it be any trouble in terms of time if I asked you to do this work?

**Comment by HashidaTKS** [comment]
Sorry for the delay of an response.
I want to work on this but I'm very busy these days and not confident that I can finish it by the deadline...

**Comment by komainu8** [comment]
I see. Thank you for your response.
I'll work on this issue.

**Comment by HashidaTKS** [comment]
I will work on this.

I have a question.
What means "summarize of changes" in this?
Picking up major changes from 11.0.0 to 11.1.2?

**Comment by komainu8** [comment]
We want to announce to users how convenient Groonga has become In comparison to the past year.
Therefore, we hope to pick up the feature that is useful by users.

**Comment by HashidaTKS** [comment]
Thanks!
I will try to create the summary.

**Comment by kou** [comment]
Done by #1324.
