### ISSUE TITLE
doc: others.rstをautotools.rstとcmake.rstに分離する。

### ISSUE THREAD

**Issue by HashidaTKS** [groonga/groonga#1412]
`others.rst`は「インストールにまつわるその他」ではなく、「その他の環境向け」という記事だと思うのですが、実質的にはAutotoolsでのビルドの仕方を解説しています。これを分離して、以下のようにするほうが良いのではないかと考えています。

* others.rst
  * `autotools.rst`と`cmake.rst`への参照を追加して、手動ビルドしてください、という旨の記載にする
  * cmakeのみでビルドするようになったら`autotools.rst`へのリンクは消す。
* autotools.rst（新設）
  * Autotoolsでのビルド方法について記載 
  * 今のothers.rstのほぼコピー
  * 将来的にcmakeのみでビルドするようになったら消す。
* cmake.rst（新設）
  * cmakeでのビルド方法について記載 
  * 今の`cmake_options.rst`の内容を補強して、（ビルドに必要なライブラリなど）`unix_cmake.rst`と`windows_cmake.rst`を統合した内容にして新設。

いかがでしょうか？

_Originally posted by @HashidaTKS in https://github.com/groonga/groonga/pull/1403#discussion_r964375558_

**Comment by abetomo** [comment]
`autotools.rst`: Autotoolsは廃止予定のため対応なし。
`cmake.rst`: 最低限の情報は記載済。適宜必要なオプションなどを追記する。
