### ISSUE TITLE
doc: make-update-latestの後にコミットするように追記

### ISSUE THREAD

**Issue by HashidaTKS** [groonga/groonga#1440]
https://groonga.org/ja/docs/contribution/development/release.html#make-update-latest-release

でmake-update-latestの後のみコミットする旨がない。
筆者はmake-update-latestの中でやってくれているのかと誤解した。
差分を見れば気付くだけの話ではあるのだが、他の手順ではコミットする旨を記載しているので、それに合わせる。

**Comment by kou** [comment]
`make update-latest-release`の中でコミットするようにしてもいいっすよ。

**Comment by HashidaTKS** [comment]
`make update-latest-release` の後にcommitまでするように変更するPRを作った。

**Comment by HashidaTKS** [comment]
[#1464](https://github.com/groonga/groonga/pull/1464)　でコミットするように対応した。
