### ISSUE TITLE
Feature Request: Dynamic highlight tag for highlighter function

### ISSUE THREAD

**Issue by askdkc** [groonga/groonga#1453]
Groonga highlighter function only outputs `<span class="keyword">` tag for highlighting.
It is useful if we can pass any tag name as a parameter to highlighter function so that output HTML tag can be like `<mark>`, `<div class="grn-highlight">`, `<span class="snippet-highlight">` or anything you want it to be.

https://github.com/groonga/groonga/blob/9ac42413166ea63386437572706f53f516529fe1/lib/highlighter.c#L111-L114

**Comment by askdkc** [comment]
mroongaでは実現できてるこの機能、groongaやpgroongaには来ないですかね？

https://github.com/mroonga/mroonga/issues/569

**Comment by kou** [comment]
Implemented.
