### ISSUE TITLE
github issue: use form

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1465]
**Is your feature request related to a problem? Please describe.**

Raw template Markdown isn't user friendly.

**Describe the solution you'd like**

We can use form: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Describe alternatives you've considered**

None.

**Additional context**

The default template Markdown isn't suitable for us. For example, we don't need "Describe the solution you'd like", "Describe alternatives you've considered" and "Additional context" for feature request. We just need "what is your problem" and "how to reproduce it".

But the default template Markdown problem is a separated issue with this.

**Comment by HashidaTKS** [comment]
I have changed to use the form for bug report and feature request.
And also I have changed to require "what is your problem" and "how to reproduce it" for feature request.

I am doing the same modification for Mroonga and PGroonga
