### ISSUE TITLE
Request document for similarity search

### ISSUE THREAD

**Issue by ShaolanTech** [groonga/groonga#1545]
### What is your problem?

we indexed more than 80000000 documents (English) and need to do similarity search against one field, but the document section is empty.
and till now,the only thing i got is the query format *S "my query phrase", but cannot find how to sort by the "most similar", and i found the "_score" column is not something with the real "similarity value".

**Comment by kou** [comment]
It may not be enough but there is a document for similarity search: https://groonga.org/docs/reference/grn_expr/script_syntax.html#similar-search-operator

`_score` has a similarity value. It's just not normalized to `[0,1.0]`. So you can use `--sort_keys _score` to sort by similarity.

**Comment by ShaolanTech** [comment]
thanks but not too much help, maybe i've some misunderstanding ,here is the screenshot  [http://cdn.xuezheku.com/images/groonga.png](url) ,so the title and the result is not similar at all

**Comment by kou** [comment]
You should use `_score` not `-_score`.

**Comment by ShaolanTech** [comment]
ok changed to _score ,and screenshot [http://cdn.xuezheku.com/images/groonga1.png](url)
and at least the top one of the results should be the title itsself (most similar), so i suppose, is there any posibility that i made the wrong index,here is the index def:[http://cdn.xuezheku.com/images/groonga3.png](url)

**Comment by kou** [comment]
Ah, sorry. `-_score` is correct. (`_score` is wrong.)

Could you show your table definition of the index?

**Comment by ShaolanTech** [comment]
table defination:
[http://cdn.xuezheku.com/images/groonga4.png](url)
field definations:
[http://cdn.xuezheku.com/images/groonga5.png](url)

**Comment by kou** [comment]
I want to see the definition of the table of `tzc_document_T1`.

**Comment by kou** [comment]
Thanks.
It looks OK to me.

Target texts may be too short for Groonga's similar search.

Groonga's similar search extracts feature words from the given query and run OR full text search for these feature words.
If each target text has a little words, most feature words are included in many target texts. It doesn't return good result.

(Feature words are words that are appeared only little target texts.)

Can you try with body not title?

**Comment by ShaolanTech** [comment]
Thanks for your reply buddy.
We are working on something about article papers searching. the scenario im dealing with is "Find an article by title", it seems like 百度 or google. 
Till now phrase search and nested phrase search meets my requirement, they are googd features, and the similarity search is still an importance part of my work, so i will try other solutions.

**Comment by kou** [comment]
Document embedding may be needed for your use case.
It's not documented yet but there are some tokenizers for (simple) document embedding approaches:
* https://github.com/groonga/groonga/tree/master/test/command/suite/tokenizers/document_vector_tf_idf
* https://github.com/groonga/groonga/tree/master/test/command/suite/tokenizers/document_vector_bm25
