### ISSUE TITLE
website needs to update the latest release info

### ISSUE THREAD

**Issue by chenrui333** [groonga/groonga#1596]
### What happend?

Looks like the website still use 13.0.4 as latest stable release

![image](https://github.com/groonga/groonga/assets/1580956/a689d770-76b7-46ab-8413-a623763d0459)

relates to https://github.com/Homebrew/homebrew-core/pull/138593

**Comment by kou** [comment]
Good catch!
I've updated!

**Comment by chenrui333** [comment]
Thanks @kou!
