### ISSUE TITLE
Unsatisfied dependency for libgroonga 13.0.6 in debian bookworm

### ISSUE THREAD

**Issue by josepsanzcamp** [groonga/groonga#1607]
### What happend?

Hi team.

I'm using debian 12 (bookworm) and I'm getting this error when trying to do an upgrade:

The following packages have unmet dependencies:
 libgroonga0 : Depends: libarrow1300 (>= 13.0.0) but it is not installable

Seems that this dependency is available for bullseye but not for bookworm.

- https://packages.groonga.org/debian/pool/bullseye/main/a/apache-arrow/

Thanks in advance.

Josep.

### How to reproduce it

Simply, performs and update of the system:

```
# sudo apt update

# apt list --upgradable

Listing... Done
libgroonga-dev/bookworm 13.0.6-1 amd64 [upgradable from: 13.0.5-1]
libgroonga0/bookworm 13.0.6-1 amd64 [upgradable from: 13.0.5-1]

# sudo apt upgrade

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libgroonga-dev libgroonga0
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

# sudo apt upgrade --with-new-pkgs libgroonga-dev libgroonga0

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgroonga0 : Depends: libarrow1300 (>= 13.0.0) but it is not installable
E: Broken packages
```

### Expected behavior

A successful upgrade to the latest released packages

### Environment

- OS: GNU/Linux
- OS Version: Debian 12 Bookworm
- Groonga version: 13.0.6

**Comment by kenhys** [comment]
You need to follow the instruction on bookworm

https://groonga.org/docs/install/debian.html#bookworm

Especially setup  apache-arrow repository in advance. (changed to use it since bookworm)

> wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
% sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb

**Comment by josepsanzcamp** [comment]
OK!!!

A lot of thanks by your quick response.

Josep.

**Comment by kenhys** [comment]
@komainu8

pinning this issue or appropriate one may be better to notify existing users for a while.

**Comment by komainu8** [comment]
@kenhys Thank you for your advice!
I've pinned this issue and announced.

**Comment by andersk** [comment]
This extra apache.jfrog.io repository is currently broken. It seems to have a record of going down at this time every year when its JFrog plan expires.

- apache/arrow#40744
