### ISSUE TITLE
ci macos: try memory file system

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1644]
### What is your problem?

Tests on macOS is too slow.

For example, "Test: stdio" takes 35m+ on macOS https://github.com/groonga/groonga/actions/runs/7218101124/job/19666979207 but it takes 3m+ on Linux: 

Let's try ramfs with `hdiutil` to reduce CI time.

**Comment by abetomo** [comment]
On my local Mac, it seemed that `init_default_hostname()` was slow, not IO.
The test completed stably without running `init_default_hostname()`.
The results of the CI in my repository are as follows.

### Commit

https://github.com/abetomo/groonga/commit/c07a1af8f5f6593ffd7e32cfaa504685875fc8c9

### CI: Autotools

All three times were completed without timeout.

1. https://github.com/abetomo/groonga/actions/runs/7792865204/job/21251642858
2. https://github.com/abetomo/groonga/actions/runs/7792865204/job/21252289037
3. https://github.com/abetomo/groonga/actions/runs/7792865204/job/21252812071

### CI: CMake

All three times were completed without timeout.

1. https://github.com/abetomo/groonga/actions/runs/7792865195/job/21251643506
2. https://github.com/abetomo/groonga/actions/runs/7792865195/job/21252595915
3. https://github.com/abetomo/groonga/actions/runs/7792865195/job/21253503211

**Comment by kou** [comment]
Let's remove `init_default_hostname()`. We can always use `localhost` as the default host name.
