### ISSUE TITLE
test: re-add `unify_to_katakana` tests

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1673]
### What is your problem?

I removed them in 6c58f5bc3e5e0f3980ffb3390fe642380573efb5 accidentally. Sorry.

They should have been moved to `test/command/suite/normalizers/nfkc/unify_to_katakana/`.

**Comment by abetomo** [comment]
### Files that seem to be the target.

`git show 6c58f5b --name-only | grep unify_to_katakana`

* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/a.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/a.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ba.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ba.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/combining_katakana_hiragana_semi_voiced_sound_mark.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/combining_katakana_hiragana_semi_voiced_sound_mark.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/combining_katakana_hiragana_voiced_sound_mark.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/combining_katakana_hiragana_voiced_sound_mark.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/da.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/da.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/etc.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/etc.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ga.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ga.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ha.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ha.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ka.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ka.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/katakana_hiragana_semi_voiced_sound_mark.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/katakana_hiragana_semi_voiced_sound_mark.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/katakana_hiragana_voiced_sound_mark.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/katakana_hiragana_voiced_sound_mark.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ma.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ma.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/na.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/na.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/pa.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/pa.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ra.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ra.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/sa.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/sa.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ta.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ta.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/wa.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/wa.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ya.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/ya.test
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/za.expected
* [ ] test/command/suite/normalizers/nfkc100/unify_to_katakana/za.test

**Comment by abetomo** [comment]
We will take [this change](https://github.com/groonga/groonga/commit/82894091ff6d347c68280da5e54982a50dd65b1b) as well and re-add the tests.

**Comment by abetomo** [comment]
I finished re-adding the tests.
