### ISSUE TITLE
Should be a test for `NormalizerNFKC{ENV['NFKC']}`

### ISSUE THREAD

**Issue by abetomo** [groonga/groonga#1680]
### What is your problem?

Some tests support only one version.
For example:  https://github.com/groonga/groonga/blob/main/test/command/suite/normalizers/nfkc/unify_kana_hyphen/with_unify_hyphen.test

Change to test with multiple versions.

**Comment by abetomo** [comment]
Files that seem to be the target.

`grep -lr 'NormalizerNFKC[0-9]' test/command/suite/normalizers/nfkc`

* [ ] test/command/suite/normalizers/nfkc/mix/katakana/di.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/di.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/du.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/du.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/du_small.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/du_small.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/gu_small.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/gu_small.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/hyphen_family.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/hyphen_family.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/middle_dot.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/middle_dot.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/a.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/a.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ba.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ba.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/da.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/da.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/du_small.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/du_small.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ga.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ga.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ha.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ha.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ja.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ja.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ka.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ka.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ma.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ma.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/n.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/n.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/na.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/na.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/pa.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/pa.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/prolonged_sound_mark_family.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/prolonged_sound_mark_family.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ra.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ra.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/sa.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/sa.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ta.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ta.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/va.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/va.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/vu.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/vu.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/wa.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/wa.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ya.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/ya.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/za.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/za.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/zu_small.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/prolonged_sound_mark/zu_small.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/small.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/small.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/trailing_o.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/trailing_o.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/v.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/v.test
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/zu_small.expected
* [ ] test/command/suite/normalizers/nfkc/mix/katakana/zu_small.test
* [ ] test/command/suite/normalizers/nfkc/mix/unify_katakana_du_sound_and_zu_small_sounds.expected
* [ ] test/command/suite/normalizers/nfkc/mix/unify_katakana_du_sound_and_zu_small_sounds.test
* [ ] test/command/suite/normalizers/nfkc/mix/unify_katakana_v_sounds_and_kana.expected
* [ ] test/command/suite/normalizers/nfkc/mix/unify_katakana_v_sounds_and_kana.test
* [ ] test/command/suite/normalizers/nfkc/remove_symbol.expected
* [ ] test/command/suite/normalizers/nfkc/remove_symbol.test
* [ ] test/command/suite/normalizers/nfkc/strip/both.expected
* [ ] test/command/suite/normalizers/nfkc/strip/both.test
* [ ] test/command/suite/normalizers/nfkc/strip/end.expected
* [ ] test/command/suite/normalizers/nfkc/strip/end.test
* [ ] test/command/suite/normalizers/nfkc/strip/start.expected
* [ ] test/command/suite/normalizers/nfkc/strip/start.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/a.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/a.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ba.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ba.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/da.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/da.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/etc.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/etc.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ga.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ga.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ha.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ha.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ka.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ka.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ma.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ma.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/n.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/n.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/na.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/na.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/pa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/pa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ra.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ra.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/sa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/sa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ta.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ta.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/wa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/wa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ya.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/ya.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/za.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/hiragana/za.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/a.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/a.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ba.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ba.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/da.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/da.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ga.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ga.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ha.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ha.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ka.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ka.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ma.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ma.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/n.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/n.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/na.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/na.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/pa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/pa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ra.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ra.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/sa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/sa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ta.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ta.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/va.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/va.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/wa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/wa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ya.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/ya.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/za.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/katakana/za.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/with_unify_hyphen.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/with_unify_hyphen.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/with_unify_katakana_trailing_o.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_hyphen/with_unify_katakana_trailing_o.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/a.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/a.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ba.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ba.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/da.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/da.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/etc.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/etc.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ga.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ga.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ha.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ha.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ka.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ka.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ma.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ma.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/n.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/n.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/na.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/na.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/pa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/pa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ra.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ra.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/sa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/sa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ta.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ta.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/wa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/wa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ya.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/ya.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/za.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/hiragana/za.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/a.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/a.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ba.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ba.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/da.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/da.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ga.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ga.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ha.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ha.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ka.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ka.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ma.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ma.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/n.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/n.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/na.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/na.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/pa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/pa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ra.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ra.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/sa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/sa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ta.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ta.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/va.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/va.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/wa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/wa.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ya.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/ya.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/za.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/katakana/za.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/with_unify_katakana_trailing_o.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/with_unify_katakana_trailing_o.test
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/with_unify_prolonged_sound_mark.expected
* [ ] test/command/suite/normalizers/nfkc/unify_kana_prolonged_sound_mark/with_unify_prolonged_sound_mark.test
* [ ] test/command/suite/normalizers/nfkc/unify_katakana_v_sounds/only.expected
* [ ] test/command/suite/normalizers/nfkc/unify_katakana_v_sounds/only.test
* [ ] test/command/suite/normalizers/nfkc/unify_katakana_v_sounds/with_unify_kana_case.expected
* [ ] test/command/suite/normalizers/nfkc/unify_katakana_v_sounds/with_unify_kana_case.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/a.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/a.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ba.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ba.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/da.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/da.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/etc.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/etc.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ga.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ga.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ha.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ha.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ka.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ka.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ma.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ma.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/n.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/n.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/na.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/na.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/pa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/pa.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ra.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ra.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/sa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/sa.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ta.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ta.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/wa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/wa.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/xtsu.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/xtsu.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ya.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/ya.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/za.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/hiragana/za.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/a.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/a.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ba.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ba.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/da.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/da.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/etc.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/etc.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ga.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ga.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ha.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ha.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ka.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ka.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ma.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ma.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/n.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/n.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/na.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/na.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/pa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/pa.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ra.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ra.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/sa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/sa.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ta.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ta.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/wa.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/wa.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/xtsu.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/xtsu.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ya.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/ya.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/za.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/katakana/za.test
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/mixed.expected
* [ ] test/command/suite/normalizers/nfkc/unify_to_romaji/mixed.test

**Comment by abetomo** [comment]
I'm thinking of replacing it automatically because there are so many files, what do you think?
For example, the following script.

```bash
test_file=$1
expected_file=$(echo ${test_file} | sed 's/\.test$/.expected/')

cat <<TEST_COMMAND > ${test_file}
#@add-substitution /NormalizerNFKC(\d*)/ "NormalizerNFKC#{ENV['NFKC'] || '100'}" "NormalizerNFKC"
$(sed 's/                   /                /' ${test_file} | sed 's/NormalizerNFKC150/NormalizerNFKC/')
#@remove-substitution /NormalizerNFKC(\d*)/
TEST_COMMAND

cat <<EXPECTED > ${expected_file}
$(sed 's/                   /                /g' ${expected_file} | sed 's/NormalizerNFKC150/NormalizerNFKC/')
EXPECTED
```

Example of replacement with this script: #1684

**Comment by kou** [comment]
I'm OK with the approach.

**Comment by kou** [comment]
FYI: We can use multiple substitutions by one `sed` call:

```bash
sed \
  -e 's/                   /                /' \
  -e 's/NormalizerNFKC150/NormalizerNFKC/' \
  ${test_file}
```
