### ISSUE TITLE
 doc: add steps for updating documentation to document contribution page

### ISSUE THREAD

**Issue by otegami** [groonga/groonga#1733]
## What is your problem?
As a new contributor, I find it challenging to understand the process for contributing updates to the Groonga documentation. It would be helpful for them to add following steps to `introduction.rst`.
- Editing the documentation
- Previewing changes
- Submitting changes

## My suggestions
I propose to add a new sections to the `introduction.rst` about the documentation update process.
- [x] Edit Documentation Sources
- [ ] ~~Reflect Your Modifications~~
- [x] Preview Your Modifications on HTML
- [x] Update Translations
- [x] Reflect Your Translations
- [x] Preview Your Translations on HTML
- [x] Send Pull Request to Groonga Repository
- [x] Add the link for Sending patch in Preview Your Modifications on HTML

## Next Steps after this issue
The content will be similar a little bit to the I18N page, but with a new flow. 
We'll think about combining them after updating this `introduction.rst`.

<details>
<summary>Outdated: First feature request</summary>

# Split contribution/documentation/introduction.rst into Two Pages like introduction and editing_guide

### What is your problem?

To improve the contribution guide, I propose restructuring the current `contribution/documentation/introduction.rst` by splitting it into two separate pages. This change focuses on the following parts.
1. Guide the process of building the documentation for viewing purposes as a previous step for contribution
2. Guide the process of editing and submitting changes via pull requests for contribution

## Proposed Changes:
I want to write the content like the following each page.
- Introduction.rst
  - Topic: Guide the process of building the documentation for viewing purposes as a previous step for contribution
  - Sections:
    - Introduction
    - How to fork and clone the Groonga repository
    - Install depended software
    - Run cmake with --preset=doc
    - Generate HTML
- (New Page) editing_guide.rst
  - Topic: Guide the process of editing and submitting changes via pull requests for contribution
  - Sections:
    - How to edit document
    - Edit documentation sources
    - Reflect your modifications
    - Preview your modifications on HTML
    - Update translations
    - Reflect your translations
    - Preview your translations on HTML
    - Send pull request to Groonga Repository

## Expected TODO List
- Introduction.rst
  - [ ] Remove the Update section from introduction.rst 
- (New Page) editing_guide.rst
  - [ ] Add new editing_guide page under `contribution/documentation/` 
  - [ ] Write the following section one by one
    - How to edit document
    - Edit documentation sources
    - Reflect your modifications
    - Preview your modifications on HTML
    - Update translations
    - Reflect your translations
    - Preview your translations on HTML
    - Send pull request to Groonga Repository

</details>

**Comment by abetomo** [comment]
Is there a purpose of having the same structure as [this document](https://groonga.org/docs/contribution/documentation/i18n.html) and splitting the common parts?
If so, why not start by making `contribution/documentation/introduction.rst` the same structure, instead of splitting it up first?
It seems to me that this would make it easier to check common parts.

**Comment by otegami** [comment]
@abetomo 
Thanks. I agree with your opinion because in this moment we are not sure splitting this document is better way.
I will update the current document and then think of the next step. How do you think of the following idea? If you agree with me, I will change the title and content of this issue.

# doc: add steps for updating documentation to document contribution page

## What is your problem?
As a new contributor, I find it challenging to understand the process for contributing updates to the Groonga documentation. It would be helpful for them to add following steps to `introduction.rst`.
- Editing the documentation
- Previewing changes
- Submitting changes

## My suggestions
I propose to add a new sections to the `introduction.rst` about the documentation update process.
- [ ] Edit Documentation Sources
- [ ] Reflect Your Modifications
- [ ] Preview Your Modifications on HTML
- [ ] Update Translations
- [ ] Reflect Your Translations
- [ ] Preview Your Translations on HTML
- [ ] Send Pull Request to Groonga Repository

## Next Steps after this issue
The content will be similar a little bit to the I18N page, but with a new flow. 
We'll think about combining them after updating this `introduction.rst`.

**Comment by abetomo** [comment]
I think that is a good way to proceed.

**Comment by otegami** [comment]
Thanks! I've just updated the issue.
