### ISSUE TITLE
NormalizerNFKC: add an option to remove diacritical mark

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1755]
### What is your problem?

See pgroonga/pgroonga#418 for details.

**Comment by otegami** [comment]
What I will do as a next
- [ ] Search for the specification of diacritical marks
- [ ] Make implementation plans

**Comment by otegami** [comment]
> Search for the specification of diacritical marks

下記の `Combining Diacritical Marks` の仕様を見ていく形で問題なさそう。

- https://www.unicode.org/charts/PDF/U0300.pdf

**Comment by otegami** [comment]
> Make implementation plans

次にこちらを考えていく。

**Comment by otegami** [comment]
## 実装方針(仮)

- [ ] Add `remove_diacritical_mark` option to `NormalizerNFKC`
  - We won't implement the logic but just the option interfance.
- [ ] Implement the logic of `remove_diacritical_mark` with tests as follows.
  - [ ] Ordinary diacritics
  - [ ] Overstruck diacritics
  - [ ] Miscellaneous additions
  - [ ] Vietnamese tone marks
  - [ ] Additions for Greek
  - [ ] Additions for IPA
  - [ ] IPA diacritics for disordered speech
  - [ ] Grapheme joiner
  - [ ] Additions for the Uralic Phonetic Alphabet
  - [ ] Miscellaneous additions
  - [ ] Double diacritics
  - [ ] Medieval superscript letter diacritics

**Comment by kou** [comment]
そのユニコードの仕様って合成文字の仕様じゃないですか？
合成文字で表現するときもあると思いますけど、 ằ（U+1EB1 LATIN SMALL LETTER A WITH BREVE AND GRAVE）とか1文字で表現するときもある（というか、NFKCしたら合成文字で表現していても1文字になりそう）ので、そういう1文字で表現されている方も対応しないといけないんじゃないかと思います。

**Comment by otegami** [comment]
> 合成文字で表現するときもあると思いますけど、 ằ（U+1EB1 LATIN SMALL LETTER A WITH BREVE AND GRAVE）とか1文字で表現するときもある（というか、NFKCしたら合成文字で表現していても1文字になりそう）

なるほどです。合成済みの文字コードの仕様もちょっと探してみます！

**Comment by otegami** [comment]
合成済み(precomposed characters)の方の仕様が見つけられないので、少し相談する。

**Comment by kou** [comment]
あぁ、さーせん。combining characterは「合成文字」じゃなくて「結合文字」というべきでした。

**Comment by otegami** [comment]
下記の点がわかっていないので少し調べる。
どの段階の文字コードを対象にノーマライゼーションをかけるのかを確認したい。
- なぜなら、Unicode正規化(NFKC) が走ったあとなのであれば、結合文字を考慮せずに合成文字だけを考慮すればよいのではないかと考えたため
- 念の為、正規化時に合成文字に変換できない場合は、そのまま結合文字が返される場合があるのかも確認する

**Comment by otegami** [comment]
> どの段階の文字コードを対象にノーマライゼーションをかけるのかを確認したい。

`grn_nfkc_normalize` にて、合成後にノーマライゼーションをかけていそう。
- `https://github.com/groonga/groonga/blob/main/lib/normalizer.c#L2986`

> 念の為、正規化時に合成文字に変換できない場合は、そのまま結合文字が返される場合があるのかも確認する

合成文字が存在しない場合や結合文字だけが残っているような状況も対応できたほうがのぞましいとおもうので、
合成文字と結合文字の両方を対応するのが良さそう。

**Comment by otegami** [comment]
@kou さんにアドバイスいただいた方法で、発音区別符号を含んだ結合（合成）文字をすべて洗い出すと 960 文字存在した。
テストを追加するのにすべてを一度に対応すると大変そうなので分割していく必要がある。

```ruby
def have_diactritical_combining_character?(character)
  code_points = character.unicode_normalize(:nfd).codepoints
  code_points.any? do |code_point|
    (0x0300..0x036f).cover?(code_point)
  end
end
  
(0x0000..0xffff).each do |code_point|
  begin
    character = code_point.chr("UTF-8")
  rescue RangeError
    next
  end
  next unless have_diactritical_combining_character?(character)
  pp ["U+%04x" % code_point, character]
end
```

**Comment by kou** [comment]
`remove_diacritical_mark`じゃなくて`unify_kana_case`みたいに、`unify_alphabet_diacritical_mark`とかの方がいいかも。

**Comment by otegami** [comment]
なるほどです。ありがとうございます！
確かにユースケースとしては、アルファベットに発音区別符号を含んだ文字が多いと思うので、一旦その方針で対応してい行きたいと思います。

---

となると合成済み文字としては、ラテン文字がメインになってくると思うので、
下記のサイトを参考に「Latin」内のセクションごとに対応していくイメージでタスクを分割して見ようと思います。
- https://www.unicode.org/charts/

**Comment by otegami** [comment]
```ruby
def have_diactritical_combining_character?(character)
  code_points = character.unicode_normalize(:nfd).codepoints
  code_points.any? do |code_point|
    (0x0300..0x036f).cover?(code_point)
  end
end

def base_character_is_alphabet?(character)
  base_character = character.unicode_normalize(:nfd).chars.first
  base_code_point = base_character.codepoints.first
  (0x0041..0x005A).cover?(base_code_point) || (0x0061..0x007A).cover?(base_code_point)
end

total_count = 0
(0x0000..0xffff).each do |code_point|
  begin
    character = code_point.chr("UTF-8")
  rescue RangeError
    next
  end
  next unless have_diactritical_combining_character?(character) && base_character_is_alphabet?(character)
  pp ["U+%04x" % code_point, character]
  total_count += 1
end
pp total_count # 489
```

**Comment by otegami** [comment]
合成後に対応するようなやつがラテン文字の仕様を列挙する。
その仕様ごとに実装とテスト追加をしていきたい。

**Comment by otegami** [comment]
下記の合成済み文字コードを対応すれば、diacritical markが、ついたアルファベットは網羅できそう。 
- [Latin-1 Supplement](https://www.unicode.org/charts/PDF/U0080.pdf)
- [Latin Extended-A](https://www.unicode.org/charts/PDF/U0100.pdf)
- [Latin Extended-B](https://www.unicode.org/charts/PDF/U0180.pdf)
- [Latin Extended-C](https://www.unicode.org/charts/PDF/U2C60.pdf)
- [Latin Extended Additional](https://www.unicode.org/charts/PDF/U1E00.pdf)

**Comment by otegami** [comment]
I've just updated the plan as follows.

##  Implementation plans

- [ ] Add `unify_alphabet_diacritical_mark` option to `NormalizerNFKC`
  - We won't implement the logic but just the option interfance.
- [ ] Implement the logic of `unify_alphabet_diacritical_mark` with tests and documents as follows.
  - [ ] [Latin-1 Supplement](https://www.unicode.org/charts/PDF/U0080.pdf)
  - [ ] [Latin Extended-A](https://www.unicode.org/charts/PDF/U0100.pdf)
  - [ ] [Latin Extended-B](https://www.unicode.org/charts/PDF/U0180.pdf)
  - [ ] [Latin Extended-C](https://www.unicode.org/charts/PDF/U2C60.pdf)
  - [ ] [Latin Extended Additional](https://www.unicode.org/charts/PDF/U1E00.pdf)

**Comment by otegami** [comment]
> Add unify_alphabet_diacritical_mark option to NormalizerNFKC
> - We won't implement the logic but just the option interfance.

I will start implementing this one now.

**Comment by otegami** [comment]
下記に `unify_alphabet_diacrtical_mark` option を指定して問題ないことを確認するテストを追加する。
- https://github.com/groonga/groonga/pull/1831

**Comment by otegami** [comment]
```console
$ /tmp/local/bin/groonga --version
Groonga 14.0.6-7-g03e3053 [Linux,x86_64,utf8,match-escalation-threshold=0,nfkc,mecab,message-pack,onigmo,zlib,lz4,zstandard,epoll,rapidjson,xxhash]
$ grntest ./test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark.test --groonga=/tmp/local/bin/groonga
```

## 実際の結果

あくまでオプションを指定できるようにするだけで値を変えることを意図していないので確認する。

```
normalize   'NormalizerNFKC("unify_alphabet_diacritical_mark", true)'   "À"   WITH_TYPES
[
  [
    0,
    0.0,
    0.0
  ],
  {
    "normalized": "\u0001\u0000",
    "types": [
      "alpha",
      "null"
    ],
    "checks": [

    ]
  }
]
```

## 期待する結果

```
normalize   'NormalizerNFKC()'   "À"   WITH_TYPES
[
  [
    0,
    0.0,
    0.0
  ],
  {
    "normalized":"à",
    "types":[
      "alpha",
      "null"
    ],
    "checks": [

    ]
  }
]
```

**Comment by otegami** [comment]
レビュー対応をしていく。

**Comment by otegami** [comment]
> Implement the logic of unify_alphabet_diacritical_mark with tests and documents for the following precomposed characters.

下記の対応をしていく！
- [ ] [Latin-1 Supplement](https://www.unicode.org/charts/PDF/U0080.pdf)

**Comment by otegami** [comment]
試しに à だけを a に変換するコードを書いてみた。

分かったこと
- アルファベットの大文字は、小文字にノーマライズされていること
- Dacritical Mark がついた文字と外して場合の文字の対応表が必要そうなこと
  - ^ NFKC の分解して判断する方法もあるが冗長な気がする 
```
  // à だけを a に変換してみる
  if (utf8_char[0] == 0xC3 && utf8_char[1] == 0xA0) {
    *unified = 'a';
    return unified;
  }
```

**Comment by otegami** [comment]
> Dacritical Mark がついた文字と外して場合の文字の対応表が必要そうなこと

下記のようなマッピングをしたテーブルを作って、読んであげると行けるかな？
```ruby
latin_1_supplement_table = {
  '0xA0' => 'a',
  0xA1: => 'a'
}
```

既存の仕組みを使って良い感じに対応できないかを少し確認する。

**Comment by otegami** [comment]
マッピングしたテーブルを使って対応してみたが、
もう少し良さそうなやり方がある気がするので相談する。
```diff
git show
commit e35fe125324ac3c61aecea5b9238f747e255dc2c (HEAD -> support-latin-1-supplement-for-unify-alpabet-diacritical-marks, origin/support-latin-1-supplement-for-unify-alpabet-diacritical-marks)
Author: otegami <otegami@clear-code.com>
Date:   Thu Aug 1 18:20:03 2024 +0900

    wip normalize Latin-1 Supplements to basic alphabets

diff --git a/lib/normalizer.c b/lib/normalizer.c
index e5d227a6b..057718203 100644
--- a/lib/normalizer.c
+++ b/lib/normalizer.c
@@ -849,12 +849,25 @@ grn_inline static const unsigned char *
 grn_nfkc_normalize_unify_alphabet_diacritical_mark(
   const unsigned char *utf8_char, unsigned char *unified)
 {
-  // TODO: Implement function to return `unified` instead of `utf8_char`.
-  // à だけを a に変換してみる
-  if (utf8_char[0] == 0xC3 && utf8_char[1] == 0xA0) {
-    *unified = 'a';
-    return unified;
+  static const char removed_latin1_supplement_diacritical_mark_table[] = {
+    'a', 'a', 'a', 'a', 'a', 'a', 'a', 'c',
+    'e', 'e', 'e', 'e', 'i', 'i', 'i', 'i',
+    'd', 'n', 'o', 'o', 'o', 'o', 'o', 0,
+    'o', 'u', 'u', 'u', 'u', 'y', 'p', 'y'
+  };
+
+  if (utf8_char[0] == 0xC3) {
+    if (utf8_char[1] >= 0xA0 && utf8_char[1] <= 0xBF) {
+      unsigned char code_point = utf8_char[1] - 0xA0;
+      unsigned char removed_diacritical_mark_alphabet =
+        removed_latin1_supplement_diacritical_mark_table[code_point];
+      if (removed_diacritical_mark_alphabet != 0) {
+        *unified = removed_diacritical_mark_alphabet;
+        return unified;
+      }
+    }
   }
+
   return utf8_char;
 }
```

**Comment by otegami** [comment]
方針について相談したのでメモ

結論: 変換後のアルファベットは、アルファベット順に並んでいるので、下記のように`if`で範囲指定しながら変換していく
- https://github.com/groonga/groonga/blob/89e46ff9437c0ca98e417f1c87372224321b0081/lib/normalizer.c#L860-L880

理由: 変換用の対応マッピングテーブルはすべて対応すると 500 以上の要素を持つことになるので、バイナリーサイズが大きくなりかつ遅くなりそうなため

**Comment by otegami** [comment]
レビュー対応をしていきます!

**Comment by otegami** [comment]
タスクの分割の仕方が実装の都合上変更になったため、
改めて対応する必要があるタスクを洗い出します。

**Comment by otegami** [comment]
対応する必要があるアルファベットは下記で洗い出すと、`q` 以外すべての文字になりそうなことがわかった。

```ruby
#!/usr/bin/env ruby

def have_diactritical_combining_character?(character)
  code_points = character.unicode_normalize(:nfd).codepoints
  code_points.any? do |code_point|
    (0x0300..0x036f).cover?(code_point)
  end
end

def base_character(character)
  character.unicode_normalize(:nfd).chars.first
end

def base_character_is_lower_alphabet?(character)
  base_code_point = base_character(character).codepoints.first
  (("a".codepoints.first)..("z".codepoints.first)).cover?(base_code_point)
end

alphabets = ('a'..'z').to_a
(0x0000..0xffff).each do |code_point|
  begin
    character = code_point.chr("UTF-8")
  rescue RangeError
    next
  end
  next unless have_diactritical_combining_character?(character)
  next unless base_character_is_lower_alphabet?(character)
  alphabets.delete(base_character(character))
end
pp alphabets
```
```console
$ ruby generate-unicode.rb
["q"]
```

**Comment by otegami** [comment]
タスクリストを更新しました。
- https://github.com/groonga/groonga/issues/1755#issuecomment-2244330981

**Comment by abetomo** [comment]
複数文字で表現しているパターンもある。
https://github.com/groonga/groonga/pull/1908#discussion_r1732166478

**Comment by kou** [comment]
"U+00C0  LATIN CAPITAL LETTER A WITH GRAVE"など（"U+0041 LATIN CAPITAL LETTER A" + "U+0300 COMBINING GRAVE ACCENT"とかじゃなくて）1文字で表現されている文字だけに対応しているのとa-zにしか対応していないので今の`unify_alphabet_diacritical_mark`だとがんばれていない。

もっと限定された名前にしよう。対象の文字は"LATIN (SMALL|CAPITAL) LETTER [A-Z] WITH XXX"という名前がついているから`unify_latin_alphabet_with`とかはどうかな。

**Comment by askdkc** [comment]
Unicodeのalphabetの定義によると、日本の常識に反して、日本語の平仮名とかも含んでしまうらしく、ここはasciiにしておいた方が良いのかも？という知見を大昔に得ました

https://github.com/laravel/framework/discussions/45660

**Comment by kou** [comment]
"latin"をつけるとa-zだけになることを期待しています！
Unicodeでは"ascii"じゃなくて"latin"を使っていますよね。

**Comment by otegami** [comment]
`simplify_latin_with_diacritical_mark` や `strip_latin_with_diacritical_mark` みたいな名前はどうでしょう。
`unify_xx` だと、ダイアクリティカルマークがついたラテン文字に統一する逆のニュアンスがあるかなぁと思ったためです。

---

上記のように考えていたのですが、既存オプションである `unify_kana_voiced_sound_mark` なども同じようにサウンドマークを外す動きをしているので、そんなに誤解をうまなさそうなので、`unify_latin_alphabet_with`良さそうに思いました。
- 新しい動詞のオプションを入れると混乱しそうな側面もあるため

**Comment by kou** [comment]
どの文字に正規化されるか考える時点で負けです！

大文字に正規化されようと小文字に正規化されようとマークがついた方に寄せようと寄せまいとそこを考えてはダメなんです。

どう正規化されるかは実装の詳細で、外からみたら同じ文字として扱われる、レベルで考えないといけないです。

**Comment by otegami** [comment]
なるほどです！既存の命名も合わせてしっくりきました。
`unify_latin_alphabet_with`良さそうに思いました！

**Comment by askdkc** [comment]
> "latin"をつけるとa-zだけになることを期待しています！ Unicodeでは"ascii"じゃなくて"latin"を使っていますよね。

`unify_latin_alphabet_with` なるほど！確かに！
