### ISSUE TITLE
Relicensing to LGPL-2.1-or-later from LGPL-2.1-only

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1774]
### What is your problem?

Groonga is licensed under [LGPL-2.1-only](https://spdx.org/licenses/LGPL-2.1-only.html).

I want to relicense Groonga to [LGPL-2.1-or-later](https://spdx.org/licenses/LGPL-2.1-or-later.html) from LGPL-2.1-only to improve [Apache-2.0](https://spdx.org/licenses/Apache-2.0.html) compatibility.

Incompatibility between [GPL-2.0](https://spdx.org/licenses/GPL-2.0-only.html) and Apache-2.0 is well known because both of FSF and ASF explain it:
* https://www.gnu.org/licenses/license-list.html.en#apache2
* https://www.apache.org/licenses/GPL-compatibility.html

Compatibility between LGPL-2.1 and Apache-2.0 isn't explained there but they may be incompatible too because LGPL-2.1 is based on GPL-2.0.

If LGPL-2.1 and Apache-2.0 are incompatible, LGPL-2.1-only licensed Groonga can't link with Apache-2.0 libraries such as Apache Arrow. LGPL-2.1-only licensed software can be also used as GPL-2.0-or-later licensed software because LGPL-2.1 has the following sentence:

> 3. You may opt to apply the terms of the ordinary GNU General Public License instead of this License to a given copy of the Library. To do this, you must alter all the notices that refer to this License, so that they refer to the ordinary GNU General Public License, version 2, instead of to this License. (If a newer version than version 2 of the ordinary GNU General Public License has appeared, then you can specify that version instead if you wish.) Do not make any other change in these notices.

So we can link with Apache-2.0 libraries by using Groonga as GPL-3.0-or-later licensed software. But this has a problem. If we use Groonga as GPL-3.0-or-later licensed software, we can't use Groonga with GPL-2.0-only licensed software such as MySQL.

If Groonga uses LGPL-2.1-or-later not LGPL-2.1-only, Groonga can link with Apache-2.0 libraries by using LGPL-3.0-or-later (LGPL-2.1-or-later includes it).

We need to ask all patch authors of Groonga to relicense Groonga to LGPL-2.1-or-later from LGPL-2.1-only.

Here are patch authors of Groonga:

```console
$ git shortlog -sn
 11409	Kouhei Sutou
  3485	Sutou Kouhei
  1818	HAYASHI Kentaro
  1078	Daijiro MORI
   647	Kentaro Hayashi
   619	Susumu Yata
   449	Tasuku SUENAGA a.k.a. gunyarakun
   408	Horimoto Yasuhiro
   371	susumu.yata
   304	Yasuhiro Horimoto
   267	mori
   262	Ryo Onodera
   254	Masafumi Yokoyama
   162	naoa
   120	t2001
   110	Takashi Hashida
    94	Naoya Murakami
    93	cosmo0920
    86	Abe Tomoaki
    66	Nobuyoshi Nakada
    55	YUKI Hiroshi
    49	Haruka Yoshihara
    40	HorimotoYasuhiro
    39	Yoji SHIDARA
    36	Hiroshi Hatake
    35	Yuto Hayamizu
    34	whombx
    30	yoshihara haruka
    26	Toshihisa
    22	takuya kodama
    19	khayashi
    18	Yutaro Shimamura
    18	wanabe
    12	Hiroyuki Sato
    12	IWAI, Masaharu
    10	dependabot[bot]
     6	Kenji Okimoto
     6	jacob16bit
     5	orangain
     4	Hiroshi Ohkubo
     4	Motoi Washida
     3	Daiki Ueno
     3	OBATA Akio
     3	Tetsuro IKEDA
     3	do-aki
     3	mori daijiro
     3	tamano
     3	yagisumi
     2	Jun Kuriyama
     2	Noritada Kobayashi
     2	Tetsuharu OHZEKI
     2	YUKI "Piro" Hiroshi
     2	brazil
     2	kou
     2	tashiro
     2	unknown
     2	wi24rd
     1	Akinori MUSHA
     1	Anthony M. Cook
     1	Ayumu
     1	Dylan Golow
     1	Genki Takiuchi
     1	HashidaTKS
     1	Jasper Siepkes
     1	NOKUBI Takatsugu
     1	Natanael Copa
     1	SATOH Fumiyasu
     1	SHIDARA Yoji
     1	SHIMODA Hiroshi
     1	Sebastian Wiedenroth
     1	Shimomura Tatsuya
     1	Sho Minagawa
     1	Tasuku SUENAGA
     1	Tim Gates
     1	Yosuke Sekikawa
     1	Yosuke Shiro
     1	Yu.Shimamura
     1	Yuya TAMANO
     1	cafedomancer
     1	mooz
     1	ryo-pinus
     1	tSU-RooT
     1	tSU_RooT
     1	vagrant
     1	yu
     1	yutaro
     1	zunda
```

Here are distinct authors (except trivial patch authors):

* [x] @kou
* [x] @kenhys
* [x] @daijiro
* [x] @s-yata
* [x] @gunyarakun
* [x] @komainu8
* [x] @ryoqun
* [x] @myokoym
* [x] @naoa
* [x] @t2001
* [x] @HashidaTKS
* [x] @cosmo0920
* [x] @abetomo
* [x] @nobu
* [x] @piroor
* [x] @yoshihara
* [x] @darashi
* [x] @hayamiz
* [x] @yu
* [x] @otegami
* [x] @wanabe
* [x] @hiroyuki-sato
* [x] @iwaim
* [x] @orangain
* [x] @wm3
* [x] @ueno
* [x] @obache
* [x] @ikdttr
* [x] @do-aki
* [x] @tamano
* [x] @kuriyama 
* [x] @noritada 
* [x] @tetsuharuohzeki 
* [x] @wi24rd
* [x] @knu 
* [x] @genki
* [x] @siepkes
* [x] @knok 
* [x] @wiedi
* [x] @ryo-pinus

If you agree to this license change, could you add the following comment to this issue?

> I agree to apply LGPL-2.1-or-later to my commits.

If you have any questions or object this license change, please let us know.

Trivial patch authors:

* Kenji Okimoto: Typo fixes
  * a0e3de50e45916daa3d2313a1a4e6128f4fc20fb
  * 666f22af0a6d187fab67559f587f091fa7431e8f
  * fcccbde106bb3b58cb8b4215b94e98aefdb6480f
  * 1a81014950b422a207fba06211e41008facd9a7b
  * adcda8b944193cbbd7e0558fa7cb4b207c0cdfb9
  * db42c1007b43698721da91e668b5bf543bdfabd2
* jacob16bit: groonga-httpd was extracted to https://github.com/groonga/groonga-nginx and it doesn't have RPM package
  * https://github.com/groonga/groonga/pull/357
  * https://github.com/groonga/groonga/pull/351
* Ayumu: Remove unused code
  * b518d63baab084dab9dac15c7cc5363f8a4fd337
* Dylan Golow: Typo fix
  * b827b5ef0810ca31f50136e33619109c0e094fcb
* SATOH Fumiyasu: Remove redundant configurations
  * ebdd2f6d1651a7b0ffa5b13a03dbe69142e76f6c
* Tim Gates: Typo fix
  * 26623b13f01dbcc1ea763cd4a20eb5671d6c52d5
* cafedomancer: Typo fix
  * 3b0daad671d30beee0486c1b077a2d6ffa878856
* mooz: Typo fix
  * 8f248d91235d597332f4fdf044dac615ea1e2088
* tSU-RooT: Typo fixes
  * b73eeb36a07b0d166f17612433bcbb3118766d37
  * aaeff8e92bb2a1263b69b17ded5f5012998eb6f9
* zunda: Typo fix
  * 39b3788a2a638d0c571b57843d2114c919af0323
* @yagisumi 
  * GH-1000
  * GH-1023
  * GH-1024
* @ncopa 
  * cc4f6b865c6db1f79d6a300efc4af100386bf2e6 
* @ohkubo
  * e52ced01210a038ed03d7878bb9874f911535682 This is not a trivial but replaced with 7371926c25b8864c80362cd62929c830ed73c218
  * 55c138060faf1a042d5d99d97fcb4fae53a98223
  * 449ca69b2e3ead16e267da2c3164269170214f97
  * 0d19f44061d8f025e66c4571dfe4307240070fc8
* @msh5
  * ada5ef5578d4443416efa7ce189c00f67ab03f63
* @shiro615 
  * GH-909

Patch authors who can't be contacted on GitHub:
* [x] @t-shm
  * #47

Patch authors whose commits are replaced by other commits:

* @OffGao
  * 13de2b0b2817b7c9e6d5da087601dbe2dbe9c76f
  * Replaced with GH-1821
* @whombx
  * We replaced all commits by migrating to Doxygen

<details>

<summary>PRs by @whombx (all of them are moving document location)</summary>

  * #100
  * #99
  * #98
  * #97
  * #96
  * #95
  * #93
  * #92
  * #91
  * #90
  * #89
  * #88
  * #87
  * #86
  * #85
  * #84
  * #83
  * #82
  * #81
  * #80
  * #79
  * #78
  * #75
  * #74
  * #73
  * #72
  * #71
  * #70
  * #69
  * #68
  * #67
  * #66
  * #65
  * #64

</details>

**Comment by kou** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by kuriyama** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by kenhys** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by knu** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by tetsuharuohzeki** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by hiroyuki-sato** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

```
- [x] @hiroyuki-sato
```

**Comment by abetomo** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by komainu8** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by cosmo0920** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by otegami** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by siepkes** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by darashi** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by noritada** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by wi24rd** [comment]
I agree to apply LGPL-2.1-or-later to my commits.
Computer Engineer
https://zhw.pages.dev/ <https://github.com/wi24rd>

**Comment by wiedi** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by kou** [comment]
I asked t-shm about this by e-mail and t-shm accepted this change.

**Comment by naoa** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by ueno** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by wanabe** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by orangain** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by ryo-pinus** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by myokoym** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by knok** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by piroor** [comment]
I agree to change the license about my contributions.

**Comment by HashidaTKS** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by ikdttr** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by gunyarakun** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by tamano** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

Thanks,

**Comment by ryoqun** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by do-aki** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by genki** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by nobu** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by hayamiz** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by daijiro** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by iwaim** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by t2001** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by s-yata** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by wm3** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by abetomo** [comment]
Listed commits for authors who have no comments at this time.

* @ohkubo
  * https://github.com/groonga/groonga/commits?author=ohkubo
  * commits
    * https://github.com/groonga/groonga/commit/e52ced01210a038ed03d7878bb9874f911535682
    * https://github.com/groonga/groonga/commit/55c138060faf1a042d5d99d97fcb4fae53a98223
    * (T) https://github.com/groonga/groonga/commit/449ca69b2e3ead16e267da2c3164269170214f97
    * (T) https://github.com/groonga/groonga/commit/0d19f44061d8f025e66c4571dfe4307240070fc8
* @yagisumi
  * https://github.com/groonga/groonga/commits?author=yagisumi
  * commits
     * (T) https://github.com/groonga/groonga/pull/1000
     * (T) https://github.com/groonga/groonga/pull/1023
     * (T) https://github.com/groonga/groonga/pull/1024
* @ncopa
  * https://github.com/groonga/groonga/commits?author=ncopa
  * commits
    * (T) https://github.com/groonga/groonga/commit/cc4f6b865c6db1f79d6a300efc4af100386bf2e6
* @msh5
  * https://github.com/groonga/groonga/commits?author=msh5 (Commit is not listed.)
  * It's not listed, but here's the commit: https://github.com/groonga/groonga/commit/ada5ef5578d4443416efa7ce189c00f67ab03f63
* @OffGao
  * https://github.com/groonga/groonga/commits?author=OffGao
  * commits
    * https://github.com/groonga/groonga/commit/13de2b0b2817b7c9e6d5da087601dbe2dbe9c76f
* @shiro615
  * https://github.com/groonga/groonga/commits?author=shiro615
  * commits
    * https://github.com/groonga/groonga/pull/909

I have assigned `(T)` to what I judged to be a trivial patch.
We appreciate any comments you may have.

**Comment by kou** [comment]
>     * @ohkubo
>       
>       * https://github.com/groonga/groonga/commits?author=ohkubo
>       * commits
>         
>         * [55c1380](https://github.com/groonga/groonga/commit/55c138060faf1a042d5d99d97fcb4fae53a98223)

We can mark this as a trivial path too because it just remove unused codes.

**Comment by abetomo** [comment]
> * @OffGao
>   * https://github.com/groonga/groonga/commits?author=OffGao
>   * commits
>     * https://github.com/groonga/groonga/commit/13de2b0b2817b7c9e6d5da087601dbe2dbe9c76f

Replaced with jQuery UI Progressbar Widget.
#1821

**Comment by abetomo** [comment]
Since the following two commits are not creative, we consider them not copyrightable.

> * @msh5
>   * https://github.com/groonga/groonga/commits?author=msh5 (Commit is not listed.)
>   * It's not listed, but here's the commit: https://github.com/groonga/groonga/commit/ada5ef5578d4443416efa7ce189c00f67ab03f63

> * @shiro615
>   * https://github.com/groonga/groonga/commits?author=shiro615
>   * commits
>     * https://github.com/groonga/groonga/pull/909

If there are any objections, please comment on this isssue within one month.

**Comment by abetomo** [comment]
For the next commit on https://github.com/groonga/groonga/issues/1774#issuecomment-2237939946 list:

> * @ohkubo
>   * https://github.com/groonga/groonga/commits?author=ohkubo
>   * commits
>     * https://github.com/groonga/groonga/commit/e52ced01210a038ed03d7878bb9874f911535682

This has been replaced by a change in https://github.com/groonga/groonga/commit/7371926c25b8864c80362cd62929c830ed73c218.

**Comment by abetomo** [comment]
@whombx commits in the description of this issue has been replaced by commits to move a C API reference to a header file.

Related task: #1817
Example of a commit moved a C API reference to a header file: #2150

**Comment by abetomo** [comment]
The list of patch authors who have agreed to relicensing is in this issue.
We have checked all patches by authors whose agreement could not be verified. What we have checked is that it has already been replaced, or is a trivial patch, etc.

The relicensing is ready.

**Comment by kou** [comment]
Finally!
Let's do it!
