### ISSUE TITLE
Build of Groonga of main buranch fail on Windows

### ISSUE THREAD

**Issue by komainu8** [groonga/groonga#1810]
### What happend?

Build of Groonga(main branch) for Windows fail by the following error.

https://github.com/groonga/groonga/actions/runs/9770073101/job/26970678787#step:13:2835

### How to reproduce it

We build Groonga of main branch by using MSVC compiler.

### Expected behavior

The build of Groonga of main branch success by using MSVC compiler.

### Environment

- OS: Windows Server
- OS Version: 2022, 2019
- Groonga version: main

**Comment by kou** [comment]
CIのログは時間が経つと消えるので、リンクだけだと後でなにがあったのかわからなくなります。
注目するべき箇所はコピペしておいたほうがいいです。

**Comment by komainu8** [comment]
なるほど。承知です。
