### ISSUE TITLE
Upload wrong link to packages for Windows

### ISSUE THREAD

**Issue by komainu8** [groonga/groonga#1839]
### What is your problem?

Groonga v14.0.6 のWindows版パッケージへのリンクがNot Foundになっていた。

### How to reproduce it

```
$ rake dev:version:bump NEW_VERSION=x.x.x
$ cd packages
$ rake windows
```

最新のタグを参照するようにすれば良さそう。

**Comment by kou** [comment]
Fixed by #1841.
