### ISSUE TITLE
Remove deprecated CentOS content to avoid misleading users

### ISSUE THREAD

**Issue by otegami** [groonga/groonga#1840]
### What is your problem?

There are some content about CentOS although CentOS reached EOL and we droped support for CentOS.
This situation will mislead users that they can use Groonga in the CentOS.
So we want to remove the contents which are related to CentOS.
- ref: [CentOS EOL](https://www.centos.org/centos-linux-eol/)
- ref: [Drop support for CentOS 7](https://github.com/groonga/groonga/pull/1809)
- ref: [Drop support for CentOS 8](https://github.com/groonga/groonga/pull/1302)

**Comment by kou** [comment]
This is a document only problem, right?
