### ISSUE TITLE
[Document] `sed: /usr/local/etc/mecabrc: No such file or directory`

### ISSUE THREAD

**Issue by Watson1978** [groonga/groonga#1846]
### What happend?

I met the error message `sed: /usr/local/etc/mecabrc: No such file or directory` when I tried to run the code below referred by https://groonga.org/docs/install/mac_os_x.html#homebrew.

```sh
% sed -i '' -e 's,dicrc.*=.*,dicrc = /usr/local/lib/mecab/dic/ipadic,g' /usr/local/etc/mecabrc
```

<img width="1102" alt="スクリーンショット 2024-07-31 14 10 37" src="https://github.com/user-attachments/assets/b22aa236-39ee-4e43-bfb4-5ef9b408e32c">

Recent Homebrew installs packages into `/opt/homebrew/`, so the file can't be found in `/usr/local/etc`.

### How to reproduce it

Invoke the command under Homebrew

```sh
% sed -i '' -e 's,dicrc.*=.*,dicrc = /usr/local/lib/mecab/dic/ipadic,g' /usr/local/etc/mecabrc
```

### Expected behavior

Fix documents.

### Environment

- OS: macOS

**Comment by abetomo** [comment]
On my macOS, I have `/usr/local/etc/mecabrc`.
Maybe it's because of the different OS or Homebrew versions.

```
$ file /usr/local/etc/mecabrc
/usr/local/etc/mecabrc: ASCII text
```

```
$ sw_vers
ProductName:        macOS
ProductVersion:     14.5
BuildVersion:       23F79
$ brew --version
Homebrew 4.3.12
```

**Comment by Watson1978** [comment]
```
[~]$ file /opt/homebrew/etc/mecabrc
/opt/homebrew/etc/mecabrc: ASCII text

[~]$ sw_vers
ProductName:		macOS
ProductVersion:		15.1
BuildVersion:		24B5009l

[~]$ brew --version
Homebrew 4.3.12-74-g6cfa083
```

What type does your mac use for CPU?
I use Apple Silicon (Apple M1 Max).
I remember that since Apple Silicon, security has become stricter and /opt/homebrew is used for new Homebrew installations.

**Comment by abetomo** [comment]
I see...the difference is the CPU.
My Mac is Intel.
