### ISSUE TITLE
Drop support for i386 architecture

### ISSUE THREAD

**Issue by otegami** [groonga/groonga#1889]
### What is your problem?

Since I think we are no longer providing packages for the i386 architecture, it may be beneficial to remove its support. This would help simplify the code and improve maintainability. What are your thoughts on dropping support for i386?

**Comment by kou** [comment]
@kenhys Debian still supports i386, right?

**Comment by otegami** [comment]
I couldn't check it. Debian supports i386 from the following.
- https://packages.debian.org/search?arch=i386&keywords=groonga

**Comment by otegami** [comment]
@kenhys 
I would like to confirm just one thing. Is the test.sh script, linked below, being used in Debian package support?
- https://github.com/groonga/groonga/blob/main/packages/apt/test.sh

If it is not being used, we are currently not checking i386 packages in Groonga. Therefore, I am considering removing the i386 specific condition in this file.

**Comment by kou** [comment]
The test script must not be used in the official Debian package.

**Comment by kenhys** [comment]
* In Debian, still i386 arch is supported.
  * But this is a just fact that it does not cause FTBFS at the moment. If it causes FTBFS more frequently and becomes hard to fix, I will drop it at once.
* https://github.com/groonga/groonga/blob/main/packages/apt/test.sh is not used in Debian package, so feel free to remove i386 condition.

**Comment by otegami** [comment]
Thank you so much.
I think we should revisit dropping support if the situation where it causes FTBFS more frequently and becomes hard to fix actually occurs on Debian. For now, I propose we will close this issue. If anyone has a different opinion or a suggestion on a better approach, please let me know.

Anyway, I will deal with the following test script.
- https://github.com/groonga/groonga/blob/main/packages/apt/test.sh
