### ISSUE TITLE
ci package: reduce execution time about especially arm64

### ISSUE THREAD

**Issue by otegami** [groonga/groonga#1895]
### What is your problem?

ref: https://github.com/groonga/groonga/pull/1886#issuecomment-2306093875

We've noticed a significant discrepancy in the build times between two of our CI jobs.
- Build (Debian GNU/Linux trixie arm64) takes 4 hours, 28 minutes, and 36 seconds
- Build (Debian GNU/Linux bookworm arm64) only takes 1 hour, 18 minutes, and 27 seconds

ref: https://github.com/groonga/groonga/actions/runs/10485982065/usage?pr=1886

This large difference raises concerns about potential inefficiencies in our build process for the trixie arm64 environment.
This https://github.com/groonga/groonga/pull/1886#issuecomment-2306093875 's analysis show it cause the longer build times to execute stages that do not require `.deb` linting or are just preparing for `grntest`. Optimizing these steps could significantly reduce the overall build time.

**Comment by kou** [comment]
Done.

* Enable parallel build
* Disable `lintian`
