### ISSUE TITLE
Regression: libgroonga 14.1.0 crashes on CPU without AVX2

### ISSUE THREAD

**Issue by khalilsadiq786** [groonga/groonga#2078]
### What happend?

See prior issue: https://github.com/pgroonga/pgroonga/issues/578

This is an issue I am experiencing in PGroonga, but after some troubleshooting it appears the issue is actually with libgroonga and not actually PGroonga.

With packages installed from the Groonga PPA, with libgroonga 14.0.9 everything works correctly even on very old systems without AVX of any kind, but as of libgroonga 14.1.0, libgroonga crashes with an "Illegal instruction" error if the CPU does not support AVX2.

I do not see this documented anywhere, so believe it must be unintentional. It was suggested on the prior PGroonga issue that it may be related to support for simdjson or llama.cpp.

Working on 14.0.9, not working on 14.1.0:
- Server from OVH with Intel Atom (no AVX)
- Server from OVH with Sandy Bridge Intel i3 (has AVX, does not have AVX2)

Working on 14.1.0:
- Broadwell Intel Xeon server (has AVX2)

### How to reproduce it

Attempt to use Groonga on CPU without AVX2.

### Expected behavior

Groonga should work on these CPUs as it used to.

### Environment

- OS: Ubuntu Server
- OS Version: 22.04 LTS
- Groonga version: 14.1.0

**Comment by kou** [comment]
Could you try a .deb attached in https://github.com/groonga/groonga/releases/tag/v14.1.0 too?
.deb built on PPA and built on GitHub Actions have some differences.
I want to confirm that these differences are unrelated to this problem.

**Comment by khalilsadiq786** [comment]
With .deb from https://github.com/groonga/groonga/releases/tag/v14.0.9 it works correctly
WIth .deb from https://github.com/groonga/groonga/releases/tag/v14.1.0 it does not work

**Comment by khalilsadiq786** [comment]
Further testing.

The artifact from here works: https://github.com/groonga/groonga/actions/runs/11176026674
This does not: https://github.com/groonga/groonga/actions/runs/11179269562

All action runs between those appear to have failed to build.

Here are the commits between those:

https://github.com/groonga/groonga/compare/2a987e7..c157fc7

I see it looks like llama.cpp is being initialized in ctx.cpp, and I would expect llama.cpp uses AVX to get acceptable performance on CPU so that is a probably culprit. It is unclear why this would be causing this problem because from a quick check of the llama.cpp repo it looks to do some sort of runtime checks for CPU features though.

**Comment by kou** [comment]
Thanks.
I'll investing this too.

**Comment by khalilsadiq786** [comment]
Actually I think I misread llama.cpp code (I am not very good at C/C++) -- it has `-march=native` in Makefile so I think this is probably that machine doing the building has AVX2 and that is why this is occurring.

**Comment by kou** [comment]
I made llama.cpp initialization lazy.
llama.cpp support still requires AVX2 (for performance) but users who don't use llama.cpp related features don't need AVX2.
