### ISSUE TITLE
Systemd migration on CentOS 7

### ISSUE THREAD

**Issue by kenhys** [groonga/groonga#252]
4.0.8でやろうと思ったが、次回リリース移行に見送り。

**Comment by myokoym** [comment]
できれば2015年5月末のリリース（5.0.4）で対応したいが、リリースに間に合わなそうなら次回にする。
手順は以下。

* [ ] 1. rpmパッケージにSystemdの設定ファイル（.serviceファイル）を追加
  * [ ] packages/rpm/centos/groonga.spec.inを修正して、CentOSのバージョンが7なら.serviceファイルを使うようにする
  * [ ] data/にCentOS 7用の.serviceファイルを追加（？）
* [ ] 2. /etc/init.d/のファイルを削除する処理を追加
  * 削除しなくても問題なさそう（/lib/systemd/が優先されるだけ）なので、次回リリースに回すのもあり
  * どこに削除する処理を追加すればいいのか要確認
* [ ] 3. 動作確認
  * [ ] CentOS 5（リグレッション）
  * [ ] CentOS 6（リグレッション）
  * [ ] CentOS 7

**Comment by kenhys** [comment]
* `--with-package-platform=fedora`を使うとservice関係のファイルもインストールされるはず。
* /etc/init.d/については%filesで分岐してinitddirとunitdirとで含めるものをわける。
* あとはpostun等のスクリプトをsystemctlに置き換える

**Comment by kenhys** [comment]
5.0.5で対応しましょう！

**Comment by myokoym** [comment]
はい！

**Comment by myokoym** [comment]
もっと具体的な進め方:

* [ ] 1. configureオプション名修正
  * 今はRedhat/Fedoraで分かれているが、時代にそぐわないのでInit/Systemdにする
  * configure.ac
    * AC_ARG_WITH
  * packages/rpm/centos/groonga.spec.in
  * doc/source/install/others.rst
* [ ] 2. 変数名修正
  * 1と同様に修正する
  * configure.ac
  * data/init.d/redhat/Makefile.am
  * data/init.d/redhat/sysconfig/Makefile.am
  * data/loglotate.d/redhat/Makefile.am
  * data/systemd/fedora/Makefile.am
  * data/systemd/fedora/sysconfig/Makefile.am
* [ ] 3. `%postun`などを5/6と7で切り替え
  * /sbin/serviceなど
  * packages/rpm/centos/groonga.spec.in
* [ ] 4. `%files`内で5/6と7で切り替え
  * packages/rpm/centos/groonga.spec.in

**Comment by myokoym** [comment]
[systemd-migration-on-centos-7](https://github.com/groonga/groonga/tree/systemd-migration-on-centos-7) ブランチで作業中です。

**Comment by myokoym** [comment]
`--with-package-platform`はdeprecatedにして残しておく方針にします。

**Comment by myokoym** [comment]
同じinit.dでも、Red Hat系とDebian系では書き方が異なることがわかった。現在のオプションでインストールされるのはRed Hat系のinit.d向けのファイルなので、単に`--with-package-platform=redhat`を`--with-system-files=init`に変えてしまうと以下の問題が起きる。

* Debian系の環境でも使えるように感じるが、実際にインストールされるのはRed Hat系のinit.d向けのファイルなので、期待通りには動かない

よって、オプション名は変えずに値を`redhat6`/`redhat7`のように分けるのがいいかもしれない。

**Comment by myokoym** [comment]
このコミット https://github.com/groonga/groonga/commit/74e2c4883d2c825840d9b0187074ae29fa35f3e0 の方針で、来月中旬頃から対応を進める予定です。

* `--with-package-platform`オプションに以下の値を追加
  * redhat5
  * redhat6
  * redhat7
* 既存の値（redhatとfedora）の挙動は変えない
* redhat5とredhat6は、既存のredhatと同じ扱い
* redhat7はfedoraと同じようにSystemdに対応させる

**Comment by kou** [comment]
これはどんな状態なんだろう。

**Comment by kou** [comment]
systemd-migration-on-centos-7ブランチを伸ばせばいいのかしら。
でも、だいぶ前のみたいだから触りたくないなぁ。

**Comment by kou** [comment]
Fedoraと同じようにって`data/systemd/fedora/`以下の`.service`を使うってことかしら。
こいつら、`packages/debian/`以下のファイルと微妙に違うんだけどまだ有効なやつなのかしら。

**Comment by kou** [comment]
1から調べないとわからないパターンかなぁ。

**Comment by myokoym** [comment]
すみません、コメントに書いたところまでしか進んでいません。
方針を決めただけで、具体的な作業は未着手です。

**Comment by kou** [comment]
わかりました！

**Comment by kou** [comment]
ところで、これはもうだれもやるつもりはないやつですか？

**Comment by myokoym** [comment]
急ぎでなければ、今週末に続けるか引き取ってもらうか決めさせてください。

**Comment by kou** [comment]
急ぎでないので今週末に決めるので問題ないです！

**Comment by myokoym** [comment]
少なくとも今月中は再着手できなそうなので、引き取ってもらえるならお願いしたいです。

**Comment by kou** [comment]
Done.
