### ISSUE TITLE
dumpコマンドをmrubyで実装してカスタマイズ可能にする

### ISSUE THREAD

**Issue by myokoym** [groonga/groonga#285]
今のdumpコマンドは、grndumpのように出力をカスタマイズすることができません。
Cで実装するのは難しいので、mrubyで置き換えてからカスタマイズ可能にします。
進め方は以下です。

1. dumpコマンドをmrubyで置き換える
  * mrubyが無効の場合は既存のdumpコマンドが使われるようにする
  * lib/に作るか、plugins/に作って最初から読み込むか検討
2. mrubyで置き換えたdumpコマンドの出力をカスタマイズできるようにする

### テストの動かし方

* `test/command/run-test.sh`
  * MeCabとエラーメッセージのパスのテストが失敗した
* mecab-naist-jdicを使う
  * replacement of ipadic
* パスが深いとエラーメッセージが切られて失敗する
  * テストを修正するのは難しそうだったので、浅い場所で作業する

#### 新しくregisterするmrubyプラグインを追加する方法

1. 以下のファイルを作成する。

  * plugins/プラグイン名.rb
  * plugins/プラグイン名/Makefile.am
  * plugins/プラグイン名/CMakeLists.txt
  * plugins/プラグイン名/sources.am
  * plugins/プラグイン名/コマンド名.rb

2. 以下のファイルを修正する。

  * configure.ac
  * plugins/Makefile.am
  * plugins/CMakeLists.txt

#### 既存のプラグインにコマンドを追加する場合

1. 以下のファイルを作成する。

  * plugins/プラグイン名/コマンド名.rb

2. 以下のファイルを修正する。

  * plugins/プラグイン名/Makefile.am
  * plugins/プラグイン名/CMakeLists.txt
  * plugins/プラグイン名/sources.am

### Cのプラグインを定義する方法

* `DEF_COMMAND`マクロ
* `#ifndef`チェックでmrubyが無効のときだけCのdumpコマンドを定義するようにする

### Cのプラグインをデフォルトで有効にする方法

* <del>proc.c</del>lib/tokenizers.cの`grn_db_init_mecab_tokenizer`をdb.cの`grn_db_open`関数で呼んでいるので参考にする

### mrubyのプラグインをデフォルトで有効にする方法

* `lib/ctx_impl_mrb.c`で呼ばれているpost.rbあたり
* post.rb -> `plugin_loader` -> `PluginLoader.load_file`すればよさそう
* `grn_plugin_call_register` -> `grn_plugin_call_register_mrb` -> `load_file`
* `grn_plugin_register` -> `grn_plugin_register_by_path` -> `grn_plugin_call_register`
* lib/proc.c: `DEF_COMMAND` -> `proc_register` -> `grn_plugin_register`

* プラグインのパス
  * pluginsディレクトリーは`grn_plugin_register` -> `grn_plugin_find_path`で見つけてるっぽい
  * `grn_plugin_register`や`grn_plugin_find_path`をmrubyにバインドすればよさそう？
    * Rubyで書いてもよい？
    * mrubyにバインドするなら方法を調べる

* mrubyからregisterする方法の調査
  * `Groonga::Plugins.load_file`だけだと`invalid command name: dump`になる
  * `registered_plugins`に入れないとだめなのかも
  * `grn_plugin_register`をバインドする？
  * バインドするならlib/plugin.hを作らないとだめかも
  * `lib/grn_plugin.h`あった
  * `mrb_grn_command_singleton_register`は呼ばれているはずだけど、これではだめなのか
  * CからはMeCabをregisterしている箇所があるので、まずはCで書いた方がいいかも

**Comment by myokoym** [comment]
mrubyが有効の場合に読み込まれるdumpコマンド（まだ何もdumpできない）は作れたので、
これをベースに改良していきます。

mrb: try to bind dump command to replace by mruby (work in progress) · 6524301 · myokoym/groonga
https://github.com/myokoym/groonga/commit/65243019c5e8c6088a324108e9433efb46f08888

次は2hを目安にテーブルのスキーマだけ出力できるようにします。

**Comment by myokoym** [comment]
コマンドに文字列を出力するには`lib/mrb/mrb_writer.c`を使うということはわかりましたが、
以下の課題があります。

* 既存の`write`メソッドはコマンドの実行結果のヘッダーも出力される。
  * dumpコマンドの出力はヘッダー不要。
* 今日のテスト中に`write`メソッドで何も出力されなくなってしまった。
  * 昨日は出力されていた気がする。

なので、改めて以下の手順で進めたいと思います。

* `write`メソッドで何も出力されない理由の調査
* ヘッダーを出力しない方法の調査
* テーブル情報の取得方法の調査（`Database#each_table`で取得できる？）

**Comment by kou** [comment]
中で`grn_ctx_set_output_type()`を呼ぶ`Groonga::Writer#content_type=`を作って`writer.content_type = Groonga::ContentType::GROONGA_COMMAND_LIST` するようにしてください！
`Groonga::ContentType`モジュールと`Groonga::ContentType::GROONGA_COMMAND_LIST`とかは新しく作る必要があります。

**Comment by myokoym** [comment]
わかりました！以下の手順で進めます。

* `Groonga::ContentType`モジュール作成
  * `lib/mrb/mrb_content_type.c`作成
  * 定数（`Groonga::ContentType::GROONGA_COMMAND_LIST`など）作成
* `Groonga::Writer#content_type=`作成
  * 引数（`Groonga::ContentType`）を受け取れるようにする
    * 型は`"o"`（オブジェクト）？
  * `grn_ctx_set_output_type()`へ`Groonga::ContentType`を渡す
    * mrubyの定数をCの定数に変換する必要があるか
    * 必要があれば、どう変換するか

**Comment by kou** [comment]
Close because `dump` implemeted by C is updated.
