### ISSUE TITLE
VS 2010 dose not have `fmax` and `fmin` functions

### ISSUE THREAD

**Issue by cosmo0920** [groonga/groonga#286]
VS 2010 does not have `fmax` and `fmin` functions.
They are C99 feature. 
But, VS 2010 dose not implement them.
VS 2013 implements them. ref: http://blogs.msdn.com/b/vcblog/archive/2013/07/19/c99-library-support-in-visual-studio-2013.aspx

So, they causes compilation error with VS 2010:

```log
...
14>..\..\..\..\..\..\source\storage\mroonga\vendor\groonga\lib\scorers.c(37): warning C4244: '=' : 'unsigned __int64' から 'double' への変換です。データが失われる可能性があります。
14>..\..\..\..\..\..\source\storage\mroonga\vendor\groonga\lib\scorers.c(38): warning C4244: '=' : 'unsigned __int64' から 'double' への変換です。データが失われる可能性があります。
14>..\..\..\..\..\..\source\storage\mroonga\vendor\groonga\lib\scorers.c(50): warning C4013: 関数 'fmax' は定義されていません。int 型の値を返す外部関数と見なします。
14>..\..\..\..\..\..\source\storage\mroonga\vendor\groonga\lib\scorers.c(87): warning C4013: 関数 'fmin' は定義されていません。int 型の値を返す外部関数と見なします。
14>  store.c
14>  str.c
14>  string.c
```

Complete log is here: https://dl.dropboxusercontent.com/u/36753409/build-VS2010-20150223-nightly.log

Mroonga still supports VS 2010? Or, no longer support it?

**Comment by kou** [comment]
Oh...
We drop VS 2010. Because MariaDB disables Mroonga on VS.

Could you update MSVC version check in CMakeLists.txt?

**Comment by cosmo0920** [comment]
> We drop VS 2010. Because MariaDB disables Mroonga on VS.

Oh, I see.

> Could you update MSVC version check in CMakeLists.txt?

Certainly.

**Comment by cosmo0920** [comment]
VS 2012 seems to be support `fmax` and `fmin`.
Mroonga supports VS 2012?
Or, Mroonga supports VS 2013 or later?

**Comment by kou** [comment]
VS 2013 or later because we don't have VS 2012.

**Comment by cosmo0920** [comment]
Oh, I've got it!

**Comment by cosmo0920** [comment]
Drop VS 2010 (and also drop VS 2012) support already merged into `Groonga` and `Mroonga` master.
Can I close this issue?

**Comment by kou** [comment]
Yes, please.

**Comment by cosmo0920** [comment]
Done!
