### ISSUE TITLE
get nested text in nested index search

### ISSUE THREAD

**Issue by istarkov** [groonga/groonga#297]
In documentation here `http://groonga.org/docs/tutorial/match_columns.html#nested-index-search-among-related-table-by-column-index` in this query `select Articles --match_columns comment.content --query groonga --output_columns "_id, _score, *"` i wish to get comment text which satisfy to query.

For example if Article has two comments:
* comment1: ''bla bla bla"
* comment2: "groonga is very nice"

with query above i wish to see `"groonga is very nice"` in query results.

Is that possible?

**Comment by kou** [comment]
You can get comment content by `comment.content` in `--output_columns`.
`select Articles --match_columns comment.content --query groonga --output_columns "_id, _score, content, comment.content"` may be what you want.

**Comment by istarkov** [comment]
i know about `match_columns comment.content` 
but it gives me all comments - in example above it gives `bla bla bla` comment for `--query groonga`. 

But i need only comments (or one comment) which matched to query.

**Comment by kou** [comment]
If you get comment not article, you should specify `Comments` to `select` command like the following:

```text
select Comments --match_columns content --query groonga
```

If you add a reference to `Articles` to `Comments`, you can refer the article for the matched comment.

**Comment by istarkov** [comment]
Is any possibility get to get distinct Articles by such query. 
For example i search some words in article comments, 
and on the search page i want to show article title and small amount of comments satisfying query words. 
So in example above i want to show Article with comment 'groonga is very nice' once and only once even if there are a lot of such comments.
In my situation i have a lot of such "comments" in every article, all "comments" have a lot of similar words, and almost every query request selects all such comments, so i'll have a great overhead to make distinct

**Comment by kou** [comment]
The following `select` command may be what you want but it's too tricky...:

```text
select Comments \
  --match_columns content \
  --query "bla" \
  --limit 0 \
  --drilldown[article].keys article,article._id \
  --drilldown[article].output_columns _value.article.content,_value.content
```

You can try it with the following schema and data:


```text
table_create Comments TABLE_HASH_KEY ShortText
column_create Comments content COLUMN_SCALAR ShortText

table_create Articles TABLE_HASH_KEY ShortText
column_create Articles content COLUMN_SCALAR Text
column_create Articles comments COLUMN_VECTOR Comments

column_create Comments article COLUMN_SCALAR Articles

table_create Lexicon TABLE_PAT_KEY|KEY_NORMALIZE ShortText --default_tokenizer TokenBigram
column_create Lexicon articles_content COLUMN_INDEX|WITH_POSITION Articles content
column_create Lexicon comments_content COLUMN_INDEX|WITH_POSITION Comments content
column_create Comments article_index COLUMN_INDEX Articles comments


load --table Comments
[
{
  "_key": "comment-1-1",
  "article": "article-1",
  "content": "I'm using Groonga too!"
},
{
  "_key": "comment-1-2",
  "article": "article-1",
  "content": "bla bla bla"
},
{
  "_key": "comment-2-1",
  "article": "article-2",
  "content": "I'm using Groonga and Mroonga!"
},
{
  "_key": "comment-2-2",
  "article": "article-2",
  "content": "bla bla bla"
},
{
  "_key": "comment-2-3",
  "article": "article-2",
  "content": "bla bla"
},
{
  "_key": "comment-3-1",
  "article": "article-3",
  "content": "I'm using mroonga too!"
}
]

load --table Articles
[
{
  "_key": "article-1",
  "content": "Groonga is fast!",
  "comments": ["comment-1-1", "comment-1-2"]
},
{
  "_key": "article-2",
  "content": "Groonga is useful!",
  "comments": ["comment-2-1", "comment-2-2", "comment-2-3"]
},
{
  "_key": "article-3",
  "content": "Mroonga is fast!",
  "comments": ["comment-3-1"]
},
]
```

**Comment by istarkov** [comment]
Thank you! It works!
