### ISSUE TITLE
NormalizerNFKC51 NormalizerAuto does not work for cyrillic characters

### ISSUE THREAD

**Issue by istarkov** [groonga/groonga#303]
for example out for this commands

```
normalize NormalizerNFKC51 "ЛИЦЕНЗИЯ"
normalize NormalizerAuto "ЛИЦЕНЗИЯ"
normalize NormalizerAuto "ПРИВЕТ"
```

must be 

```
лицензия
лицензия
привет
```

but i get 

```
ЛИЦЕНЗИЯ
ЛИЦЕНЗИЯ
ПРИВЕТ
```

search also work as no normalization set.

**Comment by kou** [comment]
Oh...
We should fix the problem but it's a heavy task.

I show a workaround: Please use `NormalizerMySQLGenearalCI` or `NormalizerMySQLUnicodeCI` included in [groonga-normalizer-mysql](https://github.com/groonga/groonga-normalizer-mysql). The package provides MySQL compatible normalizers. They support cyrillic characters.

**Comment by istarkov** [comment]
I did, NormalizerMySQLGenearalCI and NormalizerMySQLUnicodeCI also does not support cyrillic.
So i normalize in my code by adding additional "prenormalized" column.

**Comment by kou** [comment]
Really?

```text
> register normalizers/mysql
[[0,1426145246.39232,0.000321149826049805],true]
> normalize NormalizerMySQLGeneralCI "ЛИЦЕНЗИЯ"
[[0,1426145258.13746,0.000116109848022461],{"normalized":"ЛИЦЕНЗИЯ","types":[],"checks":[]}]
> normalize NormalizerMySQLGeneralCI "лицензия"
[[0,1426145287.83178,0.000104427337646484],{"normalized":"ЛИЦЕНЗИЯ","types":[],"checks":[]}]
```

Both `ЛИЦЕНЗИЯ` and `лицензия` are normalized to `ЛИЦЕНЗИЯ`.

**Comment by istarkov** [comment]
Wow, my fault, i've checked only backward situation from UpperCase to Lower like NormalizerAuto do.
Thank you a lot!!!

**Comment by kou** [comment]
The next Groonga will include a new normalizer `NormalizerNFKC100`. It's based on Unicode 10.0 and supports case normalization for Cyrillic characters.
