### ISSUE TITLE
selectの出力のJSONが壊れていることがある

### ISSUE THREAD

**Issue by kenhys** [groonga/groonga#330]
## 不具合の内容

groonga-devで報告があった。BODYの直前に余分な"1"が付くとのこと。

```
[[0,1426775540.63765,0.00017857551574707],1[[[2],[["_id","UInt32"],["_key","UInt64"],
```

発生した環境は次のとおりとのこと。
- OS: CentOS6.6 64ビット
- バージョン4.0.4をソースからビルド、5.0.0のパッケージをyumでインストールしたが両方で発生している

結構前から問題が発生していたため、余分な"1"を除去して対処しているとのこと。
## 経過

[groonga-dev,03140] selectの出力のJSONが壊れていることがある
- http://sourceforge.jp/projects/groonga/lists/archive/dev/2015-March/003142.html
  - 最初の問題報告のメール
- http://sourceforge.jp/projects/groonga/lists/archive/dev/2015-March/003143.html
  - 先頭の最後か、BODYの先頭のバッファが問題である可能性について言及
  - 4.0.3でバッファの構造が変わったことによる可能性
- http://sourceforge.jp/projects/groonga/lists/archive/dev/2015-March/003144.html
  - 全部 "1"で発生した場所も同じという報告
  - POST対応のバージョンでないとすぐに試せない(4.0.2をためすのは難しいという)返信

**Comment by kenhys** [comment]
手元で`,`が余計に付与されるケースについてたまたまかもしれないが再現できたのでメモしておく。
(groonga 5.0.0でcurl http://localhost:10041/d/statusを実行して何度か再現したケース)

ひとまずわかっていることは、grn_ctx_recvした段階でchunkの先頭に余計な`,`がついていた。
ここで期待しているのは先頭に`,`のないデータ。
なのでgrn_ctx_recvするまえの段階でおかしくなっているっぽい。
(groonga.c:915のあたり)

```
(gdb) bt
#0  h_output_typed (ctx=0x7f8baae74da0, flags=2, hc=0x7f8baae74ef0) at groonga.c:916
#1  0x0000000000407ecc in h_output (ctx=0x7f8baae74da0, flags=2, arg=0x7f8baae74ef0) at groonga.c:942
#2  0x00007f8bb6301f62 in grn_ctx_send (ctx=0x7f8baae74da0, 
    str=0x122a944 "/d/status HTTP/1.1\r\nUser-Agent: curl/7.38.0\r\nHost: localhost:10041\r\nAccept: */*\r\n\r\nt: */*\r\nUser-Agent: Ruby\r\nHost: localhost:10041\r\n\r\n\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept"..., str_len=9, flags=0) at ctx.c:1945
#3  0x0000000000407fbb in do_htreq_get (ctx=0x7f8baae74da0, msg=0x11fe630) at groonga.c:967
#4  0x0000000000409655 in do_htreq (ctx=0x7f8baae74da0, msg=0x11fe630) at groonga.c:1267
#5  0x000000000040c6d0 in h_worker (arg=0x120e650) at groonga.c:1890
#6  0x00007f8bb583d0a4 in start_thread (arg=0x7f8baae75700) at pthread_create.c:309
#7  0x00007f8bb4d5004d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) p chunk
$304 = 0x7f8ba42636d0 ",{\"alloc_count\":477,\"starttime\":1429706581,\"uptime\":16891,\"version\":\"5.0.0\",\"n_queries\":24875,\"cache_hit_rate\":0.317587939698492,\"command_version\":1,\"default_command_version\":1,\"max_command_version\":2"...
```

chunkの内容をbodyにコピーしてh_output_sendを呼ぶのでchunkが壊れているとアウト。
h_output_typed -> grn_ctx_recv -> h_output_send ->  sendmsgの流れになっている。

**Comment by kenhys** [comment]
grn_ctx_recvに以下のような箇所があって、headぶんを読み飛ばすことを意図しているようだけど実際には常にhead=0のままなので余計な`,`も含まれたままになっている。

```
      grn_obj *buf = ctx->impl->outbuf;
      unsigned int head = 0, tail = GRN_BULK_VSIZE(buf);
      *str = GRN_BULK_HEAD(buf) + head;
      *str_len = tail - head;
      GRN_BULK_REWIND(ctx->impl->outbuf);
```

**Comment by kou** [comment]
どうやって再現させたか手順をまとめてもらえませんか？

**Comment by kou** [comment]
直ったはず。
