### ISSUE TITLE
ソースからビルドしようとするとmakeでエラーになる。

### ISSUE THREAD

**Issue by hiroyasutake** [groonga/groonga#334]
ご担当者様。

AmazonLinuxにgroongaをいれようとしています。
configureまでうまく通るのですが、makeの部分で以下のエラーがでます。
無知で申し訳ないのですが、ご助言いただければと思います。

 CC       expr.lo
expr.c: In function 'grn_expr_exec':
expr.c:3499:1: warning: const/copy propagation disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
 }
 ^
expr.c:3499:1: warning: PRE disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
expr.c:3499:1: warning: const/copy propagation disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
expr.c:3499:1: warning: const/copy propagation disabled: 18950 basic blocks and 62875 registers [-Wdisabled-optimization]
make[4]: *** [expr.lo] エラー 1
make[4]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[3]: *** [all-recursive] エラー 1
make[3]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[2]: *** [all] エラー 2
make[2]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[1]: *** [all-recursive] エラー 1
make[1]: ディレクトリ `/usr/local/src/groonga-5.0.2' から出ます
make: *** [all] エラー 2

**Comment by kou** [comment]
ログにでている↓にはerrorではなくwarning扱いとでています。

```text
expr.c: In function 'grn_expr_exec':
expr.c:3499:1: warning: const/copy propagation disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
}
^
expr.c:3499:1: warning: PRE disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
expr.c:3499:1: warning: const/copy propagation disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
expr.c:3499:1: warning: const/copy propagation disabled: 18950 basic blocks and 62875 registers [-Wdisabled-optimization]
```

`make V=1`とするとさらにメッセージがでるのでその結果を教えてもらえますか？

メッセージがない状態での予想では、ビルドしているマシンの使用可能なメモリーが少ない（1GBとか）のが原因かなぁと思っています。もしそうなら、スワップを増やすか最適化をしないビルドにすることで解決できます。ただし、最適化をしないビルドでは速度が落ちるので注意する必要があります。

必ずしも自分でビルドしなくてもよい、という場合は、AmazonLinuxならCentOSのパッケージを使えるのでパッケージでインストールする方がよいかもしれません。パッケージのものは最適化を有効にした状態でビルドしてあります。

**Comment by hiroyasutake** [comment]
早速の返信ありがとうございます。
以下のような結果になりました。

libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -D_REENTRANT -DGRN_DLL_FILENAME=L\"libgroonga-0.dll\" -DGRN_PLUGINS_DIR=\"/usr/local/lib/groonga/plugins\" -DGRN_RELATIVE_PLUGINS_DIR=\"lib/groonga/plugins\" -DGRN_RUBY_SCRIPTS_DIR=\"/usr/local/lib/groonga/scripts/ruby\" -DGRN_RELATIVE_RUBY_SCRIPTS_DIR=\"lib/groonga/scripts/ruby\" -DGRN_LOG_PATH=\"/usr/local/var/log/groonga/groonga.log\" -DGRN_DEFAULT_DOCUMENT_ROOT=\"/usr/local/share/groonga/html/admin\" -DGRN_DEFAULT_RELATIVE_DOCUMENT_ROOT=\"share/groonga/html/admin\" -DGRN_DAT_EXPORT -I.. -I../include -I../vendor/onigmo-source -fno-strict-aliasing -g -O2 -Wall -Wextra -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-sign-compare -Wno-pointer-sign -Wno-missing-field-initializers -Wformat=2 -Wstrict-aliasing=2 -Wdisabled-optimization -Wfloat-equal -Wpointer-arith -Wbad-function-cast -Wcast-align -Wredundant-decls -Wwrite-strings -MT expr.lo -MD -MP -MF .deps/expr.Tpo -c expr.c  -fPIC -DPIC -o .libs/expr.o
expr.c: In function 'grn_expr_exec':
expr.c:3499:1: warning: const/copy propagation disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
 }
 ^
expr.c:3499:1: warning: PRE disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
expr.c:3499:1: warning: const/copy propagation disabled: 21538 basic blocks and 62073 registers [-Wdisabled-optimization]
expr.c:3499:1: warning: const/copy propagation disabled: 18950 basic blocks and 62875 registers [-Wdisabled-optimization]
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -D_REENTRANT -DGRN_DLL_FILENAME=L\"libgroonga-0.dll\" -DGRN_PLUGINS_DIR=\"/usr/local/lib/groonga/plugins\" -DGRN_RELATIVE_PLUGINS_DIR=\"lib/groonga/plugins\" -DGRN_RUBY_SCRIPTS_DIR=\"/usr/local/lib/groonga/scripts/ruby\" -DGRN_RELATIVE_RUBY_SCRIPTS_DIR=\"lib/groonga/scripts/ruby\" -DGRN_LOG_PATH=\"/usr/local/var/log/groonga/groonga.log\" -DGRN_DEFAULT_DOCUMENT_ROOT=\"/usr/local/share/groonga/html/admin\" -DGRN_DEFAULT_RELATIVE_DOCUMENT_ROOT=\"share/groonga/html/admin\" -DGRN_DAT_EXPORT -I.. -I../include -I../vendor/onigmo-source -fno-strict-aliasing -g -O2 -Wall -Wextra -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-sign-compare -Wno-pointer-sign -Wno-missing-field-initializers -Wformat=2 -Wstrict-aliasing=2 -Wdisabled-optimization -Wfloat-equal -Wpointer-arith -Wbad-function-cast -Wcast-align -Wredundant-decls -Wwrite-strings -MT expr.lo -MD -MP -MF .deps/expr.Tpo -c expr.c -o expr.o >/dev/null 2>&1
make[4]: *** [expr.lo] エラー 1
make[4]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[3]: *** [all-recursive] エラー 1
make[3]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[2]: *** [all] エラー 2
make[2]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[1]: *** [all-recursive] エラー 1
make[1]: ディレクトリ `/usr/local/src/groonga-5.0.2' から出ます
make: *** [all] エラー 2

**Comment by kou** [comment]
ありがとうございます！

残念ながら、見たい出力が`>/dev/null 2>&1`でなくなっていました。。。

すみませんが、もう一度↓でビルドした結果を見せてもらえませんか？

```text
% make V=1 CPPFLAGS=-no-suppress
```

**Comment by hiroyasutake** [comment]
実行結果は以下のようになりました！

depbase=`echo expr.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -D_REENTRANT -DGRN_DLL_FILENAME=L\""libgroonga-0.dll"\" -DGRN_PLUGINS_DIR=\""/usr/local/lib/groonga/plugins"\" -DGRN_RELATIVE_PLUGINS_DIR=\""lib/groonga/plugins"\" -DGRN_RUBY_SCRIPTS_DIR=\""/usr/local/lib/groonga/scripts/ruby"\" -DGRN_RELATIVE_RUBY_SCRIPTS_DIR=\""lib/groonga/scripts/ruby"\" -DGRN_LOG_PATH=\""/usr/local/var/log/groonga/groonga.log"\" -DGRN_DEFAULT_DOCUMENT_ROOT=\""/usr/local/share/groonga/html/admin"\" -DGRN_DEFAULT_RELATIVE_DOCUMENT_ROOT=\""share/groonga/html/admin"\" -DGRN_DAT_EXPORT -I.. -I../include  -I../vendor/onigmo-source   -no-suppress -fno-strict-aliasing     -g -O2 -Wall -Wextra -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-sign-compare -Wno-pointer-sign -Wno-missing-field-initializers -Wformat=2 -Wstrict-aliasing=2 -Wdisabled-optimization -Wfloat-equal -Wpointer-arith -Wbad-function-cast -Wcast-align -Wredundant-decls -Wwrite-strings   -MT expr.lo -MD -MP -MF $depbase.Tpo -c -o expr.lo expr.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -D_REENTRANT -DGRN_DLL_FILENAME=L\"libgroonga-0.dll\" -DGRN_PLUGINS_DIR=\"/usr/local/lib/groonga/plugins\" -DGRN_RELATIVE_PLUGINS_DIR=\"lib/groonga/plugins\" -DGRN_RUBY_SCRIPTS_DIR=\"/usr/local/lib/groonga/scripts/ruby\" -DGRN_RELATIVE_RUBY_SCRIPTS_DIR=\"lib/groonga/scripts/ruby\" -DGRN_LOG_PATH=\"/usr/local/var/log/groonga/groonga.log\" -DGRN_DEFAULT_DOCUMENT_ROOT=\"/usr/local/share/groonga/html/admin\" -DGRN_DEFAULT_RELATIVE_DOCUMENT_ROOT=\"share/groonga/html/admin\" -DGRN_DAT_EXPORT -I.. -I../include -I../vendor/onigmo-source -fno-strict-aliasing -g -O2 -Wall -Wextra -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-sign-compare -Wno-pointer-sign -Wno-missing-field-initializers -Wformat=2 -Wstrict-aliasing=2 -Wdisabled-optimization -Wfloat-equal -Wpointer-arith -Wbad-function-cast -Wcast-align -Wredundant-decls -Wwrite-strings -MT expr.lo -MD -MP -MF .deps/expr.Tpo -c expr.c  -fPIC -DPIC -o .libs/expr.o
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[4]: *** [expr.lo] エラー 1
make[4]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[3]: *** [all-recursive] エラー 1
make[3]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[2]: *** [all] エラー 2
make[2]: ディレクトリ `/usr/local/src/groonga-5.0.2/lib' から出ます
make[1]: *** [all-recursive] エラー 1
make[1]: ディレクトリ `/usr/local/src/groonga-5.0.2' から出ます
make: *** [all] エラー 2

**Comment by kou** [comment]
ありがとうございます！

```text
 gcc: internal compiler error: Killed (program cc1)
```

とでているので、メモリー不足な気がします。メモリーを増やしてビルドしてみてください。

ちなみに、今はメモリーはどのくらいですか？

**Comment by hiroyasutake** [comment]
いろいろありがとうございます。
1GBになります。

まずはパッケージのインストールで進めていこうと思います。

**Comment by hiroyasutake** [comment]
おかげさまで、groongaとmroongaをインストールできました。
mysql5.6とともに動かしています。

また1つ質問させていただきたいです。
上記通り無事にインストールができて①のようなコマンドで検索もできている状況なのですが、
いざ②のような形でデータ取得しようとするとemptyになってしまいます。
groonga.logは以下のような出力になっていて、②の*をcount(*)にすると2件と表示されます。
文字コードの問題などでしょうか。。。

①select mroonga_command("select memo --match_columns content --query'東京' --output_type tsv");
②SELECT * FROM memos WHERE MATCH (content) AGAINST ("東京");

【groonga.log】
2015-04-19 07:20:25.511907|i|ba8bd700|grn_ii_sel > (東京)
2015-04-19 07:20:25.512087|i|ba8bd700|exact: 2
2015-04-19 07:20:25.512098|i|ba8bd700|hits=2

**Comment by kou** [comment]
`SHOW CREATE TABLE memos`した結果と使った`INSERT`文と`SELECT * FROM memos`の結果を教えてもらえますか？

**Comment by hiroyasutake** [comment]
このようなかたちになります。

mysql> show create table memos;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| memos | CREATE TABLE `memos` (
  `id` int(11) NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT KEY `content` (`content`)
) ENGINE=Mroonga DEFAULT CHARSET=utf8 |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> insert into memos(id,content) value(2,"東京都渋谷区");
Query OK, 1 row affected (0.00 sec)

mysql> select * from memos;
+----+--------------------+
| id | content            |
+----+--------------------+
|  1 | 東京都港区         |
|  2 | 東京都渋谷区       |
+----+--------------------+
2 rows in set (0.00 sec)

mysql>

**Comment by kou** [comment]
ありがとうございます。

CentOS 7 x86_64で試してみたのですが再現しませんでした。。。AmazonLinuxだからなんですかねぇ。。。

次の結果を教えてもらえますか？

  * `SELECT * FROM memos WHERE MATCH (content) AGAINST ("東京");`の実行結果
  * `SELECT COUNT(*) FROM memos WHERE MATCH (content) AGAINST ("東京");`の実行結果
  * `SHOW VARIABLES LIKE '%version%';`の実行結果
  * `rpm -qa | grep mysql`の実行結果

**Comment by hiroyasutake** [comment]
ご連絡ありがとうございます。
こちらもAWSにCentOS7で動かすとパッケージ依存もなくすんなり入って動作できていました。
予算的にAmazonLinuxに変更してやってみるとパッケージ依存がありビルドしてインストールを進めている状況です。

mysql> SELECT * FROM memos WHERE MATCH (content) AGAINST ("東京");
Empty set (0.00 sec)

mysql> SELECT COUNT(*) FROM memos WHERE MATCH (content) AGAINST ("東京");
+----------+
| COUNT(*) |
+----------+
|        2 |
+----------+
1 row in set (0.00 sec)

mysql> SHOW VARIABLES LIKE '%version%';
+----------------------------+---------------------+
| Variable_name              | Value               |
+----------------------------+---------------------+
| innodb_version             | 5.6.24              |
| mroonga_libgroonga_version | 5.0.2               |
| mroonga_version            | 5.00                |
| protocol_version           | 10                  |
| slave_type_conversions     |                     |
| version                    | 5.6.24              |
| version_comment            | Source distribution |
| version_compile_machine    | x86_64              |
| version_compile_os         | Linux               |
+----------------------------+---------------------+
9 rows in set (0.00 sec)

$ rpm -qa | grep mysql
groonga-normalizer-mysql-1.0.9-1.el6.x86_64

**Comment by kou** [comment]
あぁ、自分でビルドしていたんですか。今は5.00を使っていますが（ドキュメントが5.00のままになっていますね。。。）、5.01を使ってください。Groongaの最新版を使うときはMroongaも最新（今だと5.01）を使う必要があるんです。

**Comment by hiroyasutake** [comment]
ありがとうございます！
一度そちらで再度試してみます。

**Comment by hiroyasutake** [comment]
無事解決できました。ありがとうございました！

mysql> SHOW VARIABLES LIKE '%version%';
+----------------------------+---------------------+
| Variable_name              | Value               |
+----------------------------+---------------------+
| innodb_version             | 5.6.24              |
| mroonga_libgroonga_version | 5.0.2               |
| mroonga_version            | 5.01                |
| protocol_version           | 10                  |
| slave_type_conversions     |                     |
| version                    | 5.6.24              |
| version_comment            | Source distribution |
| version_compile_machine    | x86_64              |
| version_compile_os         | Linux               |
+----------------------------+---------------------+
9 rows in set (0.00 sec)

mysql> SELECT * FROM memos WHERE MATCH (content) AGAINST ("東京");
+----+--------------------+
| id | content            |
+----+--------------------+
|  1 | 東京都港区         |
|  2 | 東京都渋谷区       |
+----+--------------------+
2 rows in set (0.00 sec)

**Comment by kou** [comment]
よかったです！
