### ISSUE TITLE
grn_select内でgrn_parse_query_flagsの後にctx->rcをチェックしなくて良い？

### ISSUE THREAD

**Issue by hnakamur** [groonga/groonga#336]
ソースコードを見ていてちょっと気になったので質問させてください。

https://github.com/groonga/groonga/blob/863f62079eed3bbc22c0976f341c1e6f49ef0bb8/lib/proc.c#L985-L992
で `else` 側で `ctx->rc` を見ていますが、ここでは不要ではないでしょうか？ むしろ `else` でないほうで `grn_parse_query_flags` を呼んだ後に `ctx->rc` のチェックを行うべきではないでしょうか？

**Comment by kou** [comment]
その通りなのでそうしました！

**Comment by hnakamur** [comment]
素早い対応ありがとうございました！
