### ISSUE TITLE
Document the log rotation options

### ISSUE THREAD

**Issue by myokoym** [groonga/groonga#337]
* [x] add `--log-rotate-threshold-size`
* [x] add `--query-log-rotate-threshold-size`
* [x] translate

references:
* http://groonga.org/docs/reference/executables/groonga.html#options
* https://github.com/groonga/groonga/blob/master/doc/source/reference/executables/groonga.rst
* https://github.com/groonga/groonga/blob/master/src/groonga.c#L2602

**Comment by kenhys** [comment]
groonga.orgへ反映したら完了

**Comment by myokoym** [comment]
以下のコマンドで反映したので完了とします。

    make update-document DOCUMENT_VERSION=5.0.3 DOCUMENT_VERSION_FULL=5.0.3
