### ISSUE TITLE
Typo 筆意用 -> 必要

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga#338]
Hello 

I found typo. 

[筆意用](https://github.com/groonga/groonga/blob/master/doc/locale/ja/LC_MESSAGES/reference.po#L18023)

* 誤: 筆意用
* 正: 必要

追伸: PRしようと思ったのですが、私の環境(Macだと、修正箇所以外のところが修正されたとみなされてしまい、不要な修正が含まれたPRとなってしまうため、場所のみお知らせします。

**Comment by myokoym** [comment]
ご報告ありがとうございます！助かりました！
