### ISSUE TITLE
Systemdに移行したdebパッケージからinit.dのファイルを削除する

### ISSUE THREAD

**Issue by myokoym** [groonga/groonga#346]
#343 のつづきとして、Systemdに移行したDebian GNU/Linux Jessieと
Ubuntu 15.04向けのパッケージからinit.dのファイルを削除する。
5.0.5のリリースで対応するのが目標。

**Comment by myokoym** [comment]
#343 のgroonga-httpdと #344 のgroonga-server-gqtpの両方とも対応する必要がある。

**Comment by kou** [comment]
これ、今のステータスってどうなっているのかしら。

**Comment by kou** [comment]
単にファイルを削除すればいいのかしら。

**Comment by myokoym** [comment]
すみません、issueを立てただけで未着手でした。
急ぎでなければ今週末に続けるか引き取ってもらうか決めさせてください。

**Comment by myokoym** [comment]
私は少なくとも今月中は着手できなそうです。もしできる方がいればお願いします。

**Comment by ohkubo** [comment]
はじめまして。
Debian jessie でも、 sysvinit-core パッケージをインストールすることで wheezy 同様の SysV 環境が利用可能なのですが、この点に関しては考慮済でしょうか？
試しに、 sysvinit-core をインストールした jessie に、 groonga-httpd (packages.groonga.org) をインストールしてみたところ、 SysV 環境で groonga は問題なく起動しました。
その状態で、 /etc/init.d/groonga-httpd を削除し、リブートすると、groonga は起動していませんでした。
具体的な修正方法は見えていないので、杞憂だったら良いのですが。

**Comment by kou** [comment]
情報ありがとうございます！

systemdパッケージに依存させておいたほうがよさそうですねぇ。

**Comment by kou** [comment]
いや、それは余計なお世話。。。なのか？

**Comment by ohkubo** [comment]
systemd-sysv パッケージに依存すれば groonga は起動すると思いますが、それは環境をまるごと systemd にしてしまうことになるはずですので、さすがに影響が大きすぎる気がします。

雑な調査ですが、 jessie で、 /etc/init.d と /lib/systemd の両方のディレクトリを含むパッケージ、つまり SysV と systemd の両方のスクリプトを持っていると推測されるパッケージが 306 個見つかりました。

`$ grep -f <(apt-file search /lib/systemd | cut -f 1 -d :) <(apt-file search /etc/init.d | cut -f 1 -d :) | uniq | wc`

かなりメジャーと思われる以下のようなパッケージも含まれます:
udev at cron anacron dbus lxc nginx-common bind9 dnsmasq samba vsftpd sudo

見たところ、 Debian に関しては、デフォルトの init が systemd に切り替わったに過ぎず、 SysV も引き続き利用可能というのが私の印象です。
サポートコスト・検証コスト等 Drop したい事情があれば別ですが、個人的には、 init.d のファイルを積極的に削除すべき理由は特になさそうに思えます。

Debian 公式リポジトリ sid に kfreebsd-* の groonga が入っていますが、 kfreebsd-* の systemd は入っていないので、その点も考慮に入れたほうが良さそうです。

**Comment by kou** [comment]
確認ありがとうございます。

まとめると、init.dのファイルは消すな、ということですね。

では、残しておきます。
