### ISSUE TITLE
netinet/in.h is included conditionally but not chekcked in configure script

### ISSUE THREAD

**Issue by obache** [groonga/groonga#348]
netinet/in.h is included in followings with "#ifdef HAVE_NETINETIN_H" condition:
* src/groonga_benchmark.c
* src/grnslap.c
* src/groonga.c

But existence of netinet/in.h is not checked in configure script, so it will be never included.
At least, in groonga_benchmark.c is using "struct sockaddr_in", then it should be included certainly for POSIX environment (or resunt in build failure unless it is included by side effect).

The other hand, it is included in followings unless WIN32 is not defined:
* lib/com.c
* lib/ctx.c

Please check netnet/in.h or use WIN32 for conditional include of it.

**Comment by kou** [comment]
I've fixed it!
