### ISSUE TITLE
チュートリアルをわかりやすくする

### ISSUE THREAD

**Issue by HirotakaTakayama** [groonga/groonga#354]
## 元の文章
http://groonga.org/ja/docs/tutorial/introduction.html#create-a-database にて
>指定されたパスにファイルが存在しているときは失敗するので注意してください。

と記述されているが、失敗例が書かれている方が分かりやすいと感じた。

## 期待する追記
指定されたパスにファイルが存在しているときは、下記のように失敗するので注意してください。

失敗例：
`db open failed (/tmp/groonga-databases/introduction.db): syscall error '/tmp/groonga-databases/introduction.db' (File exists)`

**Comment by myokoym** [comment]
提案ありがとうございます！

確かに具体例があったほうが私もわかりやすいと思ったので、追記する方向で前向きに検討します。

このissueはドキュメントを修正するコミットをしたときにこちらでクローズしますが、もっといい案を思いついたなどがあれば追加でコメントしてください。

**Comment by myokoym** [comment]
@HirotakaTakayama 対応してみたので、ご確認お願いします！

**Comment by HirotakaTakayama** [comment]
@myokoym 確認しました！反映ありがとうございます！
:+1:

**Comment by myokoym** [comment]
確認ありがとうございます！では閉じますね。
今後も何か気になったことがあればお気軽にご活用ください。
