### ISSUE TITLE
JSONの表示がチュートリアルと違う

### ISSUE THREAD

**Issue by tiwawan** [groonga/groonga#355]
環境:ubuntu 14.10 64bit
groonga 5.0.4

### 期待される実行結果
http://groonga.org/ja/docs/tutorial/introduction.html#create-a-database
から引用
```
% groonga /tmp/groonga-databases/introduction.db
status
# [
#   [
#     0,
#     1337566253.89858,
#     0.000355720520019531
#   ],
#   {
#     "uptime": 0,
#     "max_command_version": 2,
#     "n_queries": 0,
#     "cache_hit_rate": 0.0,
#     "version": "4.0.1",
#     "alloc_count": 161,
#     "command_version": 1,
#     "starttime": 1395806057,
#     "default_command_version": 1
#   }
# ]
```

### 実際の実行結果
```
$ groonga introduction.db status
[[0,1435371313.10237,0.000842809677124023],{"alloc_count":169,"starttime":1435371312,"uptime":1,"version":"5.0.4","n_queries":0,"cache_hit_rate":0.0,"command_version":1,"default_command_version":1,"max_command_version":2}]
```

### 問題点
チュートリアルではJSONの配列が改行付きで表示されていますが、私の環境では一行で表示されました。

### 提案
JSONを整形表示するためのプログラムであるgrnwrap (http://d.hatena.ne.jp/michisu/20110416/p1) やgrnline (http://not-taihen.ruby.iijgio.com/blog/2013/06/15/grnline/) への案内をチュートリアルに追加してはいかがでしょうか。

**Comment by myokoym** [comment]
報告ありがとうございます！

おっしゃる通り、普通にコマンドを実行しただけではJSONは整形されません。整形するためには、提案してもらったgrnwrapのようなコマンドや、jqのようなツールを使う必要があります。

参考: [コマンドラインJSONパーサjqを使ってGroongaの出力結果を整形する方法 - CreateField](http://createfield.com/%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3JSON%E3%83%91%E3%83%BC%E3%82%B5jq%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6Groonga%E3%81%AE%E5%87%BA%E5%8A%9B%E7%B5%90%E6%9E%9C%E3%82%92%E6%95%B4%E5%BD%A2%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)

確かに提案してもらった案内をチュートリアルに追加したほうが私は親切だと思ったので、前向きに検討させてもらいます！

このissueはドキュメントを修正するコミットをしたときにこちらでクローズしますが、もっといい案を思いついたなどがあれば追加でコメントしてください。

**Comment by myokoym** [comment]
@tiwawan  対応してみたので、ご確認お願いします！不足などがあればご指摘ください。

**Comment by tiwawan** [comment]
ありがとうございます！特に不足は感じません、良いと思います:cat::+1:

**Comment by myokoym** [comment]
確認ありがとうございます！おかげでより良いドキュメントになりました。
また何かあればお気軽にご連絡ください :smiley_cat:
