### ISSUE TITLE
とあるキーワードを検索すると該当しないレコードも取得されてしまう。

### ISSUE THREAD

**Issue by TomyGX** [groonga/groonga#356]
検索ワード(そば)が含まれるCommunityTopicCommentのレコードを保持するCommunityTopicのレコードを取得したい。
現在、下記クエリを実行すると対象のキーワードが全く含まれていないレコードも取得されてしまいます。
(うまくいく単語もある・・・・)
どこか定義に過不足があればご教授をお願いいたします。

【クエリ】
select CommunityTopic --match_columns comment.message --query そば

【スキーマ】
# テーブル作成
table_create --name CommunityTopicComment --flags TABLE_HASH_KEY --key_type ShortText
column_create --table CommunityTopicComment --name message --type Text

table_create --name CommunityTopic --flags TABLE_HASH_KEY --key_type ShortText
column_create --table CommunityTopic --name title --type ShortText
column_create --table CommunityTopic --name description --type Text
column_create --table CommunityTopic --name comment --flags COLUMN_VECTOR --type CommunityTopicComment

table_create --name Community --flags TABLE_HASH_KEY --key_type ShortText
column_create --table Community --name title --type ShortText
column_create --table Community --name description --type Text
column_create --table Community --name visibility --type Int8
column_create --table Community --name topic --flags COLUMN_VECTOR --type CommunityTopic

# 語彙表作成
table_create --name TermsCommunity --flags TABLE_PAT_KEY --key_type ShortText --default_tokenizer TokenBigram --normalizer NormalizerAuto
column_create --table TermsCommunity --name community_title_index  --flags COLUMN_INDEX|WITH_POSITION --type Community --source title
column_create --table TermsCommunity --name community_description_index --flags COLUMN_INDEX|WITH_POSITION --type Community --source description
column_create --table TermsCommunity --name community_topic_ref_index --flags COLUMN_INDEX|WITH_POSITION --type Community --source topic
column_create --table TermsCommunity --name topic_title_index  --flags COLUMN_INDEX|WITH_POSITION --type CommunityTopic --source title
column_create --table TermsCommunity --name topic_description_index --flags COLUMN_INDEX|WITH_POSITION --type CommunityTopic --source description
column_create --table TermsCommunity --name topic_comment_ref_index --flags COLUMN_INDEX|WITH_POSITION --type CommunityTopic --source comment
column_create --table TermsCommunity --name comment_index --flags COLUMN_INDEX|WITH_POSITION --type CommunityTopicComment --source message

【バージョン】
groonga 5.0.2

**Comment by kou** [comment]
↓の2つのインデックスを

```text
column_create --table TermsCommunity --name community_topic_ref_index --flags COLUMN_INDEX|WITH_POSITION --type Community --source topic

column_create --table TermsCommunity --name topic_comment_ref_index --flags COLUMN_INDEX|WITH_POSITION --type CommunityTopic --source comment
```

を↓に変えてみてください。

```text
column_create --table CommunityTopic --name community_topic_ref_index --flags COLUMN_INDEX --type Community --source topic

column_create --table CommunityTopicComment --name topic_comment_ref_index --flags COLUMN_INDEX --type CommunityTopic --source comment
```

今回のケースだと2番目のインデックスを直すだけで大丈夫なんですが、1番目の方も間違ったインデックス定義なので直しておいたほうがいいです。

ポイントは語彙表（`COLUMN_INDEX`が定義されているテーブル）のキーの型と（トークナイズされた後の）カラムの値の型をあわせるというところです。（絵を描くとピンと来るんですが。。。もし、いつかGroongaの勉強会に来ることがあったら絵を書いて欲しいと言ってください。。。）

`Community.title`など`ShortText`と`Text`のカラムは語彙表として`TermCommunity`は適切（`TermCommunity`の`default_tokenizer`の`TokenBigram`は入力として`Text`, `ShortText`, `LongText`のどれかを受け取って`ShortText`のトークンに分解する。で、トークンの型である`ShortText`は`TermCommunity`のキーの方と一致している。）なのですが、`Community.topic`と`CommunityTopic.comment`の方はそれぞれ`CommunityTopic`と`CommunityTopicComment`で`ShortText`ではないので適切ではありません。

そのため、適切な語彙表にしたものが直したインデックス定義になります。`WITH_POSITION`フラグを外しているのはトークナイズしていない（`ComminityTopic`にも`ComminityTopicComment`にも`default_tokenizer`を設定していないのでトークナイズしない）のでトークンの出現位置は不必要な情報だからです。（これも図を描くとピンとくるやつです。。。）

**Comment by d-tomita-beat-co-jp** [comment]
ありがとうございます
こちらの内容でやってみます。

やはり文章だとイメージがしづらいですね(汗)
是非タイミングがあえば勉強会には参加したいですね。

**Comment by TomyGX** [comment]
ありがとうございます
こちらの内容でやってみます。

やはり文章だとイメージがしづらいですね(汗)
是非タイミングがあえば勉強会には参加したいですね。

**Comment by TomyGX** [comment]
無事目的の動作をさせることができました。
いつも本当にありがとうございます。

**Comment by kou** [comment]
よかったです！
