### ISSUE TITLE
groonga-httpd のlogファイルのオーナー権限がlogrotateの前と後で違う

### ISSUE THREAD

**Issue by jacob16bit** [groonga/groonga#358]
環境：CentOS6.6
Groonga-httpd 5.0.5

groonga-httpdの初回起動（logファイルが何もない状態）では root権限でlogファイルは作成されますが
logrotate後はgroonga権限になってしまうようです。

```
-rw-r--r-- 1 root    root       0  7月  3 17:03 2015 access.log
-rw-r----- 1 groonga groonga    0  7月  5 13:57 2015 error.log
-rw-r--r-- 1 root    root    1482  7月  3 19:16 2015 error.log-20150705
-rw-r--r-- 1 root    root       0  7月  3 17:03 2015 groonga-query.log
-rw-r----- 1 groonga groonga    0  7月  5 13:57 2015 groonga.log
-rw-r--r-- 1 root    root     516  7月  3 19:16 2015 groonga.log-20150705
```

これは `logrotate.d/groonga-httpd` の `create` の設定に `groonga`ユーザとグループを設定しているためです。
`groonga-httpd`は`root`ユーザーにて実行されるため、logファイルが書き込めない等の影響はないのですが、ちょっとこの設定だともやもやします。

## 提案
`nginx`の`logrotate`設定ファイルと比較してみたところ、nginxではオーナー権限は設定していないので、root権限で作成されています。
`groonga-httpd`の`logrotate`設定も、nginxと同じく、権限を設定しない（logファイルの権限をrootユーザーにする）ようにしてはいかがでしょうか？

**Comment by kou** [comment]
その通りだと思ったので`create ...`を削除しました！
提案ありがとうございます！

あと、ログをローテートした後に動くスクリプト部分が動いていなかったことにも気づいたので修正しました。

**Comment by jacob16bit** [comment]
修正ありがとうございます。
