### ISSUE TITLE
groonga-httpd のlogファイルのlotate後も古いlogファイルにlogが出力され続ける

### ISSUE THREAD

**Issue by jacob16bit** [groonga/groonga#362]
環境：CentOS6.6
 Groonga-httpd 5.0.5

`loglotate`ファイルは修正後のもの https://github.com/groonga/groonga/commit/b2e0650a7ce93de3b869f592add8877f7a4849ff を使用しています。

lotate直後はこんな感じです。
```
-rw-r--r-- 1 root    root        0  7月  8 17:30 2015 access.log
-rw-r--r-- 1 root    root    25972  7月  8 17:31 2015 access.log-20150708
rw-r--r-- 1 root    root        0  7月  8 17:30 2015 groonga-query.log
-rw-r--r-- 1 root    root    11448  7月  8 17:31 2015 groonga-query.log-20150708
```

その後、`groonga-httpd`にアクセスすると
```
-rw-r--r-- 1 root    root        0  7月  8 17:30 2015 access.log
-rw-r--r-- 1 root    root    26215  7月  8 17:31 2015 access.log-20150708
rw-r--r-- 1 root    root        0  7月  8 17:30 2015 groonga-query.log
-rw-r--r-- 1 root    root    11571  7月  8 17:31 2015 groonga-query.log-20150708
```
こんな感じで古いファイルに書き続けられるようです。

`nginx`の`logrotate`と比較して、試しに`groonga-httpd` へ `USR1`を送ってみたところ、
```bash
/bin/kill -USR1 `ps -ef | egrep "^root.*groonga-httpd" | grep -v grep | awk '{print $2}'` 2>/dev/null || :
```
```
-rw-r--r-- 1 groonga root     1008  7月  8 18:05 2015 access.log
-rw-r--r-- 1 root    root    30661  7月  8 17:33 2015 access.log-20150708
rw-r--r-- 1 groonga root      457  7月  8 18:05 2015 groonga-query.log
-rw-r--r-- 1 root    root    14499  7月  8 17:33 2015 groonga-query.log-20150708
```
このような感じで新しいファイルにlogを書き込むことができました。
ソースコードを追いかけてないため、USR1を送って大丈夫かどうかは検証していません。あと、curl "http://127.0.0.1:10041/d/log_reopen" の意味は追いかけずに検証しています。スミマセン。

## 提案
下記3つの中で、どれかが実現できれば問題は解消されると思います。(2と3は基本同じですね…)

1. `curl "http://127.0.0.1:10041/d/log_reopen"` で新しいlogファイルを見るようにする。
2. `groonga-httpd`のinitスクリプト中の start に `PID` ファイルを作るようにして、nginxと同じようにPIDファイルからUSR1を送るようにする。
例
```bash
/usr/bin/curl --silent --output /dev/null \
  "http://127.0.0.1:10041/d/log_reopen"
/bin/kill -USR1 $(cat /var/run/nginx.pid 2>/dev/null) 2>/dev/null || :
```
3. logrotateスクリプト内でpidを判定してしまう
例
```bash
/usr/bin/curl --silent --output /dev/null \
  "http://127.0.0.1:10041/d/log_reopen"
/bin/kill -USR1 `ps -ef | egrep "^root.*groonga-httpd" | grep -v grep | awk '{print $2}'` 2>/dev/null || :
```

以上です。

**Comment by kou** [comment]
あぁ、nginxが出力しているaccess.logもあるので、`log_reopen`よりもシグナルのほうがよさそうですねぇ。
来週動作を確認します。。。

**Comment by jacob16bit** [comment]
すみません。よろしくお願いします。

**Comment by kou** [comment]
遅くなりましたが確認しました！
groonga-httpdもPIDファイルを作っているのでそれを使ってシグナルを送るようにしました。nginxの設定ファイルではエラーを無視していますが、groonga-httpdでは無視していません。必要なときだけシグナルを送るようにしているのでエラーになったらそれは無視するべきものではなく問題を調べないといけないときだからです。

ログをローテートしていくと`groonga`ユーザー権限になりますね。特に、設定をする必要はなかったんですね。

**Comment by jacob16bit** [comment]
動作確認しました。
groonga-httpdのpidあったんですね。確認せずに思いっきり力技でやり過ぎてました。

いつも対応ありがとうございます！

**Comment by kou** [comment]
確認ありがとうございます！
今月もいいリリースを向かえられそうです！
