### ISSUE TITLE
VC++2013 complains undefined symbols in 20150728 nightly

### ISSUE THREAD

**Issue by cosmo0920** [groonga/groonga#366]
```log
(Link ターゲット) -> 

  windows_event_logger.obj : error LNK2019: 未解決の外部シンボル _EventWriteString が関数 _windows_event_logger_log で参照されました。 [C:\jw\workspace\dmbvc2013\powershell\work\build-vc2013-zip-32\storage\mroonga\vendor\groonga\lib\libgroonga.vcxproj]

  windows_event_logger.obj : error LNK2019: 未解決の外部シンボル _EventUnregister が関数 _windows_event_logger_fin で参照されました。 [C:\jw\workspace\dmbvc2013\powershell\work\build-vc2013-zip-32\storage\mroonga\vendor\groonga\lib\libgroonga.vcxproj]

  windows_event_logger.obj : error LNK2019: 未解決の外部シンボル _EventRegister が関数 _grn_windows_event_logger_set で参照されました。 [C:\jw\workspace\dmbvc2013\powershell\work\build-vc2013-zip-32\storage\mroonga\vendor\groonga\lib\libgroonga.vcxproj]

  C:\jw\workspace\dmbvc2013\powershell\work\build-vc2013-zip-32\storage\mroonga\vendor\groonga\lib\RelWithDebInfo\groonga.dll : fatal error LNK1120: 3 件の未解決の外部参照 [C:\jw\workspace\dmbvc2013\powershell\work\build-vc2013-zip-32\storage\mroonga\vendor\groonga\lib\libgroonga.vcxproj]
```

Complete build log is here: https://dl.dropboxusercontent.com/u/36753409/MrnBuildWindows/Mroonga-20150728-nightly-build.log

**Comment by cosmo0920** [comment]
調べたところ、Windows7+Visual Studio 2013 Express + Windows SDK 8.1環境でビルドが失敗する理由は、 `WINVER` をVisual Studio環境向けに指定していないのが原因でした。
また、EventWriteや　EventRegister、 EventUnregister はVista以降で使えるAPIのため、`<eventprov.h>` 内で `#if (WINVER >= _WIN32_WINNT_VISTA)` で囲われてしまっているため、無効になってしまっているようです。

Groongaのgrn.hへ、

```diff
#ifdef WIN32

+# if !defined(WINVER)
+#  define WINVER 0x0600
+# endif
# if defined(__GNUC__) && !defined(WINVER)
#  include <w32api.h>
#  define WINVER WindowsVista
```

を加えるとビルドに成功しました。
が、もう少し良い方法はありそうですね。。
`grn.h`では`__GNUC__` が定義されていないコンパイラを用いる時に`WINVER` が定義されていないように見えます。

**Comment by cosmo0920** [comment]
さすがに定数決め打ちはどうにかしたいと考えた結果、`<windows.h>`のさらに奥深くで`_WIN32_WINNT_XXX` という定数が定義されていることが分かった https://msdn.microsoft.com/ja-jp/library/windows/desktop/aa383745%28v=vs.85%29.aspx ので、

```diff
--- .\lib\grn.h.orig	2015-08-04 23:55:32 +0900
+++ .\lib\grn.h	2015-08-04 23:42:50 +0900
@@ -70,6 +70,9 @@
 #  include <w32api.h>
 #  define WINVER WindowsVista
 # endif /* defined(__GNUC__) && !defined(WINVER) */
+# if defined(_MSC_VER) && !defined(WINVER)
+#  define WINVER _WIN32_WINNT_VISTA
+# endif /* defined(_MSC_VER) && !defined(WINVER) */
 
 # include <basetsd.h>
 # include <process.h>
```

このパッチに行きつきました。

**Comment by kou** [comment]
AppVeyorでは問題がおきていない理由はわかりますか？ https://ci.appveyor.com/project/groonga/groonga

理由もわからない一時的な対処療法はできれば入れたくないんですけど。。。

**Comment by cosmo0920** [comment]
GroongaではなくMroongaでのビルド時に起きていた問題です。
なのでGroonga単体では起きません。
MroongaのAppVeyorのビルドは成功してはいますが、
https://ci.appveyor.com/project/groonga/mroonga/build/546#L8718

↓のような警告が出ています。
```log
C:\projects\mariadb-10.0.20\storage\mroonga\vendor\groonga\lib\windows_event_logger.c(113): warning C4013: 'EventWrite' undefined; assuming extern returning int [C:\projects\mariadb-10.0.20\storage\mroonga\vendor\groonga\lib\libgroonga.vcxproj]
```

**Comment by cosmo0920** [comment]
試しに https://github.com/mroonga/mroonga/commit/ef3160080dbdbbede66566df17d3db91c503bd48 をコミットしてAppVeyorを動かすと、 確かに問題が再現します。 https://ci.appveyor.com/project/groonga/mroonga/build/547/job/56bpoe8hssh7rhqv#L4189
これは、

```
% ag WIN32_WINNT
cmake/os/Windows.cmake
54:ADD_DEFINITIONS("-D_WIN32_WINNT=0x0501")
```

MariaDB側のcmakeでWIN32_WINNT=0x0501 (= Windows XP) とされている事が原因じゃないかと疑っています。

**Comment by kou** [comment]
なるほど。それが原因かどうか確かめてもらえませんか？原因がわかれば適切な対応を検討できます。

**Comment by cosmo0920** [comment]
原因は `<sdkddkver.h>` の

```c
#ifndef WINVER
#ifdef _WIN32_WINNT
// set WINVER based on _WIN32_WINNT
#define WINVER          _WIN32_WINNT
#else
#define WINVER          0x0603
#endif
#endif
```

のマクロが原因です。また、先のコメント https://github.com/groonga/groonga/issues/366#issuecomment-128433805 と相まって、`WINVER` が定義されていないときは`WINVER`を`_WIN32_WINNT`の値を使うようになっており、これにより`WIN32_WINNT=0x0501 (= Windows XP)` として認識されていたようです。

**Comment by kou** [comment]
ソースからの検証ありがとうございます。実際に動かしての確認もしてもらえませんか？
MariaDBの該当コードを削除するとビルドが通るようになるかどうかで確認できると思います。

**Comment by kou** [comment]
これは違う人にお願いしたほうがよいでしょうか？

**Comment by cosmo0920** [comment]
違う人にお願いしたいです、すみません…。

**Comment by kou** [comment]
わかりました。
もうやらないときは放置ではなくてそう言ってもらえると違うアクションを起こせるので助かります。

**Comment by cosmo0920** [comment]
次から心がけるようにします。

**Comment by kou** [comment]
ありがとうございます。

**Comment by cosmo0920** [comment]
すみません、MroongaでGroongaの中で'FILE_SET_SPARSE_BUFFER'がundefined identifierになる問題 https://ci.appveyor.com/project/groonga/mroonga/build/565/job/lo948dybscc5gwrb#L6478 が起きているようなのですが、これはまた別にissueを立てて取り扱った方が良いでしょうか？

**Comment by kou** [comment]
調査できなそうならなにもしなくて大丈夫ですよ。
たぶん、これと根は同じなので。

**Comment by cosmo0920** [comment]
わかりました！

**Comment by kou** [comment]
https://github.com/groonga/groonga/commit/d9e4fa932c052a716c7ec76e6cc902f40d945d98
で修正しました。

MariaDBが`WIN32_LEAN_AND_MEAN`を定義していて、`WIN32_LEAN_AND_MEAN`が定義されていると`#include <windows.h>`で読み込まれなくなるヘッダーがでてきて、定義が足りなくなってエラーということでした。

**Comment by cosmo0920** [comment]
ありがとうございました！
