### ISSUE TITLE
TODO does not yet.

### ISSUE THREAD

**Issue by redfigure** [groonga/groonga#367]
https://github.com/groonga/groonga/blob/master/doc/source/conf.py#L279

looks like closed.
there is something reason?

Original URL is [Bitbucket](https://bitbucket.org/birkenfeld/sphinx/issue/1426/gettext-builder-is-very-slow-during-read).
Moved to [GitHub](https://github.com/sphinx-doc/sphinx/issues/1426).

**Comment by kou** [comment]
Sorry for missing it.
It's the reason why we don't remove it that we don't watch it. Now, we can remove it.

Could you create a pull request that removes it?

**Comment by redfigure** [comment]
Okey Dokey :+1:
wait a few days.

**Comment by kenhys** [comment]
This issue is resolved. Thanks!
