### ISSUE TITLE
groonga ドキュメントの簡単な修正方法(もしあれば)

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga#377]
* [OS XでGroongaのドキュメントにコントリビュートする方法](http://qiita.com/tamano/items/7cc81f96699417677994)

上記を参考にいくつかドキュメントを修正してPRしようと思っているところがあるのですが、
私のマシンが非力で、autogen.shをするとマシンが重くなりすぎてなんにも動かなくて
仕事にならないので、その先に進めずにいます。

簡単にドキュメント部分だけ修正して確認する方法があれば教えて下さい。
難しければ、夜中にでもautogenを動かしっぱなしにして見ます。

よろしくお願いします。

```
./autogen.sh 
Submodule path 'vendor/mruby-source': checked out '1c2fc94c207ab4d4a43d701e7a784fddd3328cad'
```
ここでCPUが100%になって、マシンが動かなくなってしまいます。

**Comment by kou** [comment]
ありがとうございます！とても助かります！
https://github.com/groonga/groonga/tree/master/doc/source 以下にドキュメントのソース（英語）があるのですが、それをGitHub上で編集して（Webブラウザー上でファイルを閲覧するページに行くとファイルの内容の右上のところに「Raw」「Blame」「Histroy」というボタンが並んでいてそれの右側にある鉛筆のアイコンをクリックすると編集できます）Pull Requestにしてもらえればそれで大丈夫です！

多少マークアップがおかしくなっていたりしてもこちらで調整するので大丈夫です！

**Comment by hiroyuki-sato** [comment]
ありがとうございます。

上記の方法は、groonga/doc/sourceの中の文字だけ直してsphinxで確認しないで、PRするのと一緒ですね。こっちの方がやりやすいので、簡単なタイポなどを見つけたら修正してPRします。

**Comment by kou** [comment]
はい、そうです。

よろしくお願いします！
