### ISSUE TITLE
Create Table web admin does not set key

### ISSUE THREAD

**Issue by leerlemoniii** [groonga/groonga#383]
When trying to create a new hash table in the web interface,  the Key type field seems to be ignored.  it creates the table, but does not create the _key field.   creating from command line or via web interface using /d/table_create?name=Site3&flags=TABLE_HASH_KEY&key_type=ShortText works as expected.

**Comment by leerlemoniii** [comment]
forgot to say this was using the windows 64bit binary.

**Comment by kou** [comment]
Could you give us a screenshot for your input?
I couldn't reproduce with the following input:

![create-table](https://cloud.githubusercontent.com/assets/27350/9548403/402fcdc6-4ddb-11e5-8f24-407cf5f0e9dd.png)
