### ISSUE TITLE
doc ja: statusコマンド

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga#399]
気がついたのでメモです。

http://groonga.org/ja/docs/reference/commands/status.html

> 開始時間
>
> groongaプロセスが起動した時刻のtvsec値を返します。
>
> 稼動時間
> 
> groongaプロセスが起動してから経過した秒数を返します。

* 開始時間は、starttimeでしょうか？、この場合「開始時間」はstarttimeのままの方が良いように思います。
* tvsecと書くよりはなにか別の表現の方がよいような、「協定世界時 (UTC) での1970年1月1日午前0時0分0秒の時刻からの形式的な経過秒数」..ちょっと長いですね。
* 「稼働時間」は、上のサンプルのどれに対応するのかわかりませんでした。
* command_versionなどの説明がないようですね。(追加してほしいと言っているわけではないです)

**Comment by kou** [comment]
これ、だいぶ前に書かれたやつなんですよね。

全面的に書き直しました。
http://groonga.org/ja/docs/reference/commands/status.html

**Comment by hiroyuki-sato** [comment]
ありがとうございます。わかりやすくなりました。
