### ISSUE TITLE
doc: the value of ``_id`` is equal to 1. 

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga#403]
http://groonga.org/ja/docs/tutorial/search.html

> 上記クエリの詳細をみてみましょう。 filter パラメータではこのように条件が指定されています:
```
_id <= 1
```
> このケースでは、 _id の値が1であるという条件に合致するレコードを返します。

これは以下条件(ですよね？)なので、
ケースでは、 _id の値が1以下とするのが正しいように思います。

tutorial.poの英語も、equal to 1となっており例か原文のどちらかを直した方が良いように思います。

```
msgid ""
"In this case, this query returns the records which meets the condition that "
"the value of ``_id`` is equal to 1."
msgstr ""
"このケースでは、 ``_id`` の値が1であるという条件に合致するレコードを返しま"
"す。"
```

**Comment by kou** [comment]
報告ありがとうございます！
文章の方を修正しました！

**Comment by hiroyuki-sato** [comment]
ありがとうございまいた。
