### ISSUE TITLE
grn_ts: evaluate the sorting performance

### ISSUE THREAD

**Issue by s-yata** [groonga/groonga#433]
#### Description

The sorting performance of `grn_ts` should be evaluated.

**Comment by s-yata** [comment]
I've tested the following commands for 10M rows.

```
select Table --sortby 'XXX' --limit 0 --output_columns '_id'
select Table --filter '?true' --sortby 'XXX' --limit 0 --output_columns '_id'
```

|             sortby| Groonga (s)|  grn_ts (s)|
|------------------:|-----------:|-----------:|
|`Int_0`            |       0.501|       0.235|
|`Int_0, Int_1`     |       0.663|       0.234|
|`Float_0`          |       0.638|       0.191|
|`Float_0, Float_1` |       0.624|       0.191|
|`Text_0`           |       0.546|       0.758|
|`Text_0, Text_1`   |       0.950|       0.752|

The sorting performance of grn_ts seems OK except for Text.
It should be improved ( #435 ).

**Comment by s-yata** [comment]
Interfaces to read values from `grn_ja` have been improved ( #441 ).

- Text_0: 1-4 bytes
- Text_1: 4-8 bytes
- Text_2: 8-12 bytes

|   sortby| Groonga (s)|  grn_ts (s)|
|--------:|-----------:|-----------:|
| `Text_0`|       0.586|       0.555|
| `Text_1`|       0.707|       0.578|
| `Text_2`|       0.921|       0.832|

**Comment by s-yata** [comment]
See also #435

**Comment by kou** [comment]
grn_ts was abandoned. We may use Apache Arrow based query engine instead.
