### ISSUE TITLE
grn_ts: improve Text based sorting

### ISSUE THREAD

**Issue by s-yata** [groonga/groonga#435]
#### Description

There are several ideas to improve Text based sorting.
- [x] Quicksort.
- [ ] 8-bit multi-key quicksort.
- [ ] 64-bit multi-key quicksort.

**Comment by s-yata** [comment]
`grn_ts_ja_get_value()` seems to take long time.
It should be improved before improving the sorting implementation.

**Comment by s-yata** [comment]
#### Comparison of quicksort and 8-bit multi-key quicksort

Multi-key quicksort (MKQsort) is faster than quicksort (Qsort).

- #rows: 10,000,000
 - Text_0: 1-4 bytes ('A'-'Z')
 - Text_1: 4-8 bytes ('A'-'Z')
 - Text_2: 8-12 bytes ('A'-'Z')

|       |   Qsort| MKQsort|
|------:|-------:|-------:|
| Text_0|  0.527s|  0.415s|
| Text_1|  0.511s|  0.464s|
| Text_2|  0.718s|  0.561s|

- #rows: 10,000,000
 - Text_0: 1-4 bytes ('A'-'D')
 - Text_1: 4-8 bytes ('A'-'D')
 - Text_2: 8-12 bytes ('A'-'D')

|       |   Qsort| MKQsort|
|------:|-------:|-------:|
| Text_0|  0.536s|  0.477s|
| Text_1|  0.583s|  0.521s|
| Text_2|  0.629s|  0.516s|

**Comment by kou** [comment]
grn_ts was abandoned. We may use Apache Arrow based query engine instead.
