### ISSUE TITLE
groonga.exe Can't input UTF-8 Japanese String on Windows environment.

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga#439]
Windows上でgroonga.exeをUTF-8の環境で使うと、日本語入力ができない。
日本語入力をすると、groongaのコマンドが終了してしまう。
- OS: Windows7
- Groonga: 5.0.9

```
> load --table Site
> [{"_key":"http://example.org/","title":"日本語1"},{"_key":"http://example.net/","title":"日本語2"},{"_key":"http://example.com/","title":"日本語3"}]

C:\Program Files\Groonga\bin>
```
- 期待する動作: groongaのコマンド(load)が実行される。
- 現在の動作: groonga.exeがすぐに終了してしまう。

再現方法

1, フォントの設定

[コマンドプロンプト起動時、自動的に文字コードをUTF-8にして日本語もちゃんと表示できるようにする方法](http://qiita.com/yui/items/86a455f948a3e1c0ef97)

2, コマンドプロンプト起動

3, コードページ変更

```
> chcp65001
Active code page: 65001
```

3, groonga起動

```
C:\Program Files\Groonga\bin>groonga.exe -n test2.db
```

4, テーブル作成

```
> table_create --name Site --flags TABLE_HASH_KEY --key_type ShortText
[[0,1448852689.869,0.0],true]
```

5, カラム作成

```
> column_create --table Site --name title --type ShortText
[[0,1448852701.622,0.0],true]
```

6, データロード

```
> load --table Site
> [{"_key":"http://example.org/","title":"日本語1"},{"_key":"http://example.net/","title":"日本語2"},{"_key":"http://example.com/","title":"日本語3"}]

C:\Program Files\Groonga\bin>
```

**Comment by kou** [comment]
3の状態で何かプログラムを実行したとき（たとえば`irb`）、入力した日本語テキストのエンコーディングが何になっているか確認してもらえないでしょうか？UTF-8なのでしょうか？CP932なのでしょうか？

```
irb> "日本語".encoding
```

でわかるのかしら。

```
irb> "日本語".valid_encoding?
```

もやらないとダメかしら。

**Comment by kou** [comment]
もし、コマンドプロンプトで入力したテキストがCP932ならUTF-8のデータを入力することは諦めた方がいいです。Groongaはエンコーディングを変換する機能を持っていないので。

前に、 @myokoym さんがGTK+ベースでGroongaのDBをさわるやつを作っていた気がしますが、そういう感じでコマンドプロンプトじゃないなにかでコマンドを使えるようにするのがいいんじゃないかなぁと思います。

**Comment by myokoym** [comment]
> 前に、 @myokoym さんがGTK+ベースでGroongaのDBをさわるやつを作っていた気がしますが、

これですね: https://github.com/myokoym/groonga-database-viewer-gtk

紹介記事もあります: [Groongaの既存のデータベースの中を見る3つの方法 - Qiita](http://qiita.com/myokoym/items/38a5f7126f144a0e8649)

**Comment by hiroyuki-sato** [comment]
そもそもirbで日本語入力ができないという別の問題が生じました。orz

```
irb(main):001:0> "".encoding
```

なにがなんでも、Windowsでgroonga.exeを使いたいという人が出てくるのを待ちましょう。

**Comment by kou** [comment]
> これですね: https://github.com/myokoym/groonga-database-viewer-gtk

そうそう。

コマンドプロンプトで日本語入力するのは諦めた方がよさそうなので別のUIを用意する方がいいんじゃないかなぁと思います。

**Comment by cosmo0920** [comment]
ちなみに・・・PowerShellではirbで日本語入力は可能です。

```powershell
PS C:\Users\hhatake> irb
irb(main):001:0> "日本語".encoding
=> #<Encoding:Windows-31J>
```

でもWindows-31Jみたいですね・・・。

**Comment by hiroyuki-sato** [comment]
@cosmo0920 さん
ありがとうございます。なぜかPSでも私の環境だと日本語がうまく入力できませんでした。
Windows-31Jですか...ますます、groonga.exeを使うのは難しそうですね。
別のUIを用意するのが良いですね。

**Comment by cosmo0920** [comment]
もしかするとIMEによっては入力出来ない事もありそうですね。こちらの環境ではWindows 7 32bitでMicrosoft IMEです（Officeを入れるとついてくるMicrosoft Office IMEは使っていないです）。

**Comment by hiroyuki-sato** [comment]
私も同じ環境です(と思います。OfficeのIMEがよくわからない..)
違いがわかりました。私PSで、chcp 65001したあとirbを起動しています。

初期状態だとコードページは932で日本語は入力できました。

、Windows-3.1J

## chcp 65001の場合

* PS起動
* ``chcp 65001``
* irb
* 日本語入力 -> NG

## chcp 932

* PS起動
* ``chcp`` -> 932
* irb
* 日本語入力 -> OK

**Comment by hiroyuki-sato** [comment]
ひらめいた!!、Jupyter でgroongaが使えればいいんだ!!
..と思いましたが、WindowsでJypterを動かすのも敷居が高そうですね。でもJuypterのgroongaプラグインほしいかも、ということでアイディアだけ残しておきます。

http://reiji1020.hatenablog.com/entry/2015/06/21/154223

**Comment by cosmo0920** [comment]
たぶんWindowsで動かすには.NETやJVMで動かせるものの方が敷居が低くなって良いんじゃないかと思います。特に.NET製であればほぼどのWindowsマシンにも入っているので導入につまずくことは無くなると思います。。。と、アイディアだけ書き記しておきます。

**Comment by myokoym** [comment]
Rubyでツールを作ってみました: https://github.com/myokoym/grnlip

紹介記事: [UTF-8なDBに対してShift_JIS（cmd.exe）で全文検索する3つの方法](http://qiita.com/myokoym/items/c7ea4c83dad080d8ebbe)

**Comment by hiroyuki-sato** [comment]
お！、いいですね。ぜひ質問者の方にもお知らせください。

**Comment by kou** [comment]
@hiroyuki-sato 質問者の方にも伝えてくれてありがとうございます！とてもすばらしいことだと思います！ありがとうございます！

**Comment by hiroyuki-sato** [comment]
天の声が聞こえたので補足しました。😀

**Comment by myokoym** [comment]
ありがとうございます。助かりました。

**Comment by cosmo0920** [comment]
@myokoym さんのツールもgroonga.orgの関連プロジェクトに記載するのが良いんじゃないかと思います。
