### ISSUE TITLE
select: Support dynamic columns

### ISSUE THREAD

**Issue by kou** [groonga/groonga#461]
The current Groonga can't use computed value for `output_columns`, `drilldown` and `sortby`.

If Groonga supports dynamic columns, we can use computed value for them. Because users just put computed values to dynamic columns. Dynamic columns can be implemented by columns for temporary table (result table is a temporary table).

There is another feature provided by dynamic columns. Naming computed value in `output_columns`. For example, `--output_columns 'snippet_html(column1), snippet_html(column2)'` uses `snippet_html` for both computed values for now. If Groonga supports dynamic columns, we can use another label for each computed value.

API idea:

``` text
select \
  --column[name].stage filtered \
  --column[name].type ShortText \
  --column[name].flags COLUMN_SCALAR \
  --column[name].value 'column1 + column2'
```

Available `stage` values:
- `initial`: Created a column at the first. It can be used in `query`, `filter`, `drilldown`, `sortby` and `output_columns`.
- `filtered`: Created a column after `query` and `filter` are evaluated. It can be used in `drilldown`, `sortby` and `output_columns`.
- `output`: Created a column after `sortby`. The value of column should only evaluated only for `limit` records.

**Comment by kou** [comment]
`filtered` is implemented at master.

**Comment by s-yata** [comment]
Dynamic columns seem to be already supported.
It uses  `--columns[name].xxx` instead of `--column[name].xxx`.
