### ISSUE TITLE
Incorrect order from admin page

### ISSUE THREAD

**Issue by tricknotes** [groonga/groonga#476]
I specified `_key` as sort key, but it seems not sorted correctly.

http://packages.groonga.org:10041/#/tables/Sizes/search?match_columns=&output_columns=_id,_key,logs_index&offset=0&limit=10&sortby=-_key&drilldown=&drilldown_sortby=-_nsubrecs&filter=
![2016-02-13 18 41 50](https://cloud.githubusercontent.com/assets/290782/13027001/81814f5e-d281-11e5-95ee-66e248c58ca9.png)

**Comment by kou** [comment]
Thanks for your report!
I've fixed it.
