### ISSUE TITLE
Split large posting chunks in static indexing

### ISSUE THREAD

**Issue by s-yata** [groonga/groonga#479]
#### Description

The current Groonga creates one chunk for each term in static indexing.
The advantage and drawback of this "one-chunk-per-term" approach are as follows:

- Advantage: it can compress postings a little bit better.
- Drawback: it can skip non-target chunks in searching.

The goal of this issue is to improve the search performance by splitting large chunks into small chunks.

**Comment by s-yata** [comment]
It seems to be difficult to complete implementation and **tests** before the next release...

**Comment by kou** [comment]
OK. We'll include it in the next next release.

**Comment by s-yata** [comment]
I've implemented it but it takes 20-30% more time than the old implementation.
Now I'm searching for a cause.

**Comment by kou** [comment]
`GRN_II_CURSOR_SET_MIN_ENABLE=yes` environment variable will be useful to confirm split chunks increase search performance.

**Comment by s-yata** [comment]
Thank you. I'll evaluate it!

**Comment by s-yata** [comment]
I've compared the default and `GRN_II_CURSOR_SET_MIN_ENABLE=yes` for split chunks.

- Flags
 - Index table: `--default_tokenizer TokenMecab` `--normalizer NormalizerAuto`
 - Index column: `COLUMN_INDEX|WITH_SECTION|WITH_POSITION`
- Data
 - Columns: `body0`, `body1` and `body2` (Text)
 - No. records: 6,635,021
 - Total Text length: 2GiB

I executed select commands for comparison as follows:

```
$ groonga /tmp/groonga/db
> select page --match_columns 'body0,body1,body2' --query 'Query' --limit 0 --cache no

$ GRN_II_CURSOR_SET_MIN_ENABLE=yes groonga /tmp/groonga/db
> select page --match_columns 'body0,body1,body2' --query 'Query' --limit 0 --cache no
```

I executed each select command more than 10 times and selected the best result. The following table shows the results.

|Query         |  No skip|With skip|
|--------------|--------:|--------:|
|焼肉の        |   0.268s|   0.068s|
|今日は晴れです|   0.159s|   0.031s|

Then, the following table shows the results for different chunk size.

|Query           | 4kB chunks|64kB chunks|
|----------------|----------:|----------:|
|今日は晴れです  |     0.006s|     0.024s|
|今日は肉の日です|     0.008s|     0.027s|
|焼肉の          |     0.012s|     0.068s|

The above results tell us that the combination of split chunks and `GRN_II_CURSOR_SET_MIN_ENABLE=yes` can considerably improve the phrase search performance.

**Comment by kou** [comment]
Wow! It's a great improvement!

**Comment by s-yata** [comment]
A blog article (Japanese) has been published.

- Groonga - 静的索引によるフレーズ検索の高速化
 - http://groonga.org/ja/blog/2016/03/28/chunk-split.html

**Comment by s-yata** [comment]
Improvements will be discussed in other issues, such as #509 and #516.
