### ISSUE TITLE
No snippet_html is output

### ISSUE THREAD

**Issue by KitaitiMakoto** [groonga/groonga#490]
Hi,

My Groonga database doesn't output `snippet_html` against query 
https://search.apehuci.kitaitimakoto.net/d/select?table=Apehuci&output_columns=title,snippet_html%28title%29&query=title:@Groonga&command_version=2

Groonga status is:

```
[
  [
    0,
    1456325677.67137,
    0.000119924545288086
  ],
  {
    "alloc_count": 25273,
    "starttime": 1454993543,
    "start_time": 1454993543,
    "uptime": 1332134,
    "version": "5.1.2",
    "n_queries": 0,
    "cache_hit_rate": 0.0,
    "command_version": 1,
    "default_command_version": 1,
    "max_command_version": 2
  }
]
```

Database schema is here: https://github.com/KitaitiMakoto/apehuci/blob/fbb8bea5c8f6de2e19004f2c865c1d6cbe35e25c/Rakefile#L15-L34

Any idea? Please tell me if there are information I can provide.

Thanks.

**Comment by s-yata** [comment]
Hmm, I could not reproduce this problem on my environment.

```
$ groonga -n /tmp/groonga/db
table_create --name Apehuci --flags 'TABLE_HASH_KEY' --key_type ShortText
column_create --table Apehuci --name 'title' --type ShortText
column_create --table Apehuci --name 'tags' --type ShortText --flags 'COLUMN_VECTOR'
column_create --table Apehuci --name 'content' --type Text

table_create --name ApehuciTerms --flags 'TABLE_PAT_KEY' --key_type ShortText --default_tokenizer TokenMecab --normalizer NormalizerAuto
column_create --table ApehuciTerms --name 'title_index' --flags 'COLUMN_INDEX|WITH_POSITION' --type Apehuci --source 'title'
column_create --table ApehuciTerms --name 'tags_index' --flags 'COLUMN_INDEX|WITH_POSITION' --type Apehuci --source 'tags'
column_create --table ApehuciTerms --name 'content_index' --flags 'COLUMN_INDEX|WITH_POSITION' --type Apehuci --source 'content'

select --table Apehuci --output_columns 'title,snippet_html(title)' --query 'title:@Groonga' --command_version 2
# [[0,1456371841.36053,0.00573182106018066],[[[0],[["title","ShortText"],["snippet_html","null"]]]]]
```

`grooonga-httpd` returned the same result against `http://localhost:10041/d/select?table=Apehuci&output_columns=title,snippet_html%28title%29&query=title:@Groonga&command_version=2`.

```
[[0,1456371943.93452,0.00217032432556152],[[[0],[["title","ShortText"],["snippet_html","null"]]]]]
```

The status is:

```
[
  [0,1456372114.35414,6.55651092529297e-05],
  {
    "alloc_count":251,
    "starttime":1456372089,
    "start_time":1456372089,
    "uptime":25,
    "version":"5.1.2-241-gb95e409",
    "n_queries":1,
    "cache_hit_rate":0.0,
    "command_version":1,
    "default_command_version":1,
    "max_command_version":2
  }
]
```

**Comment by kou** [comment]
@KitaitiMakoto Could you publish https://search.apehuci.kitaitimakoto.net/d/dump to @s-yata ? If you provide dump data to @s-yata , @s-yata will fix it. :-)

**Comment by KitaitiMakoto** [comment]
@s-yata @kou 
I'm so sorry. I made a mistake. My query lacks `command_version`.

The actual query on my diary is: https://search.apehuci.kitaitimakoto.net/d/select?table=Apehuci&match_columns=title%20*%202%2Ctags%20*%202%2Ccontent&output_columns=_key%2Ctitle%2Ctags%2Csnippet_html%28content%29%2C_score&sortby=-_score&&query=Groonga
and just appending `&command_version=2` to the URI, we can see `snippet_html`.

**Comment by s-yata** [comment]
We are happy to hear that your problem has been fixed. :-)

**Comment by kou** [comment]
TODO: We need to put `command_version` value and `output_pretty` value to cache key.

**Comment by kou** [comment]
I've added `command_version` value and `output_pretty` value to cache key for `select`.

**Comment by KitaitiMakoto** [comment]
Great!
