### ISSUE TITLE
grn_idが指すオブジェクトの一貫性が保証されない

### ISSUE THREAD

**Issue by genki** [groonga/groonga#500]
grn_table_getなどで取得したgrn_idに対してgrn_obj_set_valueなどで値の更新を行う場合、その僅かな時間の間に別のプロセスやスレッドから対象となるオブジェクトの削除とgrn_idの再利用が行われた時、もともと更新しようとしていたオブジェクトとは別のオブジェクトを更新してしまう可能性がある。

そこで、以下のようにgrn_idと共に操作対象のテーブルの内部状態を取得し、Compare And Swap を行うことでidが示すオブジェクトが変化している可能性がある場合、更新処理を失敗させる手段があると良いと思われる。

```
grn_state state;
while(1){
    grn_id id = grn_table_get_with_state(ctx, table, key, key_size, &state);
    if(grn_obj_cas_value(ctx, column, id, state, value, flags)) break;
}
```

stateはオブジェクトの削除や追加操作のたびにインクリメントされるカウンタのようなもので、プロセス間で共有される必要がある。

**Comment by genki** [comment]
grn_obj_cas_valueはほとんどの場合で成功するため、パフォーマンスの劣化は認識できないレベルだと思われる。また、stateは共有メモリ上に確保すれば良い。

**Comment by s-yata** [comment]
更新については，より上のレベルで排他制御することが前提になっているため，このレベルで一貫性を保証する必要はないということだったかと思います．

また， state を追加した場合，オブジェクトと state を同時に更新することはできないため，オブジェクトと state の一貫性に関する問題が出てくると思います．

それから，ひとつのオブジェクトを更新したとき，フックによって別のオブジェクトも更新されるケースがあります． state を割り当てる範囲によってはデッドロックが発生する可能性も想定しなければならないと思います．

**Comment by genki** [comment]
例えば rroonga の rb_grn_table_key_support_set_value_by_key の実装を見てみると、
現状排他制御が行われていないように見受けられます。
https://github.com/ranguba/rroonga/blob/70ffee9d8d8906d3c202e4016a0d451fb24a97f9/ext/groonga/rb-grn-table-key-support.c#L675
grn_idの取得から値の更新までの間に割り込みが発生する確率は非常に低いので、ほとんど問題になっていないとは思われますが、稀ではあっても意図せずにデータが破壊される可能性があるのは問題ではないかと思います。
値の更新のたびにlockを行うのは更新系のパフォーマンス劣化の影響が大きいと思われるため、CASを行う手段を用意するという提案をさせていただきました。

CAS の実装のためのstateの更新は false positiveで良いので、保守的にすべての更新操作に先立って行えばよく、stateの一貫性の心配はありません。CASの呼び出し側でおかしな事をしないかぎりデッドロックが発生する可能性は無いと思います。また、擬似コードではwhile(1)と簡潔に示しましたが、実際の利用ではタイムアウトを設ける形になるかと思います。

**Comment by s-yata** [comment]
Rroonga の `rb_grn_table_key_support_set_value_by_key` についても，上位で排他制御するなり更新系がひとつしかないことを保証するなりしてくださいということだと思います．

Lock と CAS のコストについては一長一短あります．値を少し更新するだけであれば， lock と CAS のコストはあまり問題になりません．問題は大量に値を更新するときですが，まとめて 1 回の lock で済む場合もあります．そのようなケースでは，ひとつひとつ CAS をおこなうより効率的です．

オブジェクトと state の一貫性については，以下のようなことを危惧しています．

1. Process A が state を更新
2. Process B が state を参照
3. Process B が state を更新
4. Process A, B がオブジェクトを更新

実際のところ，更新同士ではリソース競合が発生するため，排他制御は必須になります．同じオブジェクトを複数のスレッド・プロセスから同時に更新しようとすると DB が壊れる可能性があります．

**Comment by kou** [comment]
`grn_id`の再利用を防ぐためにロックをしたくないなら、いっそレコードを削除しない使い方はどうですか？

テーブルのvalueに値を入れられるのでそこにそのレコードが生きているかどうかを入れておけば削除しなくても削除したように見せかけられます。

https://github.com/genki/hog で実現するならこんな感じです。

```diff
diff --git a/src/del.c b/src/del.c
index 5b599f1..6acf032 100644
--- a/src/del.c
+++ b/src/del.c
@@ -25,7 +25,15 @@ void hog_del(server_t *s, grn_ctx *ctx)
         buf = realloc(buf, len);
         receive(s->socket, buf, len);
         ntoh_buf(buf, len, type);
-        grn_table_delete(ctx, table, buf, len);
+        grn_id id = grn_table_get(ctx, table, buf, len);
+        if (id == GRN_ID_NIL) {
+          continue;
+        }
+        grn_obj alive;
+        GRN_BOOL_INIT(&alive, 0);
+        GRN_BOOL_SET(ctx, &alive, GRN_FALSE);
+        grn_obj_set_value(ctx, table, id, &alive, GRN_OBJ_SET);
+        GRN_OBJ_FIN(ctx, &alive);
     }
 cleanup:
     free(buf);
diff --git a/src/exist.c b/src/exist.c
index 6584eff..f0cb1c1 100644
--- a/src/exist.c
+++ b/src/exist.c
@@ -26,6 +26,15 @@ void hog_exist(server_t *s, grn_ctx *ctx)
         receive(s->socket, buf, len);
         ntoh_buf(buf, len, type);
         grn_id id = grn_table_get(ctx, table, buf, len);
+        if(id != GRN_ID_NIL){
+            grn_obj alive;
+            GRN_BOOL_INIT(&alive, 0);
+            grn_obj_get_value(ctx, table, id, &alive);
+            if(!GRN_BOOL_VALUE(&alive)){
+                id = GRN_ID_NIL;
+            }
+            GRN_OBJ_FIN(ctx, &alive);
+        }
         char flag = (id == GRN_ID_NIL ? 0 : 1);
         submit(s->socket, &flag, 1);
     }
diff --git a/src/get.c b/src/get.c
index befa0b9..07290d0 100644
--- a/src/get.c
+++ b/src/get.c
@@ -21,6 +21,8 @@ void hog_get(server_t *s, grn_ctx *ctx)
     nkeys = ntohl(nkeys);
     grn_obj value;
     GRN_VOID_INIT(&value);
+    grn_obj alive;
+    GRN_BOOL_INIT(&alive, 0);
     for(uint32_t i = 0; i < nkeys; ++i){
         receive(s->socket, &len, sizeof(len));
         len = ntohl(len);
@@ -29,6 +31,13 @@ void hog_get(server_t *s, grn_ctx *ctx)
         ntoh_buf(buf, len, types[0]);
         grn_id id = grn_table_get(ctx, table, buf, len);
         if(id != GRN_ID_NIL){
+            GRN_BULK_REWIND(&alive);
+            grn_obj_get_value(ctx, table, id, &alive);
+            if(!GRN_BOOL_VALUE(&alive)){
+                id = GRN_ID_NIL;
+            }
+        }
+        if(id != GRN_ID_NIL){
             GRN_BULK_REWIND(&value);
             grn_obj_get_value(ctx, col, id, &value);
             if(ctx->rc == GRN_SUCCESS){
diff --git a/src/put.c b/src/put.c
index 99948a7..ba7135c 100644
--- a/src/put.c
+++ b/src/put.c
@@ -36,6 +36,11 @@ void hog_put(server_t *s, grn_ctx *ctx)
         GRN_BULK_REWIND(&value);
         grn_bulk_write(ctx, &value, buf, len);
         grn_obj_set_value(ctx, col, id, &value, GRN_OBJ_SET);
+        grn_obj alive;
+        GRN_BOOL_INIT(&alive, 0);
+        GRN_BOOL_SET(ctx, &alive, GRN_TRUE);
+        grn_obj_set_value(ctx, table, id, &alive, GRN_OBJ_SET);
+        GRN_OBJ_FIN(ctx, &alive);
     }
     GRN_OBJ_FIN(ctx, &value);
 cleanup:
```

`test/test.rb` で使う用のカラムは以下で定義できます。`Bool`が入る分だけvalueのスペースを確保しています。

```text
table_create Foo TABLE_HASH_KEY ShortText Bool
column_create Foo bar COLUMN_SCALAR Text
```

**Comment by genki** [comment]
@kou 論理削除するという話だと思いますが、大量のデータを長期間扱う想定なのと、
32 bit int maxのレコード数上限が厳しいので、削除できないのは辛いですね。
それから、ロックしたいわけではなく、ロックをせず（lock free）に一貫性を担保する
手段を提供するのがCASを利用する狙いです。

@s-yata Compare And Swapのコストは比較演算数回分だけなので、
大量のデータを更新する場合でも無視できます。
懸念されているケースを以下のように細かく解析しますと、
問題が発生しない事がわかると思います。

1. Process A が state を 1 に更新
1. Process B が state 1 を参照
1. Process B が state を 2 に更新
1. Process A が state 2 を参照
1. Process B が state 1 でCASを試みるが stateは2なので失敗
1. Process A が state 2でCASを試み、成功して state は3に更新
1. Process B が state 3 を参照
1. Process B が state 3 でCASを試み、成功して state は4に更新

memcached や redis などの主流のKVSでは CAS命令（compare and swap
もしくはcheck and set）が用意されており、ロックをかけずに一貫性を
保証する手段として有効性が広く認知されているものと思われます。

**Comment by genki** [comment]
Process A, Bによる同時更新のタイミングが違うケースをもう一つ例示いたします。

1.    Process A が state を 1 に更新
1.   Process B が state 1 を参照
1.    Process B が state を 2 に更新
1.    Process A が state 1 でCASを試みるが stateは2なので失敗
1.    Process A が state 2 を参照
1.    Process B が state 2でCASを試み、成功して state は3に更新
1.    Process A が state 2 でCASを試みるが stateは3なので失敗
1.    Process A が state 3 を参照
1.    Process A が state 3でCASを試み、成功して state は4に更新

こちらもデッドロックなどの問題は発生しません。
また、stateの参照からCASの実行までの時間はごく短時間に
行われるため、更新処理が交差して上記のようにCASが失敗する
ケースは実際にはほとんど発生しません。

**Comment by s-yata** [comment]
object と state の一貫性やコストについては，私が CPU の CAS 命令レベルで考えていたので話が咬み合っていないのかもしれません． @genki さんの例では object の更新がでてこないので…．

それから，繰り返しになりますが， `grn_obj_set_value` などはスレッドセーフではありません．どこかでロックは必要になります．そして， DB として使うときはコマンドレベルでロックをおこなっているはずです．そのため， @genki さんの仰るような安全な CAS を提供するには，内部でロックするしかありません．外でロックするか中でロックするかの違いになります．

**Comment by genki** [comment]
@s-yata 私の想定でも、内部でロックせずにstateを確認して更新を行うにはCPUのCAS命令を使って実装する必要があると思っています。

Groonga C APIのスレッドセーフかどうかに関するドキュメント的なものってありますでしょうか。利用例のソースコードから推測するしかなくてきちんと理解できていないのですが、例えば rroongaの実装を見た感じですと、 grn_obj_set_value の排他制御は行われていないように思われました。

**Comment by s-yata** [comment]
@genki 私が API としての CAS と CPU の CAS 命令とをきちんと区別できずに混乱していた感じです．

時間がなくて確認できないのですが，残念ながら，きちんとしたものはないと思います．私の知っている範囲では，まず `grn_ctx` がスレッドセーフではなくて，スレッド毎に用意する必要があります．同じ DB に対する `grn_ctx` については `grn_ctx_use` で増やせます．各種関数は基本的に，更新が非スレッドセーフで，参照がスレッドセーフだと思います．

Rroonga は使ったことがないので分かりかねますが， Groonga の設計思想を踏襲して，細かいところで排他制御はしないようにしているのかなと思います．

**Comment by kou** [comment]
あれ、`grn_obj_set_value()`ってスレッドセーフじゃなかったでしたっけ。

実装をみると、`grn_ja`だけが安全なんですね。コアAPIはスレッドアンセーフでDB APIはスレッドセーフだった気がするのでロック漏れな気がしますがどうだろう。。。

**Comment by s-yata** [comment]
ひょっとして私の勘違いでしょうか…！？

**Comment by genki** [comment]
これは、ドキュメントが必要な気がします。
スレッドセーフとは関係ないですが、現状ではGroonga C APIを使っているプロダクトは、削除操作が連続して発生している状態で更新操作を行うと意図しないレコードを更新してしまう可能性がある実装が多いのではないかと思われます。

**Comment by kou** [comment]
`grn_obj_set_value()`はスレッドセーフでした。

**Comment by genki** [comment]
良かったです :)

**Comment by s-yata** [comment]
お騒がせして申し訳ありませんでした．
