### ISSUE TITLE
Release Groonga 6.0.1

### ISSUE THREAD

**Issue by kenhys** [groonga/groonga#506]
3/29に6.0.1をリリースする。

- [x] ディストリビューションごとの対応
  - [x] Ubuntu: Vividの削除
- [x] NEWS
  - [x] newsの更新 (@kenhys)
  - [x] newsの翻訳 (@kenhys)
- [x] リリースノートを書く
  - [x] 英語
  - [x] 日本語
- [x] ドキュメントの更新
  - [x] rstの更新
  - [x] poを翻訳
- [x] ドキュメントのアップロード
- [x] タグ打ちとソースアップロード
- [x] パッケージのアップロード
      - [x] Debian
      - [x] Ubuntu (launchpad)
      - [x] CentOS
      - [x] Windows
- [x] ブログエントリを書く
  - [x] 英語
  - [x] 日本語
- [x] リリースアナウンス
  - [x] groonga-dev
  - [x] groonga-talk
  - [x] Twitter
  - [x] Facebook

**Comment by kenhys** [comment]
newsについて更新と翻訳をやる。

**Comment by kenhys** [comment]
次、リリースノートを準備する

**Comment by kenhys** [comment]
リリースノートと日本語のブログエントリを準備した。

**Comment by s-yata** [comment]
間際のタイミングで申し訳ないのですが，以下の内容をリリースノート（とりあえず日本語のみ）に加えていただくことは可能でしょうか？
http://groonga.org/ja/blog/2016/03/28/chunk-split.html

**Comment by kenhys** [comment]
わかりました、案内に入れておきます！

**Comment by s-yata** [comment]
ありがとうございます．よろしくお願いします．

**Comment by kenhys** [comment]
リリースノートの下書きとblogエントリにも「静的索引によるフレーズ検索の高速化」の項目を追加した。

**Comment by s-yata** [comment]
ありがとうございます！

**Comment by kenhys** [comment]
あとはFacebookでの宣伝。いつもすとうさんがやっているのかなコレ。

**Comment by kou** [comment]
私がやっていますがそれもやってもらえると助かります。
最近はFacebookが一番反応があります。

**Comment by kenhys** [comment]
やっておこう、と思ったんですが、Facebookのアカウント情報ってどこにあるんでしたっけ。。。

**Comment by kenhys** [comment]
メンバーになればよいとうことを結城さんに教えてもらった。

**Comment by kenhys** [comment]
結城さんにメンバーとして追加してもらったので、投稿しておく。

**Comment by kenhys** [comment]
投稿done.

**Comment by kenhys** [comment]
ひととおりすんだのでclose

**Comment by kou** [comment]
Facebookにも英語のリリースアナウンスをしてもらえるとうれしいです！

**Comment by kenhys** [comment]
おおっと、それもでした。とうわけで英語のも追加しておきました。
