### ISSUE TITLE
インデックス対象のカラムが空の場合、grn_ii_build2がエラーになる

### ISSUE THREAD

**Issue by naoa** [groonga/groonga#508]
以下のようにインデックス対象のカラムの中身が空の場合にgrn_ii_build2を使うとトークナイザー内のノーマライズ処理でエラーになります。他方grn_ii_buildの場合は成功します。

まだ、まったくソースを追っていませんが、ii_build2の方は、テキストが空の場合の処理が何かないのかもしれません。
対応できますでしょうか？

```bash
table_create docs TABLE_PAT_KEY Int32
column_create docs description COLUMN_SCALAR LongText

table_create docs#description TABLE_PAT_KEY ShortText --default_tokenizer TokenBigram --normalizer NormalizerAuto

load --table docs
[
["_key","description"],
[1,"hoge"],
[2,""]
]

column_create docs#description index COLUMN_INDEX|WITH_POSITION docs description
```

```bash
% rm -f /tmp/db*;  GRN_INDEX_CHUNK_SPLIT_ENABLE=1 groonga -n /tmp/db < rep.dump
[[0,1459177266.69794,0.000948905944824219],true]
[[0,1459177266.69895,0.000476837158203125],true]
[[0,1459177266.69945,0.000792741775512695],true]
[[0,1459177266.70028,0.000581741333007812],true]
[[0,1459177266.7009,0.000317096710205078],2]
[[-52,1459177266.70125,0.00487685203552246,"[tokenizer] failed to open normalized string",[["grn_tokenizer_query_open","tokenizer.c",166]]],false]
```

**Comment by s-yata** [comment]
すみません．修正しておきます！

**Comment by s-yata** [comment]
空文字列に対して `grn_token_cursor_open`, `grn_token_cursor_next` するとエラーになるみたいです．
なんとなくサイズ 0 の領域を確保しようとして NULL が返ってきてエラーになっていそうな気がします．

ii.c よりトークナイザか正規化するところを修正すべきかもしれません．

**Comment by s-yata** [comment]
`grn_string_open_` はサイズが 0 のときは NULL を返すようになっていて， `grn_tokenizer_query_open` がそれをエラー扱いするみたいです．

- `grn_string_open_`
 - https://github.com/groonga/groonga/blob/6be6a17ee6a67ececb80dcb4358b9f435532c634/lib/string.c#L139-L141
- `grn_tokenizer_query_open`
 - https://github.com/groonga/groonga/blob/6be6a17ee6a67ececb80dcb4358b9f435532c634/lib/tokenizer.c#L156-L168

`grn_free_default` あたりを見ると NULL を `free` しようとして新たに問題が起きそうなので， ii.c 側で対処します．

**Comment by kou** [comment]
`NULL`を`free()`はC言語の仕様的に問題ないので、その使い方は大丈夫です！

**Comment by kou** [comment]
別件なんですが、静的索引構築のときにテキストじゃない値（数値とか）もトークナイズしようとするコードになっているので、後で直さないとなぁと思っています。（メモ）

**Comment by s-yata** [comment]
`grn_free_default` は ALERT レベルでログを出すみたいなので， `GRN_FREE` については NULL を許さないスタンスかなぁと…．

- `grn_free_default`
 - https://github.com/groonga/groonga/blob/6be6a17ee6a67ececb80dcb4358b9f435532c634/lib/ctx.c#L2587-L2600

今回のケースについては，空文字列に対してトークナイズしようとしてコストをかけるのは勿体ないので，いずれにせよ ii.c で対処した方が良いと思います．

**Comment by kou** [comment]
うは。これは`ALERT`を消しておきます。

ii.cで対応するのはよいと思います！

**Comment by s-yata** [comment]
Text 以外をトークナイズしてしまう件については issue を作成しておきます．

**Comment by s-yata** [comment]
修正完了いたしました．

```
$ GRN_INDEX_CHUNK_SPLIT_ENABLE=1 src/groonga --file issue-508.grn -n /tmp/groonga/db
[[0,1459221894.78031,0.00107216835021973],true]
[[0,1459221894.78145,0.000622987747192383],true]
[[0,1459221894.78213,0.000611543655395508],true]
[[0,1459221894.7828,0.000153541564941406],2]
[[0,1459221894.783,0.00409173965454102],true]
```

**Comment by naoa** [comment]
あざす！
でっかいので試してみようと思っています。
