### ISSUE TITLE
msgpack 1.4.0 removes deprecated `libmsgpack`

### ISSUE THREAD

**Issue by cosmo0920** [groonga/groonga#512]
msgpack 1.4.0 removed deprecated libmsgpack library.
ref: https://github.com/msgpack/msgpack-c/issues/395#issuecomment-174019730

Should we use `libmsgpackc` instead of `libmsgpack`?
Or, search both of `libmsgpack` and `libmsgpackc`?

**Comment by kou** [comment]
Groonga uses `msgpack.pc`. `msgpack.pc` reports `-lmsgpackc`.
Why does we need to care about it?

**Comment by cosmo0920** [comment]
Oh, this issue is caused by Homebrew!
We should leave as-is.... :<

**Comment by kou** [comment]
No problem.
