### ISSUE TITLE
grn_cache_*() should not use grn_gctx concurrently

### ISSUE THREAD

**Issue by s-yata** [groonga/groonga#515]
#### Description

`grn_cache_*()` may use `grn_gctx` concurrently and it can cause a crash.

Related: #503, #507

**Comment by s-yata** [comment]
#### Memos

1. All the caches are associated with `grn_gctx` and require exclusive access to `grn_gctx`.
2. `grn_cache` uses a static variable `grn_cache_current` to keep the current cache. It seems that a process can't use more than one caches in parallel.
3. If `grn_hash_create` fails in `grn_cache_open`, `cache->hash` becomes NULL and it will cause a crash.

**Comment by kou** [comment]
Done!

**Comment by s-yata** [comment]
Excellent!
