### ISSUE TITLE
データがあるサイズ以上になるとgrn_ii_build2でうまくインデックスが作成できない

### ISSUE THREAD

**Issue by naoa** [groonga/groonga#517]
データがある大きさ以上になると（たぶんトークン数依存?）、grn_ii_build2でうまくインデックスが作成できないようです。column_createコマンドは成功しますが、インデックスのサイズが非常に小さく、検索もできません。

```bash
 GRN_INDEX_CHUNK_SPLIT_ENABLE=1 groonga --log-level dump --log-path groonga.
log -n db/db < dump.grn
[[0,1459455860.45156,0.000535726547241211],true]
[[0,1459455860.45214,0.000341176986694336],true]
[[0,1459455860.4525,0.000463247299194336],true]
[[0,1459455860.45299,0.000445842742919922],true]
[[0,1459455860.45345,0.000427484512329102],true]
[[0,1459455860.4539,27.3962512016296],183173]
[[0,1459455887.85017,282.228671073914],true]
[[0,1459456170.07887,0.000302314758300781],[[[0],[["app_id","ShortText"]]]]]
```

以下のdumpファイルで再現が可能です。圧縮後1.1G、展開後5.6Gぐらいです。
このdumpファイルから最後の１レコードを削除すると、うまくインデックスが作成できます。
そこに成功と失敗の境界条件がありそうです。

https://drive.google.com/file/d/0B7YROOOhfA8QZ05GeHVXVWNaQnM/view?usp=sharing

調査願いますでしょうか。

**Comment by s-yata** [comment]
ご報告ありがとうございます．
調査いたします．

**Comment by s-yata** [comment]
ダウンロードして問題なく展開できました．
最初の実行結果と併せると以下のようになりますね．

```
$ GRN_INDEX_CHUNK_SPLIT_ENABLE=1 groonga --log-level dump --log-path groonga.log -n db/db < dump.grn

> table_create terms TABLE_PAT_KEY ShortText --default_tokenizer TokenBigram --normalizer NormalizerAuto
[[0,1459455860.45156,0.000535726547241211],true]

> column_create terms term COLUMN_SCALAR ShortText
[[0,1459455860.45214,0.000341176986694336],true]

> table_create docs TABLE_PAT_KEY ShortText --normalizer NormalizerAuto
[[0,1459455860.4525,0.000463247299194336],true]

> column_create docs app_id COLUMN_SCALAR ShortText
[[0,1459455860.45299,0.000445842742919922],true]

> column_create docs description COLUMN_SCALAR LongText
[[0,1459455860.45345,0.000427484512329102],true]

> load --table docs
> [
> ...
> ]
[[0,1459455860.4539,27.3962512016296],183173]

> column_create terms description COLUMN_INDEX|WITH_POSITION docs description
[[0,1459455887.85017,282.228671073914],true]

> select docs --match_columns description --query 'データベース' --output_columns 'app_id'
[[0,1459456170.07887,0.000302314758300781],[[[0],[["app_id","ShortText"]]]]]
```

**Comment by s-yata** [comment]
失敗したときの `groonga.log` は残っているでしょうか？
もし残っているのであれば，内容を確認したいです．

**Comment by naoa** [comment]
ログです。いくつかトークンが長すぎるwarningがありますが、省略しています。
今思いついたのですが、トークン数依存だと仮定すると、Normalizerを切ってTokenUnigramにするともっと再現セットのサイズをコンパクトに再現できるかもしれませんのでやってみます。

```
2016-03-31 14:10:03.438279|n| grn_init: <6.0.1-48-g697737c>
2016-03-31 14:10:03.444016|n| DDL:table_create terms
2016-03-31 14:10:03.444564|n| DDL:column_create terms term
2016-03-31 14:10:03.445062|n| DDL:table_create docs
2016-03-31 14:10:03.445546|n| DDL:column_create docs app_id
2016-03-31 14:10:03.446016|n| DDL:column_create docs description
2016-03-31 14:10:34.003351|n| DDL:column_create terms description
2016-03-31 14:10:34.006377|n| DDL:set_source terms.description docs.description
2016-03-31 14:13:00.702097|w| [token_next] ignore too long token. Token must be less than or equal to 4096: <5853>(<agtaaagttgacacctttacagaagtga....
...

2016-03-31 14:15:15.360097|i| [object][search][index][key][exact] <terms.description>
2016-03-31 14:15:15.360108|i| grn_ii_sel > (データベース)
2016-03-31 14:15:15.360127|i| exact: 0
2016-03-31 14:15:15.360145|i| unsplit: 0
2016-03-31 14:15:15.360257|i| partial: 0
2016-03-31 14:15:15.360259|i| hits=0
2016-03-31 14:15:15.493523|n| grn_fin (0)
```

**Comment by naoa** [comment]
1レコード削除して成功するときのlogは、たしかselectの前にchuck ~sizeとかがでますが、失敗するときは何も出ていません。

**Comment by s-yata** [comment]
ありがとうございます．
最後に chunk size などが出力されていないということは，きちんとフラッシュがおこなわれていない可能性が高いです．
現在，手元で動作確認をしているところです．

**Comment by naoa** [comment]
TokenUnigramにしてしまうと再現できず、単純にNormalizerをなくしたTokenBigramだと、レコード1万件減らしても再現し(検索できない)、レコード5万件減らすと再現しません(検索できる)でした。そこまで大きく再現セットが減らせるわけではないようなので、上記の再現セットから調査をよろしくお願いします。

レコードを１件を減らして成功する時のログは以下の通りです。

```bash
 GRN_INDEX_CHUNK_SPLIT_ENABLE=1 groonga --log-level dump --log-path groonga
3.log -n db2/db < dump.grn
[[0,1459479695.70596,0.00141644477844238],true]
[[0,1459479695.7075,0.000883579254150391],true]
[[0,1459479695.70845,0.000929594039916992],true]
[[0,1459479695.70945,0.000860452651977539],true]
[[0,1459479695.71036,0.000840902328491211],true]
[[0,1459479695.71129,30.6142916679382],183172]
[[0,1459479726.32561,308.742613554001],true]
[[0,1459480035.06825,0.0352387428283691],[[[8835],[["app_id","ShortText"]],["JP20000000003"],["JP20000000004"],["JP20000000059"],["JP20000000103"],["JP20000000139"],["JP20000000162"],["JP20000000170"],["JP20000000279"],["JP20000000306"],["JP20000000371"]]]]
```

```
2016-03-31 20:01:35.695494|n| grn_init: <6.0.1-48-g697737c>
2016-03-31 20:01:35.706427|n| DDL:table_create terms
2016-03-31 20:01:35.707549|n| DDL:column_create terms term
2016-03-31 20:01:35.708496|n| DDL:table_create docs
2016-03-31 20:01:35.709482|n| DDL:column_create docs app_id
2016-03-31 20:01:35.710391|n| DDL:column_create docs description
2016-03-31 20:02:06.325618|n| DDL:column_create terms description
2016-03-31 20:02:06.326840|n| DDL:set_source terms.description docs.description
2016-03-31 20:04:31.770684|w| [token_next] ignore too long token. Token must be less than or equal to 4096: <5853>(<agtaaagttgacacctttacagaagtgatc...
....
2016-03-31 20:07:14.577501|d| n_terms = 2815, chunk_offset = 1048377, chunk_size = 1048576, total = 3336537KB
2016-03-31 20:07:14.643506|d| n_terms = 3160, chunk_offset = 1044872, chunk_size = 1048576, total = 3343098KB
2016-03-31 20:07:14.688482|d| n_terms = 3977, chunk_offset = 1047343, chunk_size = 1048576, total = 3347951KB
2016-03-31 20:07:14.716659|d| n_terms = 3721, chunk_offset = 1010178, chunk_size = 1048576, total = 3351014KB
2016-03-31 20:07:15.068351|i| [object][search][index][key][exact] <terms.description>
2016-03-31 20:07:15.068361|i| grn_ii_sel > (データベース)
2016-03-31 20:07:15.068445|i| n=5 (データベース)
2016-03-31 20:07:15.103216|i| exact: 8835
2016-03-31 20:07:15.103223|i| hits=8835
2016-03-31 20:07:15.368598|n| grn_fin (0)
```

**Comment by s-yata** [comment]
内部のカウンタを `+=` すべきところが `=` になっているという実につまらない内容ながらクリティカルなバグがありました．このバグを修正して問題なく動作するようになるか確認します．

**Comment by s-yata** [comment]
修正により，手元での実行結果は以下のようになりました．

```
$ GRN_INDEX_CHUNK_SPLIT_ENABLE=1 groonga --file dump.grn --log-level dump --log-path groonga.log -n db/db
[[0,1459494070.91703,0.00413370132446289],true]
[[0,1459494070.92165,0.0018467903137207],true]
[[0,1459494070.92377,0.00175118446350098],true]
[[0,1459494070.9257,0.000976324081420898],true]
[[0,1459494070.92679,0.00076746940612793],true]
[[0,1459494070.92763,88.6711621284485],183173]
[[0,1459494159.59915,580.963520765305],true]
[[0,1459494740.56738,0.0972220897674561],[[[8835],[["app_id","ShortText"]],["JP20000000003"],["JP20000000004"],["JP20000000059"],["JP20000000103"],["JP20000000139"],["JP20000000162"],["JP20000000170"],["JP20000000279"],["JP20000000306"],["JP20000000371"]]]]
```

**Comment by s-yata** [comment]
データが大きくなると駄目だった原因は，内部カウンタが頻繁にクリアされてフラッシュの条件を満たさなくなったことにあります．

本来であれば，ある程度のデータを処理した時点で一時ファイルにフラッシュするのですが，ここがスキップされて，すべてのデータをメモリ上に持つようになっていました．手元では途中でメモリが不足しておかしくなりました．今回の修正により，適切にフラッシュされるようになっています．

**Comment by naoa** [comment]
なるほど、ありがとうございます。どんだけでかくなっても、ずーっとメモリにもっていておかしいなと思っていました。とりあえず、私の方でも最小の再現ケースでうまくインデックスが作られることを確認しました。
また、何かありましたら報告します。

**Comment by naoa** [comment]
grn_ii_buildではうまく作成できなかったインデックスサイズが315GiBぐらいのものでも、grn_ii_build2ではうまくインデックスが作成できるようになりました！ありがとうございます。
構築時間もii_buildとほとんど遜色がなく、サイズもやや小さくなるようで非常にありがたいです。
(だいたい23時間ぐらい。マルチスレッドで並列処理できたりすると嬉しいですが、難しいですかね。。）

これはトピック外ですが、文書数とフレーズ中のトークンの出現数が多いとminを設定するデメリットの方が大きくなることが多いようです。最悪ケースだと１５倍遅かったりします。たぶんここのループ回数ですかね。dgapを先頭のchunk_infoから足していかないとridを復元できなくて線形探索するしかないんですかね。
https://github.com/groonga/groonga/blob/master/lib/ii.c#L4374-L4382

ii_cursor_set_minをすると不利になることが推定できれば、するかしないかを設定できるパラメータがあるといいかもしれません。chunkサイズをいじってchunk数を減らすのも効果があるかもしれません。色々試してみようと思います。

| Token:estimate size(Vgram tokenizer) | N hits  | Normal     | GRN_II_CURSOR_SET_MIN_ENABLE=1 |
|--------------------------------------|---------|------------|--------------------------------|
| データベ:378354 ベース:321365        | 376880  | **0.6064 sec** | 0.7316 sec                     |
| レーザー:490506 ー光:132413          | 153887  | **0.0993 sec** | 0.1563 sec                     |
| 光ポ:1401 ポート:750355              | 841     | 0.0291 sec | **0.0133 sec**                     |
| 接続ポ:17690 ポート:750355           | 13641   | **0.0356 sec** | 0.0505 sec                     |
| 詳細な説:8729533 細な説明:8729531    | 8729531 | **1.0377 sec** | 16.0283 sec                    |
| 詳細な説:8729533 な説明を:22494      | 203132  | **0.1596 sec** | 0.6413 sec                     |
| 詳細な説:8729533 明をユ:536          | 10      | 0.1325 sec | **0.0095 sec**                     |
| 詳細な説:8729533 な説明が:17471      | 9264    | **0.1341 sec** | 0.1354 sec                     |
| 詳細な説:8729533 な説明に:70150      | 63189   | **0.1434 sec** | 0.3008 sec                     |

**Comment by s-yata** [comment]
大規模なテスト＆ご報告ありがとうございます．とても参考になります．

`grn_ii_build` で駄目だったのは，単一チャンクに詰め込んでいたらからチャンクサイズの上限に達していた…とかですかね（多分）． ` grn_ii_build2` は複数チャンクに分割するので大丈夫なのかもしれません．

dgap の件は #519 で既に片付いちゃっていますね．ありがとうございます！

**Comment by s-yata** [comment]
マルチスレッド化については， Groonga 内部での複数スレッド使用ということで新戦略になります．
まずは試しにやってみるというのもありかもしれません．
検討してみます．

**Comment by naoa** [comment]
ii_buildで失敗していたのは、たしか、[ここ](https://github.com/groonga/groonga/blob/master/lib/ii.c#L8162)のbufferの上限をくらってました。

私のはちょっと大きいのを無理しすぎていると思いますが、静的索引構築がより速くなると嬉しいケースは結構あると思うので、マルチスレッドで高速化できるとかなり嬉しいですね。ゆるりと期待しています。

**Comment by s-yata** [comment]
分割しない実装（`grn_ii_build`）では buffer 直結の chunk にすべて詰め込もうとするので， buffer の使用率が低いのに chunk のサイズが閾値を超えてしまい，どんどん新しい buffer を作って buffer 数が上限に達してしまうことで失敗していたのだと思います．

マルチスレッド化については，ゆるりとご期待下さい．
