### ISSUE TITLE
grn_table_atの使いどころについて

### ISSUE THREAD

**Issue by genki** [groonga/groonga#520]
ドキュメントには grn_table_at はコストが高いので濫用を控えよ、という記述があるのですが、どのようなケースでチェックする必要があり、どういうケースでは呼ぶ必要が無いのか、もう少し明確な基準が示されているとありがたいです。

具体的には、以下のような事が分かりますでしょうか。

1. grn_table_get で取得したgrn_idはgrn_table_atで存在確認する必要があるのかどうか。
2. テーブルのレコードが削除される場合、grn_obj_get_value の前に常に grn_table_at で存在を確認する必要があるかどうか
3. テーブルのレコードが削除されない場合、grn_table_atは不要であるか

**Comment by genki** [comment]
手元で実験した限りでは、レコードを削除した直後に同一キーで grn_table_get した grn_id は GRN_ID_NILではないケースがあり、grn_table_atで確認が必須なのかな、という想像をしております。
逆にレコードの削除がない場合、grn_table_atは不要なのでは、という想像をしておりますが、こちらも確信は得られておりません。

**Comment by kou** [comment]
そのIDが有効かどうかわからないケースで使う必要があります。Groogna内では、`load`でIDを指定してレコードをロードするときに使っています。ユーザーが指定したIDが妥当なIDかどうかわからないからです。

> grn_table_get で取得したgrn_idはgrn_table_atで存在確認する必要があるのかどうか。

ありません。`grn_table_get`は有効なIDを返すからです。

> テーブルのレコードが削除される場合、grn_obj_get_value の前に常に grn_table_at で存在を確認する必要があるかどうか

確認と`grn_obj_get_value`を呼び出す間に削除される可能性があるので確認する意味が薄いです。

クリティカルセッションにして処理の期間中はIDを有効な状態にしておく方が現実的だと思います。

> テーブルのレコードが削除されない場合、grn_table_atは不要であるか

前述の`load`のように、有効なIDかどうかわからないIDが指定される可能性があるなら必要です。有効なIDだとわかっているのであれば不要です。

**Comment by kou** [comment]
> 手元で実験した限りでは、レコードを削除した直後に同一キーで grn_table_get した grn_id は GRN_ID_NILではないケースがあり、grn_table_atで確認が必須なのかな、という想像をしております。

テーブルの種類と再現方法を教えてもらえませんか？おかしな挙動のように見えます。

**Comment by genki** [comment]
@kou ありがとうございます。なるほど、loadの場合に使うのですね。

＞テーブルの種類と再現方法
種類はHashで、keyはShortText、レコード数は7000万ぐらい、Columnは10個程度（textとuint32）です。
grn_table_delete した直後に同じkeyに対して grn_table_get するとほぼ必ず GRN_ID_NIL ではない値が帰ってきて、grn_obj_get_value すると削除前の値も取得できます。
体感ですが、deleteしてから1秒ぐらい経つと GRN_ID_NILが返るようになります。
2プロセス、80x2スレッドぐらいで動いています。

**Comment by genki** [comment]
ちなみに上記環境のソースコードは https://github.com/genki/hog です。

**Comment by kou** [comment]
情報ありがとうございます。

> grn_table_delete した直後に同じkeyに対して grn_table_get するとほぼ必ず GRN_ID_NIL ではない値が帰ってきて、grn_obj_get_value すると削除前の値も取得できます。
> 体感ですが、deleteしてから1秒ぐらい経つと GRN_ID_NILが返るようになります。
> 2プロセス、80x2スレッドぐらいで動いています。

これは同一プロセス・同一スレッドでも発生しますか？それとも、別プロセスのときだけ発生しますか？あるいは、同一プロセス・別スレッドのときだけ発生しますか？

**Comment by genki** [comment]
小規模なDBでは発生しない（したとしても超短時間で検出できないのかもしれない）ので、本番環境でしか検証できず厳密ではないのですが、恐らく同一プロセス同一スレッドでも発生していると思います。もう少し厳密に検証できるようなコードを入れてみます。

仮に、別プロセスや別スレッドである場合はこういったラグが発生する事は想定されている挙動なのでしょうか。その場合、削除の完了を待つような仕組みはありますでしょうか。

**Comment by kou** [comment]
ありがとうございます。

ラグが発生するなら`mmap()`絡みかもしれません。

同一プロセス・同一スレッドで発生するなら、`grn_table_delete()`が完全に終了した後に`grn_table_get_value()`していることになるので、なにか問題がありそうな気がします。

別プロセスや別スレッドで`grn_table_delete()`している最中に`grn_table_get()`しているならそういうこともありえると思います。`grn_table_delete()`を呼び出した直後にそのIDが無効になるわけではないので、実際に無効になる前に`grn_table_get()`したら`GRN_ID_NIL`じゃないIDが返ってくると思います。

実際に問題が発生しているときの状況がわからないと推測の域をでないので、まずは、状況の把握を先にするのがいいと思っています。

**Comment by genki** [comment]
かしこまりました。分かり次第詳報をお伝えいたします。

**Comment by kou** [comment]
ありがとうございます。

**Comment by genki** [comment]
調査した所、

1. 同一プロセス、同一スレッドの場合 → 遅延なし
2. 同一プロセス、別スレッドの場合は遅延あり
3. 別プロセスの場合は遅延あり

という結果でした。それぞれ、delete の応答をまち、処理が完了した後に get を行いました。
mmapの反映が行われてない感じでしょうかね。

**Comment by kou** [comment]
ありがとうございます。

同一プロセス・別スレッドで発生するなら`mmap()`は関係なさそうです。同じデータベースを複数のスレッドで共有している場合は、`mmap()`した領域も共有しているからです。

「deleteの応答を待ち」というのは https://github.com/genki/hog/blob/master/src/del.c のレスポンスが返ってきてから、ということですか？コードを見ると`HOG_SEND`がないのでレスポンスは返ってこなそうなんですがどうやって応答を待っていますか？

**Comment by genki** [comment]
ある程度の時間(500ms) sleepしてから実行したのですが、確かにdelete処理にもっと時間が掛かっているとすると、それが原因である気がします。
確実に同期を取るような手段を実装して検証してみます。

**Comment by genki** [comment]
delete処理の完了後に応答を返すようにして応答を待ったところ、ラグが発生しない事が確認できました。deleteに想像以上に時間がかかっていたというのが真相でした。
お手数をおかけいたしました。

**Comment by kou** [comment]
確認ありがとうございました。
