### ISSUE TITLE
doc: grn_expr needs more detailed explanation

### ISSUE THREAD

**Issue by genki** [groonga/groonga#535]
I couldn't find examples about AND or OR search by using grn_expr in documents.
I think it's difficult to guess the correct usage of grn_expr functions without examples.

There are at least two possible options:
1. calling grn_table_select twice
2. building a complicated grn_expr by pushing some stuff. 

Which way is better?

**Comment by kou** [comment]
> 2. building a complicated grn_expr by pushing some stuff.

It's better.

Here is a sample code that show how to build `a @@ "keyword1" && b @@ "keyword2"` condition:

```c
/* a @@ "keyword1" && b @@ "keyword2" */

/* a @@ "keyword1" */
grn_expr_append_obj(ctx, expr, column_a, GRN_OP_PUSH, 1);
grn_expr_append_const_str(ctx, expr, "keyword1", strlen("keyword1"), GRN_OP_PUSH, 1);
grn_expr_append_op(ctx, expr, GRN_OP_MATCH, 2);

/* b @@ "keyword2" */
grn_expr_append_obj(ctx, expr, column_b, GRN_OP_PUSH, 1);
grn_expr_append_const_str(ctx, expr, "keyword2", strlen("keyword2"), GRN_OP_PUSH, 1);
grn_expr_append_op(ctx, expr, GRN_OP_MATCH, 2);

/* A && B */
grn_expr_append_op(ctx, expr, GRN_OP_AND, 2);
```

PGroonga is a real world example. You can find many `grn_expr_append_*()` at [pgroonga.c](https://github.com/pgroonga/pgroonga/blob/master/src/pgroonga.c)

**Comment by genki** [comment]
Thank you for the example and pointer!
