### ISSUE TITLE
新しく作成した静的索引で検索漏れがある

### ISSUE THREAD

**Issue by s-yata** [groonga/groonga#551]
#### 概要

旧実装（`GRN_INDEX_CHUNK_SPLIT_ENABLE=no`）を使って作成した静的索引では検索できたものが，新実装を使って作成した静的索引で検索できなくなることがあります．

以下に例を示します．この例では，ヒット件数が 3,025 から 3,023 に減っています．詳しく調べてみると，検索漏れが起きていると判明しました．

```
## 旧実装（GRN_INDEX_CHUNK_SPLIT_ENABLE=no）を使って静的索引を作成したとき
$ groonga db.old/db
> select tbl --match_columns 'col4' --query 'コース' --output_columns '_id,_score'
[[0,1465293529.228552,0.008726596832275391],
 [[[3025],[["_id","UInt32"],["_score","Int32"]],[8,1],[18,1],[23,3],[24,4],[34,1],[86,10],[87,1],[98,2],[133,1],[157,1]]]]
```

```
## 新実装を使って静的索引を作成したとき
$ groonga db.new/db
> select tbl --match_columns 'col4' --query 'コース' --output_columns '_id,_score'
[[0,1465293530.429,0.02821159362792969],
 [[[3023],[["_id","UInt32"],["_score","Int32"]],[8,1],[18,1],[23,3],[24,4],[34,1],[86,10],[87,1],[98,2],[133,1],[157,1]]]]
```

なお，検索漏れが起きるのは，複数のカラムに対する索引のみです． `column_create` で `WITH_SECTION` が指定されていなければ影響はありません．

**Comment by s-yata** [comment]
一時ファイルにフラッシュするタイミングをレコードの境界とすべきところがセクションの境界となっており，以降の処理はレコードの境界を前提としていたためにおかしくなっていました．

**Comment by s-yata** [comment]
新しい grntest であれば， `generate-series` を使って再現できます．

[issue-551.test.txt](https://github.com/groonga/groonga/files/304602/issue-551.test.txt)

**Comment by kou** [comment]
テスト時間が短くなるようにしてpushしました。

**Comment by s-yata** [comment]
ありがとうございます！
