### ISSUE TITLE
selector関数でトークナイザーが指定されたインデックスを使えない

### ISSUE THREAD

**Issue by naoa** [groonga/groonga#589]
たとえば、以下のようにすると、``in_values``関数にはindexが渡されていませんでした。

```
table_create Tags TABLE_PAT_KEY ShortText   --default_tokenizer TokenBigram   --normalizer NormalizerAuto
[[0,0.0,0.0],true]
table_create Memos TABLE_HASH_KEY ShortText
[[0,0.0,0.0],true]
column_create Memos tag COLUMN_SCALAR ShortText
[[0,0.0,0.0],true]
column_create Tags memos_tag COLUMN_INDEX Memos tag
[[0,0.0,0.0],true]
load --table Memos
[
{"_key": "Groonga is fast", "tag": "Groonga"},
{"_key": "Mroonga is fast", "tag": "Mroonga"}
]
[[0,0.0,0.0],2]
select Memos   --output_columns _key,tag   --filter 'in_values(tag, "groonga", "mroonga")'
[[0,0.0,0.0],[[[0],[["_key","ShortText"],["tag","ShortText"]]]]]
```

この例からトークナイザーを除くと、うまくindexが渡されて正常に検索できます。

**Comment by naoa** [comment]
``grn_column_find_index_data``で``GRN_OP_CALL``は、``grn_column_find_index_data_column_range``としており、

https://github.com/groonga/groonga/blob/master/lib/db.c#L12682

``grn_column_find_index_data_column_range```はトークナイザー有のインデックスをスキップしているからのようです。

https://github.com/groonga/groonga/blob/master/lib/db.c#L12215

``between``関数を想定して、こうなっていると思うのですが、``GRN_OP_CALL``は``grn_column_find_index_data_column_match``の方がよいのではないでしょうか？

``GRN_OP_CALL``で``grn_column_find_index_data_column_match``を使うようにすると一応上記の例は通るようになりました。

しかし、そうするとbetweenでトークナイザー有の方が優先して選ばれるおそれがあるんですかね。
よければ、ご意見ください。

**Comment by kou** [comment]
セレクター毎にどの演算用のインデックスを使うかを指定できるようにしました。
なので、`between()`は範囲検索用のインデックスを使う、`in_values()`は等価比較用のインデックスを使うということができるようになりました。

**Comment by naoa** [comment]
ありがとうございます
