### ISSUE TITLE
pgroonga index on primary key column cause IN operator not working

### ISSUE THREAD

**Issue by yongxianggao-chanjet** [groonga/groonga#600]
If we use the the test case from tutorial:

CREATE TABLE score_memos (
  id integer PRIMARY KEY,
  content text
);

CREATE INDEX pgroonga_score_memos_content_index
          ON score_memos
       USING pgroonga (id, content);

INSERT INTO score_memos VALUES (1, 'PostgreSQL is a relational database management system.');
INSERT INTO score_memos VALUES (2, 'Groonga is a fast full text search engine that supports all languages.');
INSERT INTO score_memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga as index.');
INSERT INTO score_memos VALUES (4, 'There is groonga command.');

SET enable_seqscan = off;

SELECT * FROM score_memos WHERE id in (1, 2, 3, 4);

We will see 0 row returns

**Comment by kou** [comment]
Thanks for your report.
Could you re-report it to https://github.com/pgroonga/pgroonga/issues/new ? pgroonga/pgroonga (not groonga/groonga) is the PGroonga repository.

**Comment by yongxianggao-chanjet** [comment]
Done, the new issue is here: https://github.com/pgroonga/pgroonga/issues/21

**Comment by kou** [comment]
Thanks!
