### ISSUE TITLE
Gronga 6.0.9

### ISSUE THREAD

**Issue by kenhys** [groonga/groonga#603]
9/29に6.0.9をリリースする。

- [x] ディストリビューションごとの対応
  - [x] debian: 増減はなし
  - [x] ubuntu: 増減はなし 来月は16.10を追加。
  - [x] centos: 増減はなし
- [x] NEWS
  - [x] newsの更新
  - [x] newsの翻訳
- [x] リリースノートを書く
  - [x] 英語
  - [x] 日本語
- [x] ドキュメントの更新
  - [x] rstの更新
  - [x] poを翻訳
- [x] ドキュメントのアップロード
- [x] タグ打ちとソースアップロード
- [x] パッケージのアップロード
      - [x] Debian
      - [x] Ubuntu (launchpad)
      - [x] CentOS
      - [x] Windows
- [x] ブログエントリを書く
  - [x] 英語
  - [x] 日本語
- [x] リリースアナウンス 9/29
  - [x] groonga-dev
  - [x] groonga-talk
  - [x] Twitter
  - [x] Facebook

* GRN_INDEX_CHUNK_SPLIT_ENABLE, GRN_II_CURSOR_SET_MIN_ENABLE 静的索引構築の改善は2016/05にデフォルトで有効になった。
環境変数でon/offできるというのはまだ残す(なんかあったときにデバッグしたい)。2017/2/9のメジャーバージョンアップで削除する。

* MySQLとPostgreSQLと日本語全文検索3は今日ですよ！というのをリリースノートに忘れずに入れて、おきたい。が、リリースノートが間に合うか。

**Comment by kenhys** [comment]
アナウンスまわりは @myokoym さんが手伝ってくれることになった。とても助かる。

**Comment by myokoym** [comment]
ドキュメントのアップロードをしました。

**Comment by myokoym** [comment]
各所にアナウンスしました。残作業はなさそうなので閉じます。（あとはMroongaですね。。。）
