### ISSUE TITLE
selectの説明でsort_keysではなくsortbyが使われている部分が残っている

### ISSUE THREAD

**Issue by piroor** [groonga/groonga#604]
チュートリアルでsortbyが使われている。
http://groonga.org/ja/docs/tutorial/introduction.html#sort-a-search-result
Groonga 6.0.3からはsort_keysになっているので、チュートリアルを直す。
http://groonga.org/ja/docs/reference/commands/select.html#sortby

他にもsort_keysではなくsortbyになっている部分が残っているかもしれないので、見直す必要がある。

同様のチェックをdrilldown→drilldownsについても行う。

**Comment by kou** [comment]
http://groonga.org/ja/docs/reference/commands/select.html#syntax に`drilldown[label].sortby`の記述が残っていた。
`drilldown[label].sortby`も`drilldown[label].sort_keys`推奨という書き方にしないといけない。

**Comment by s-yata** [comment]
すみません．
c0503b1398167618680cd16e8613d02911e0b3b8 も関連コミットなのですが，コミットメッセージに書く番号を間違えてしまいました．

チュートリアルの `sortby`, `drilldown_sortby` は `sort_keys`, `drilldown_sort_keys` に変更しました．
reference 以下， `select` で `sortby` を使っていたところを `sort_keys` に変更しました．

**Comment by s-yata** [comment]
`drilldown[label]` は news 内と deprecated の説明にしか出てこないようです．
