### ISSUE TITLE
Check usage about return value of grn_ctx_at()

### ISSUE THREAD

**Issue by kenhys** [groonga/groonga#613]
grn_ctx_at()がNULLを返すことがあり、(おそらく)クラッシュの原因となるケースがあった。

a05f929ca

他にも同様の箇所がないか点検し、問題があれば修正する。
grn_ctx_at()はあちこちで使用されている。

```
% gg grn_ctx_at lib | wc -l
254
% gg grn_ctx_at src | wc -l
9
% gg grn_ctx_at plugins | wc -l
5
```

src:以下

```
% gg grn_ctx_at src
src/suggest/groonga_suggest_learner.c:      if ((table = grn_ctx_at(ctx, table_id))) {
src/suggest/groonga_suggest_learner.c:            ref_table = grn_ctx_at(ctx, grn_obj_get_range(ctx, col_kana));
src/suggest/groonga_suggest_learner.c:            ref_table = grn_ctx_at(ctx, grn_obj_get_range(ctx, col_pre));
src/groonga.c:                                  grn_ctx_at(ctx, GRN_DB_UINT32));
src/groonga.c:                                   grn_ctx_at(ctx, GRN_DB_UINT32));
src/groonga.c:                                grn_ctx_at(ctx, GRN_DB_UINT64));
src/groonga.c:    cache_table = grn_ctx_at(ctx, cache_value->header.domain);
src/groonga.c:                                     grn_ctx_at(ctx, GRN_DB_SHORT_TEXT),
src/groonga.c:                                      grn_ctx_at(ctx, GRN_DB_SHORT_TEXT));
```

plugins:以下
```
% gg grn_ctx_at plugins
plugins/suggest/suggest.c:    grn_obj *pairs = grn_ctx_at(ctx, grn_obj_get_range(ctx, co));
plugins/suggest/suggest.c:        if ((cur = grn_table_cursor_open(ctx, grn_ctx_at(ctx, index->header.domain),
plugins/suggest/suggest.c:  learner->seqs = seqs = grn_ctx_at(ctx, GRN_OBJ_GET_DOMAIN(learner->seq));
plugins/suggest/suggest.c:  learner->events = events = grn_ctx_at(ctx, events_id);
plugins/suggest/suggest.c:  learner->items = items = grn_ctx_at(ctx, GRN_OBJ_GET_DOMAIN(post_item));
```

lib:以下は大量にあるのでファイル単位でチェック。

* [ ] lib/dat.cpp:
* [ ] lib/db.c:
* [ ] lib/db.c:grn_ctx_at(grn_ctx
* [ ] lib/expr.c:
* [ ] lib/geo.c:
* [ ] lib/grn_db.h:
* [ ] lib/grn_ecmascript.c:
* [ ] lib/grn_ecmascript.lemon:
* [ ] lib/hash.c:
* [ ] lib/ii.c:
* [ ] lib/index_column.c:
* [ ] lib/mrb/mrb_bulk.c:
* [ ] lib/mrb/mrb_converter.c:
* [ ] lib/mrb/mrb_ctx.c:
* [ ] lib/mrb/mrb_index_column.c:
* [ ] lib/mrb/mrb_index_cursor.c:
* [ ] lib/mrb/mrb_indexable.c:
* [ ] lib/obj.c:
* [ ] lib/operator.c:
* [ ] lib/output.c:
* [ ] lib/pat.c:
* [ ] lib/plugin.c:
* [ ] lib/proc.c:
* [ ] lib/proc/proc_column.c:
* [ ] lib/proc/proc_dump.c:
* [ ] lib/proc/proc_fuzzy_search.c:
* [ ] lib/proc/proc_highlight.c:
* [ ] lib/proc/proc_object_inspect.c:
* [ ] lib/proc/proc_schema.c:
* [ ] lib/proc/proc_select.c:
* [ ] lib/proc/proc_table.c:
* [ ] lib/proc/proc_tokenize.c:
* [ ] lib/report.c:
* [ ] lib/str.c:
* [ ] lib/ts.c:
* [ ] lib/ts/ts_expr_builder.c:
* [ ] lib/ts/ts_expr_node.c:
* [ ] lib/ts/ts_util.c:
* [ ] lib/util.c:

**Comment by kenhys** [comment]
groonga.c は #614 で対応した。

**Comment by kenhys** [comment]
src/suggest/groonga_suggest_learner.c: の`grn_ctx_at` の返り値 `ref_table` を参照している箇所では`grn_table_get_key` の引数として指定されていて、`grn_table_get_key`ではNULLチェックしているので問題なし。

**Comment by kou** [comment]
やった方がいいんだろうけど、やっていないのでクローズ。
