### ISSUE TITLE
Add note for environments with disabled EPEL

### ISSUE THREAD

**Issue by piroor** [groonga/groonga#631]
https://gitter.im/groonga/ja?at=58816c2811e7a7f61dbcdcf6

> たかさん
> @tigersun2000_twitter
> 1月 20 10:47
> 昨日Amazon Linuxにインストールしたのですが、epelリポジトリが必須でした。参考までに。
> sudo yum install percona-server-57-mroonga --enablerepo=epel
> Kouhei Sutou
> @kou
> 1月 20 16:58
> はい、最近のリリースからEPELを必須にしました。LZ4やZstandardを有効にするためです。
> たかさん
> @tigersun2000_twitter
> 1月 20 21:38
> 
> はい。ちょうどそうなってました。
> 
> インストールドキュメント更新するにはどうしたらいいでしょうか？
> http://mroonga.org/ja/docs/install/centos.html
> Kouhei Sutou
> @kou
> 1月 21 20:25
> 
> https://github.com/mroonga/mroonga/tree/master/doc/source/install 以下のファイルを更新してpull request送ってください。
> 
> ただ、今のドキュメント通りやってもEPELを自動でインストールして使うようになっているんですが、自分でEPELを明示的に無効にして使っていたりしませんか？
> たかさん
> @tigersun2000_twitter
> 1月 22 11:31
> @kou あー、そういう意味ではCentOSとAmazon Linuxのepelの初期動作が違うのかも、Amazon Linuxだと初期インストールは以下のようにenableが無効になっています。
> 
> name=Extra Packages for Enterprise Linux 6 - $basearch
> #baseurl=http://download.fedoraproject.org/pub/epel/6/$basearch
> mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
> failovermethod=priority
> enabled=0
> gpgcheck=1
> gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
> 
> たかさん
> @tigersun2000_twitter
> 1月 22 12:01
> という事は、サポートOSじゃない、OSを使っているからという問題で、ドキュメント更新すべき話ではないのかもしれませんね。失礼しました。

参考情報として、EPELが無効化されている場合の注意書きを追加する。（Groonga, Mroonga共に）

**Comment by myokoym** [comment]
過去のドキュメントではEPELについての注釈があったが、現在は削除されている様子
http://movie.hexacosa.net/doc/groonga-doc/ja/html/install/centos.html

**Comment by myokoym** [comment]
https://github.com/groonga/groonga/commit/2a2a6f59229716596fc94bfc6ae7dfd039349c74 で対応していただいていました。閉じます。
