### ISSUE TITLE
CentOS packages: Add libstemmer package as build-dep or create additional token-filter-stem package?

### ISSUE THREAD

**Issue by nomoon** [groonga/groonga#633]
As groonga/groonga#430 suggests, bundling https://github.com/snowballstem/snowball directly into groonga may be desirable. In the meantime, the Ubuntu package definitions have provided an additional `token-filter-stem` package built on release.

On CentOS/RHEL, this is not yet the case, though `libstemmer` and `libstemmer-devel` packages are available for that platform. Would it be preferable to modify the CentOS/yum RPM spec to build an additional package (like Ubuntu does), or to simply include `libstemmer-devel` as a build requirement, thus building the token filter as part of the main `groonga-libs` package?

My skill in editing RPM specs might not be quite at the level required to define an additional package, but I could attempt a PR to that effect.

**Comment by kou** [comment]
`groonga-token-stem-stem` is provided for CentOS 7 since the next release.

**Comment by nomoon** [comment]
@kou thanks again for the amazingly fast response!
