### ISSUE TITLE
検索語に":"が含まれていると検索結果が欠落する

### ISSUE THREAD

**Issue by genki** [groonga/groonga#639]
バージョンは7.0.0です。検索語が"foo:bar"のように半角の":"を含んでいるケースで、6.1.5での検索結果と比べて結果が著しく欠落するようになりました（例: 2270件→18件）

検索対象のカラムはText型, インデックスは
```
"TABLE_PAT_KEY|PERSISTENT","ShortText",null,"TokenBigram"
```
です

**Comment by genki** [comment]
C API経由やRroongaで検索した場合は構文エラーにはならず検索できますが、":"を含む検索語では6.1.5で実行した場合とくらべて検索結果がかなり欠落してしまっています。

**Comment by kou** [comment]
再現するテストデータを提供してもらうことは可能でしょうか？

**Comment by genki** [comment]
再現データの作成は難しいですが、古いバージョンから使い続けているものなので、
7.0.0でインデックスの再構築を行ってもう一度試してみます

**Comment by genki** [comment]
7.0.0でdump/restoreした結果、正常な検索結果が得られるようになりました。
... -> 6.1.1 -> 6.1.5 -> 7.0.0 といった感じに移行してきたDBですが、何らかの原因でindexが壊れていたようです。

**Comment by kou** [comment]
DBの互換性は壊していないつもりなので、なにか問題があるのかもしれないですね。。。
