### ISSUE TITLE
Groonga exhausts all CPU resources for a couple of minutes periodically

### ISSUE THREAD

**Issue by genki** [groonga/groonga#686]
These days, my Groonga server exhausts all CPU resources for a couple of minutes about once a day. The size of DB is about 80GB with 80M records.

Here's the version info:

```
Groonga 7.0.2 [linux-gnu,x86_64,utf8,match-escalation-threshold=0,nfkc,msgpack,onigmo,epoll]

configure options: < '--prefix=/usr' '--disable-maintainer-mode' '--disable-dependency-tracking' '--disable-groonga-httpd' 'CFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security'>
```

I guess that some processes, such as defrag or vacuum, contain busy loop.

**Comment by kou** [comment]
I think that it's the first step that we identify what process consumes all CPU resources.

Did you find the problem with your hog server? Or `groonga -s` server?

**Comment by genki** [comment]
@kou I am using the hog built with libgroonga 7.0.2.
But the hog is very thin wrapper for the libgroonga and `perf top` reported that there is a part being busy in the libgroonga.so. 
The all source code of the hog I used is here: https://github.com/genki/hog

**Comment by kou** [comment]
OK.
Did you keep `perf.data`? I want to run `perf report` to confirm which function is slow.

**Comment by genki** [comment]
I don't have it. I will try it next time.
Though after I have taken dump and restore the DB, the issue is not happening...

**Comment by kou** [comment]
> I will try it next time.

Thanks! It'll be helpful that we know which function is slow to resolve this problem.

> Though after I have taken dump and restore the DB, the issue is not happening...

Oh...

**Comment by kou** [comment]
Can't reproduce.

**Comment by genki** [comment]
I agree with you in these days this issue is not happen. The current version is stable.
