### ISSUE TITLE
How to add custom tokenzier

### ISSUE THREAD

**Issue by chenzhekl** [groonga/groonga#757]
I walked through the documentation but found no mention about using custom tokenizer. Appreciate it if anyone could provide some instructions.

**Comment by naoa** [comment]
Does the using custom tokenizer mean how to use built-in tokenizers?
If so, you can change it with ``default_tokenizer`` option of ``table_create`` command.
The following is example to use ``TokenBigramSplitSymbolAlpha`` tokenizer.

* ``table_create`` command's document
http://groonga.org/docs/reference/commands/table_create.html#default-tokenizer

* Available built in tokenizers
http://groonga.org/docs/reference/tokenizers.html#built-in-tokenizsers

```
table_create Lexicon TABLE_PAT_KEY ShortText --default_tokenizer TokenBigramSplitSymbolAlpha --normalizer NormalizerAuto
[[0,0.0,0.0],true]
table_create Memos TABLE_NO_KEY
[[0,0.0,0.0],true]
column_create Memos name COLUMN_SCALAR ShortText
[[0,0.0,0.0],true]
column_create Lexicon index COLUMN_INDEX|WITH_POSITION Memos name
[[0,0.0,0.0],true]
load --table Memos
[
{"name": "Groonga is fast!"},
{"name": "Mroonga is fast!"}
]
[[0,0.0,0.0],2]
select Memos   --filter 'name @ "roon"'
[
  [
    0,
    0.0,
    0.0
  ],
  [
    [
      [
        2
      ],
      [
        [
          "_id",
          "UInt32"
        ],
        [
          "name",
          "ShortText"
        ]
      ],
      [
        1,
        "Groonga is fast!"
      ],
      [
        2,
        "Mroonga is fast!"
      ]
    ]
  ]
]
```

If you want to develop custom tokenizer, the following is simply sample code for developing custom tokenizer.

https://github.com/groonga/groonga-tokenizer-sample

**Comment by chenzhekl** [comment]
Thanks you! `groonga/groonga-tokenizer-sample` is exactly what I'm looking
for. BTW, is there documentation for the C Api of Groonga?

**Comment by naoa** [comment]
There is C API documentation here.
http://groonga.org/docs/reference/api.html

However, it is not perfect, I recommend that you see the files under ``include/groonga.h`` and look into source code is used it.

**Comment by chenzhekl** [comment]
Really appreciate your help!!
