### ISSUE TITLE
in_valuesで127個以上の値を指定したい

### ISSUE THREAD

**Issue by kenhys** [groonga/groonga#760]
# Problem

`[groonga-dev,04449] indexを使ったin_valuesでの不具合` より

https://ja.osdn.net/projects/groonga/lists/archive/dev/2017-August/004452.html

indexを使ったin_values(target, value1, ..., valueN)でvalueNの数が増えると正しい結果を取得できない。
(具体的には126件までしか持ってこれない)

#  Expected

127件以上指定していても正しい結果を取得できる。

# How to reproduce it

```
groonga -n testdb/db < schema.txt
groonga testdb/db < load.txt
groonga testdb/db < 127.txt
```

[127.txt](https://github.com/groonga/groonga/files/1266520/127.txt)
[load.txt](https://github.com/groonga/groonga/files/1266521/load.txt)
[schema.txt](https://github.com/groonga/groonga/files/1266522/schema.txt)

# Additional information

GRN_SCAN_INFO_MAX_N_ARGSの制限に引っかかっているのでvalueNは126個まで。

現状のままだと無理だが、 `in_values(column, [1, 2, 3, ...])` みたいに1つのベクターで指定できるようにin_values()を拡張するという案がある。

**Comment by s-yata** [comment]
初期のバッファサイズを 16 に減らし，不足したときは動的に拡張するようにしました．

**Comment by s-yata** [comment]
初期のバッファから新しいバッファへとコピーし忘れるという致命的なバグを修正しました．
