### ISSUE TITLE
grn_log_level_parseが定義されていない

### ISSUE THREAD

**Issue by myamanishi3** [groonga/groonga#775]
久々にGroongaのアップデートをしていて、コンパイルができません。

OS X 10.12.6で、configureを使ってMakefileを作る方法です。止まるところのエラーを解析すると、"grn_log_level_parse"が定義されていないように読めます。この関数はgroonga.hにヘッダが定義されていますが、実体の定義を見つけられません。環境異存的なもんだいでしょうか？

objs/ngx_modules.o \
	-L/usr/local/lib -L/usr/local/lib -L/usr/local/src/groonga-7.0.8/lib/.libs -L/usr/local/src/groonga-7.0.8/vendor/onigmo-source/.libs -lgroonga -lpcre -lssl -lcrypto -lz
Undefined symbols for architecture x86_64:
  "_grn_log_level_parse", referenced from:
      _ngx_http_groonga_conf_set_log_level_slot in ngx_http_groonga_module.o

**Comment by kou** [comment]
`-L/usr/local/lib`の方が`-L/usr/local/src/groonga-7.0.8/lib/.libs`より前にあるのですでにシステムにインストールされている古いGroongaを使ってしまっているように見えます。

このフラグって標準で追加されるんでしたっけ。なにか思い当たることはありますか？

**Comment by myamanishi3** [comment]
ご指摘で何が悪いか理解しました。ありがとうございました。

5.0.0をインストールしています。フラグはconfigureが自動的に取捨選択したものです。前のバージョンが悪さしているとは思っても見ませんでした。

**Comment by kou** [comment]
うーん、`config.log`をこのissueに添付してもらえませんか？

**Comment by myamanishi3** [comment]
/usr/local/libの下のlibgroonga.*を削除して、Makeし直した所、コンパイルは最後まで通りました。

すでに書き換えてしまったので、あとでもう一度再現してみます。

**Comment by kou** [comment]
よろしくお願いします。
すでにインストールされていてもビルドできるようにしたいなぁと思っています。

**Comment by kou** [comment]
あ、あと、`vendor/nginx-1.13.6/objs/Makefile`も添付して欲しいです。

**Comment by myamanishi3** [comment]
5.0.0のソースディレクトリが残っていたので、そのままmake installして前の環境に戻したあと、7.0.8を改めてtarから展開後configureして、makeいたしました所、状況が再現できました。

ご指定のファイルを添付します。（Makefileの方はgithubが受け付けてくれなかったので、圧縮しました）お役に立ちますでしょうか？

[config.log](https://github.com/groonga/groonga/files/1425827/config.log)

[Makefile.zip](https://github.com/groonga/groonga/files/1425832/Makefile.zip)

**Comment by kou** [comment]
ありがとうございます。`src/httpd/nginx-module/config`を次のように書き換えて（`$groonga_cflags`と`$groonga_libs`を前に持ってくる）`configure && make`するとどうなるか確認してもらえませんか？

```diff
diff --git a/src/httpd/nginx-module/config b/src/httpd/nginx-module/config
index b79eef6ba..78129daa6 100644
--- a/src/httpd/nginx-module/config
+++ b/src/httpd/nginx-module/config
@@ -22,8 +22,8 @@ if [ "$GROONGA_HTTPD_IN_TREE" = yes ]; then
   ngx_addon_name=ngx_http_groonga_module
   HTTP_MODULES="$HTTP_MODULES ngx_http_groonga_module"
   NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_groonga_module.c"
-  CFLAGS="$CFLAGS $groonga_cflags"
-  CORE_LIBS="$CORE_LIBS $groonga_libs"
+  CFLAGS="$groonga_cflags $CFLAGS"
+  CORE_LIBS="$groonga_libs $CORE_LIBS"
 
   return 0
 fi
```

**Comment by myamanishi3** [comment]
エラーメッセージは変わらず/usr/local/libの方を先に観ているような感じです。どこかもう少し上位で定義されているか、指定のconfigを無視しているか。（それとも、書き換え方が悪かったか？本日は時間切れとなりました。ヒントを頂ければ明日再開します）

objs/ngx_modules.o \
	-L/usr/local/lib -L/usr/local/lib -L/usr/local/src/groonga-7.0.8/lib/.libs -L/usr/local/src/groonga-7.0.8/vendor/onigmo-source/.libs -lgroonga -lpcre -lssl -lcrypto -lz
Undefined symbols for architecture x86_64:

**Comment by kou** [comment]
うーん、そうですかぁ。

`vendor/ngx_mruby-source/Makefile.in`の


```makefile
CFLAGS = $(MRUBY_CFLAGS) -I/usr/local/include
LDFLAGS = $(MRUBY_LDFLAGS) -L/usr/local/lib
```

の`/usr/local/...`を抜いて

```makefile
CFLAGS = $(MRUBY_CFLAGS)
LDFLAGS = $(MRUBY_LDFLAGS)
```

として`configure && make`だとどうでしょうか。

**Comment by myamanishi3** [comment]
vendor/ngx_mruby-source/Makefile.inを修正してみましたが、結果が変わらないようです。

vendor/nginx-1.13.6のMakefileおよびobj/Makefileはvendor/nginx-1.13.6/auto以下のconfigureスクリプトで発生させているように見えます。vendor/nginx-1.13.6のディレクトリで'./auto/configure'と打ってMakefileを発生させてやると、LDFLAGSが"-lpcre -lz"と非常にシンプルです。何処かでこのスクリプトを起動しているのではないかと想像しますが、その際のLDFLAGSに-L/usr/local/libなどが渡されているとか、でしょうか？

**Comment by kou** [comment]
たぶん、そうだと思います！
どこで渡しているのかは、再現している環境で、二分探索的にprintデバッグするのが一番楽なんですが、私の手元だと再現していないのでそれができなくて、勘でここらへん？とすることしかできないのが現状です。

再現している環境でちょっと調べてみてもらえないでしょうか？****

**Comment by kou** [comment]
あ、`vendor/nginx-1.13.6/auto/configure`を実行しているのは`src/httpd/configure`です！

**Comment by myamanishi3** [comment]
src/httpd/configureについて、下のような変更をしたところ、configure & makeが最後まで通りました。

--- configure.orig	2017-10-31 19:20:38.000000000 +0900
+++ configure	2017-10-31 19:21:17.000000000 +0900
@@ -112,8 +112,6 @@
   --http-log-path="${GROONGA_HTTPD_HTTP_LOG_PATH}" \
   --add-module="${GROONGA_HTTPD_MODULE_PATH}" \
   --pid-path="${GROONGA_HTTPD_PID_PATH}" \
-  --with-cc-opt="${cc_opt}" \
-  --with-ld-opt="${ld_opt}" \
   --with-http_stub_status_module \
   --with-http_v2_module \
   ${configure_args}

**Comment by myamanishi3** [comment]
すません、diffの出力を貼り付けたのですが、文字化けしているかもしれません。行頭に●がある行は、「削除」した行です。

**Comment by kou** [comment]
あぁ、diffを貼るときは↓というようにするといいですよ。（前のコメントのやつは私が直しておきました。）

    ```diff
    --- ...
    +++ ...
    ...
    ```

これでビルドできるようになるということは、PCREかOpenSSLが/usr/localにあるのかしら。

トップディレクトリーにある`groonga-httpd-conf.sh`の中身を見せてもらえますか？

あと、 https://github.com/groonga/groonga/commit/de7fc2d6848f1f9768758044d53172bbc8c90a5f で直ると思うので、以下を試してみてもらえませんか？

```console
% wget -O src/httpd/configure https://raw.githubusercontent.com/groonga/groonga/master/src/httpd/configure
% wget -O src/httpd/nginx-module/config https://raw.githubusercontent.com/groonga/groonga/master/src/httpd/nginx-module/config
% ./configure
% make
```

**Comment by myamanishi3** [comment]
Mac（OS X）だと推奨されていないのかもしれないんですが、MacはUNIXもどきとして使っており、パッケージ管理システムとかを使っておりません。Slackware使っていたので、特に苦にならず、必要なものは自分でコンパイルして入れてきました。PCREも

```prefix="/usr/local"
exec_prefix="${prefix}"
sbindir="${exec_prefix}/sbin"
libdir="${exec_prefix}/lib"
sysconfdir="${prefix}/etc"
pkgsysconfdir="${sysconfdir}/groonga"
localstatedir="${prefix}/var"

EXEEXT=""

SED="/usr/bin/sed"

export GROONGA_HTTPD_MODULE_PATH="/usr/local/src/groonga-7.0.8/src/httpd/nginx-module"
export GROONGA_HTTPD_IN_TREE_INCLUDE_PATH="/usr/local/src/groonga-7.0.8/include"
export GROONGA_HTTPD_IN_TREE_LINK_PATH="/usr/local/src/groonga-7.0.8/lib/.libs"
export GROONGA_HTTPD_PREFIX="${pkgsysconfdir}/httpd"
export GROONGA_HTTPD_BIN_PATH="${sbindir}/groonga-httpd${EXEEXT}"
export GROONGA_HTTPD_CONF_PATH="${pkgsysconfdir}/httpd/groonga-httpd.conf"
export GROONGA_HTTPD_ERROR_LOG_PATH="${localstatedir}/log/groonga/httpd/error.log"
export GROONGA_HTTPD_HTTP_LOG_PATH="${localstatedir}/log/groonga/httpd/access.log"
export GROONGA_HTTPD_GROONGA_LOG_PATH="${localstatedir}/log/groonga/httpd/groonga.log"
export GROONGA_HTTPD_GROONGA_QUERY_LOG_PATH="${localstatedir}/log/groonga/httpd/groonga-query.log"
export GROONGA_HTTPD_PID_PATH="/usr/local/var/run/groonga/groonga-httpd.pid"
export GROONGA_HTTPD_DEBUG="no"
export GROONGA_HTTPD_WITH_PCRE="yes"
export GROONGA_HTTPD_PCRE_CFLAGS="-I/usr/local/include "
export GROONGA_HTTPD_PCRE_LIBS_ONLY_L="-L/usr/local/lib "
export GROONGA_HTTPD_WITH_ONIGMO="yes"
export GROONGA_HTTPD_ONIGMO_IN_TREE_LINK_PATH="/usr/local/src/groonga-7.0.8/vendor/onigmo-source/.libs"
export GROONGA_HTTPD_WITH_ZLIB="yes"
export GROONGA_HTTPD_WITH_SSL="yes"
export GROONGA_HTTPD_SSL_CFLAGS="-I/usr/local/include "
export GROONGA_HTTPD_SSL_LIBS_ONLY_L="-L/usr/local/lib "
export GROONGA_HTTPD_WITH_MRUBY=""
```

**Comment by myamanishi3** [comment]
de7fc2dの補正を行って、groonga-5.xxがインストールされている環境でも7.0.8のコンパイルが通るようになりました。ありがとうございました。

**Comment by kou** [comment]
よかったです！
開発に参加してくれてありがとうございます！
