### ISSUE TITLE
正規表現の結果がhighlight_htmlできない

### ISSUE THREAD

**Issue by takagi01** [groonga/groonga#787]
mroongaの方からmroonga_commnadで正規表現を使って検索を行い、結果にタグをつけたいと
思ったのですが、うまくいきません。
select mroonga_command("select <<table_name>> --query \"content:~xxx\" --output_columns \"highlight_html(content)\" --command_version 2");
こんな感じで書きました。xxxのところは簡単な正規表現です。結果は帰って来ますが、タグがついていない
状態です。
よろしくお願いいたします。

**Comment by kou** [comment]
あぁ、これはなかなか難しい問題ですね。

ハイライト機能は事前にハイライト候補を用意してからテキスト中の候補を探す、という動きになっているんですが、正規表現だと候補をうまく作れない（`.*oonga`から`Groonga`、`Mroonga`、…とかすべてのパターンを作るのはムリ）んですよねぇ。

とりあえず、`.*`とか`\\A`とかを候補の区切りにして動くようにしておきました。たとえば、`r.*nga`は`r`と`nga`がハイライトされます。パターンによってはノイズが多くなりすぎるかも。。。
