### ISSUE TITLE
`grndb check` doesn't report internal error messages when something are corrupted.

### ISSUE THREAD

**Issue by genki** [groonga/groonga#818]
Looking into the source code, `grn_xxx_is_currupt` functions seem to try to report what is wrong by `SERR(...)` but `grndb check` doesn't report it regardlessly with `--log-level` option.

**Comment by kou** [comment]
Did you specify `--log-path` option?
`SERR(...)` message is logged into log file not standard output.

**Comment by genki** [comment]
@kou Oh, I misunderstood the default `--log-path` is `stdout` or `stderr`. thx!

**Comment by kou** [comment]
If we use the standard output or the standard error for log path, normal logs and `grndb` outputs are mixed... It confuses users...

**Comment by genki** [comment]
@kou I see. But specifying `--log-path /dev/stderr` is very handy for me :)
