### ISSUE TITLE
Add support for MSYS2 package

### ISSUE THREAD

**Issue by kou** [groonga/groonga#902]
We need to send a pull request to https://github.com/Alexpux/MINGW-packages .

If we have a MSYS2 package, we can use it in Rroonga.

**Comment by cosmo0920** [comment]
I've registered a PR to create Groonga MINGW package.
https://github.com/msys2/MINGW-packages/pull/5151

**Comment by cosmo0920** [comment]
Should we use Groonga MINGW package's maintainer as "Groonga developer"?

**Comment by kou** [comment]
Thanks.
You don't need to use "Groonga developer".

**Comment by cosmo0920** [comment]
https://github.com/msys2/MINGW-packages/pull/5151 is merged.
We can install Groonga in MSYS2 with pacman command:

```
$ pacman -Sy mingw-w64-x86_64-groonga
:: パッケージデータベースの同期中...
 mingw32 は最新です
 mingw64 は最新です
 msys は最新です
依存関係を解決しています...
衝突するパッケージがないか確認しています...

パッケージ (2) mingw-w64-x86_64-zeromq-4.3.1-1  mingw-w64-x86_64-groonga-9.0.3-1

合計ダウンロード容量:   4.06 MiB
合計インストール容量:  39.65 MiB
最終的なアップグレード容量:   6.53 MiB

:: インストールを行いますか？ [Y/n]
```
