### ISSUE TITLE
grn_windows_base_dir のバグ

### ISSUE THREAD

**Issue by yagisumi** [groonga/groonga#953]
windows(VC版)なんですが、groongaのdllが自分のパスを正しく取得できていないようです。
VC版のdllはlibgroonga.dllなのですが、GRN_DLL_FILENAMEがgroonga.dllになってしまっていて、
GetModuleHandleが0を返し、その結果GetModuleFileNameがexeのパスを取得してしまうようです。

ちなみに、GetModuleFileNameで取得したパスの頭には\\?\が付いてたりもするので、その処理も必要かと思います。

**Comment by kenhys** [comment]
報告ありがとうございます！

たしかにGRN_DLL_FILENAMEが意図しないものになりますね。。。
修正しておきます。

**Comment by kenhys** [comment]
GRN_DLL_FILENAMEの修正がはいっているので閉じます。
