### ISSUE TITLE
windowsでnroongaを使った時のgrn_windows_base_dir()が返す値について

### ISSUE THREAD

**Issue by yagisumi** [groonga/groonga#958]
windowsのnroongaからlibgroonga.dllが呼ばれた時に、GetModuleFileNameWで得られるパスが、例えば、
`\\?\G:\data\node\test\node_modules\nroonga\build\Release\libgroonga.dll`
みたいになるので、最終的に
`//?/G:/data/node/test/node_modules/nroonga/build/Release`
という感じで、ちょっと困ります。
(Mecabのプラグインで、設定ファイルのパスを渡すところなど)

どう扱うのが適切なのかはわかりませんが、`//?/`を削るしかないかなという気がします。

**Comment by cosmo0920** [comment]
`\\?\`はWIndowsのMAX_PATHの制限(大抵は255文字)を32,767文字に緩和するのに用いられるものなので、安易に削ると深いフォルダにGroongaがインストールされている場合に扱えない不具合が生じるものと考えられますが、その辺はどうでしょうか？

ref: https://docs.microsoft.com/ja-jp/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation

**Comment by yagisumi** [comment]
Groonga自体がwindowsの長いパスに対応してないので、長いパスにならないような所で使うしかないというのが現状です。

確認した所、`//?/`が付いているために、statで失敗してMeCabのプラグインを見つけられない不具合があって、そこをクリアしても、MeCabにmecabrcのパスを渡すとエラーになるので、`//?/`を削る必要がありそうです。

**Comment by komainu8** [comment]
ご報告いただきありがとうございます。

すみません。
まだ、手元で確認しきれていないので、少し教えていただきたいのですが、「//?/が付いているために、statで失敗してMeCabのプラグインを見つけられない」のと「MeCabにmecabrcのパスを渡すとエラーになる」のは、VC++版のGroongaで起きている問題ということでしょうか？
(いままでのMinGW版のGroongaでは起きておらず、VC++版のGroongaを使ったら発生したということでしょうか？)

**Comment by yagisumi** [comment]
VCとは関係ない話で、GetModuleFileNameWが返すdllのパスが、呼ばれた時と同じように返すことが原因となってます。
つまり、`\\?\`を付けて長いパスに対応しているプログラムから呼ばれると問題が起こることになります。
この長いパスに対応したプログラムはほぼ無いと言っていいくらいのものなんですが、node.jsは階層が深くなってパスが長くなりがちなので、真面目に対応しているのだと思います。
`\\?\`を付けたパスを扱うには、ユニコード(ワイド文字)だったり、全てバックスラッシュでないとダメだとか、いろいろ制限があったはずなので、普通に扱えないものとなっています。(テキトーな知識)

**Comment by komainu8** [comment]
ご回答いただきありがとうございます。

なるほど。常に`\\?\`のプレフィックスが付くわけではないんですね。
ありがとうございます。対応を検討します。

**Comment by kenhys** [comment]
@yagisumi 
なおす方向(ゆくゆくは長いパスにきちんと対応するとして、ひとまずは\\?を削る）でいこうかと思っているのですが、なおすにしてもnroongaのCI(AppVeyor)を先に整備しておきたいです。
windowsでnroongaを動かせるようにするまでに、どういう手順でビルドしたりしていたか教えてもらってもよいですか？

**Comment by yagisumi** [comment]
試しに作ってみたやつです。

https://github.com/yagisumi/nroonga/tree/helper-for-windows

windowsの場合は、ビルド前に`groonga-latest-(x64|x86)-vs2017-with-vcruntime.zip`をダウンロードして`win/groonga`に展開するスクリプトを動かすようにしてます。

`binding.gyp`はwindowsの場合の設定を、`win/groonga`以下に固定してます。

そしてライブラリを読み込む時には、`win/groonga/bin`にパスを通して、DLLが読み込まれるようにしています。

環境変数の`NRN_GROONGA_PATH_WIN_X64`または`NRN_GROONGA_PATH_WIN_X86`にVS版Groongaのパスを設定しておくと、zipをダウンロードせずに、それをコピーするようにしてます。

**Comment by kenhys** [comment]
@yagisumi おぉ、ありがとうございます。

手元でこんな感じかなぁと作っていたやつに↑も参考にして手を加えたやつを https://github.com/nroonga/nroonga/pull/53 にAppVeyorでのCIをまずフィードバックしてみました。

**Comment by yagisumi** [comment]
さっき確認してみたのですが、パスを通してDLLを読み込ませる時は、`\\?\`が付かないようです。

最初に作った時は、nroonga_bindings.nodeの場所にDLLをコピーして、PATHを設定せずにDLLを読み込ませてたのですが、その場合だけ`\\?\`が付くようです。

**Comment by yagisumi** [comment]
ということで大した問題ではなかったようです。
わりとどうでも良い話題に長々と付き合わせてしまって申し訳ないです

**Comment by kenhys** [comment]
`\\?\` の修正がはいったので閉じます。
